#!/usr/bin/env python3
"""Stage history-backed Batch 08 outcomes without serving or watchlist writes."""
from __future__ import annotations
import argparse,hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BACKEND=ROOT/'backend';sys.path.insert(0,str(BACKEND)) if str(BACKEND) not in sys.path else None
from app.us_valuation.artifacts import PUBLIC_SCHEMA_VERSION,sanitize_public_artifact
from app.us_valuation.batch_08 import BATCH_08_MANIFEST,BATCH_08_TICKERS,BATCH_08_VALUATION_DATE
from app.us_valuation.batch_08_history import BATCH_08_HISTORY_VERSION,EQUITY_EARNINGS_TICKERS,PASS_TICKERS,build_batch_08_history_result
from run_batch_07_history import PROTECTED,WATCHLIST,_immutable,_json,_tree

def _base(issuer,result,*,primary,model,assumptions,review_state='review_required'):
 source=result['source_ledger']['controlling_filing'];scenario=result['scenario_range'];url=f"https://www.sec.gov/Archives/edgar/data/{int(issuer.cik)}/{source['accession'].replace('-','')}/{source['primary_document']}"
 return {'schema_version':PUBLIC_SCHEMA_VERSION,'valuation_date':BATCH_08_VALUATION_DATE,'market':'US','currency':'USD','ticker':issuer.ticker,'issuer':{'cik':issuer.cik,'ticker':issuer.ticker,'issuer_name':issuer.issuer_name,'filing_regime':'10-K_10-Q','accounting_standard':'US-GAAP','sec_sic_code':None,'sec_sic_label':issuer.gics_sub_industry,'finsight_sector':issuer.gics_sector,'primary_archetype':issuer.primary_lane_id,'secondary_archetypes':[],'classification_confidence':.8,'mapping_version':'US-RESET-PARTITION-2026-08-14-2.0','classification_reason':'Frozen Batch 08 lane plus issuer-specific history review.','override_applied':True,'source_accessions':[source['accession']]},'source_financial_statement':{'form':source['form'],'period_end':source['period_end'],'filed_date':source['filed'],'accession':source['accession'],'url':url,'note':'Controlling filing anchors current inputs; company history or explicit comparative evidence anchors normalized assumptions.'},'primary_valuation_method':result['method'],'model_policy':{'primary':primary,'supporting':[],'blend_models':False,'reason':'History-backed source-bounded normalized cash-FCFF.' if primary=='fcff_dcf' else 'History-backed Conditional Low baseline with a named material dependency.','fallback_from':'fcff_dcf' if primary=='conditional_estimate' else None},'public_assumptions':assumptions,'models':{primary:model},'scenarios':{},'scenario_range':{**scenario,'label':'assumption range, not a statistical confidence interval or recommendation'},'sensitivities':[],'forecast_quality':{'policy_version':BATCH_08_HISTORY_VERSION,'status':review_state,'errors':[],'warnings':[result['warning']],'checks':{}},'review':{'publication_state':review_state,'confidence_grade':'source_bounded' if primary=='fcff_dcf' else 'conditional_low','errors':[],'warnings':[result['warning'],result['governed_assumptions']['invalidation'],result['governed_assumptions'].get('calculator_calibration','Calculator unavailable.')],'price_dependent_inputs_used':False,'prohibited_output_check':{'buy_hold_sell':False,'current_price':False,'trading_multiples':False,'upside_downside':False}},'reliability':result.get('history_reliability'),'confidence':{'label':None if result.get('history_reliability') is None else result['history_reliability']['label'],'reasons':[] if result.get('history_reliability') is None else result['history_reliability']['reasons']},'methodology':{'forecast_policy':BATCH_08_HISTORY_VERSION,'sector_framework':result['method'],'source_policy':'Reported facts remain private and separate from historical summaries and governed assumptions.'},'data_boundary':{'raw_financial_statement_values_included':False,'stock_prices_used':False,'public_payload_contains':'value range, reliability, warnings, historical-policy summary, assumptions and filing attribution'}}

def _public(issuer,result):
 availability=result['availability_type'];a=result['governed_assumptions'];scenario=result['scenario_range']
 if availability=='not_available':
  value=_base(issuer,result,primary='conditional_estimate',model={'model':'conditional_estimate','output_type':'conditional_value_per_share','currency':'USD','conditional_value_per_share':None,'publication_state':'withheld','errors':[result['warning']],'warnings':[result['warning']]},assumptions={'forecast_policy_version':BATCH_08_HISTORY_VERSION,'forecast_years':5,'forecast_mode':'unavailable_post_spin_history','history_policy_version':a['history_policy_version'],'history_years_used':0,'normalization_basis':a['normalization_basis'],'assumption_source_mix':a['assumption_source_mix'],'source_policy':'Reported SEC facts; no value emitted because comparable history is absent.'},review_state='withheld');value['review']['errors']=[result['warning']];public=sanitize_public_artifact(value)
  if public['availability_type']!='not_available' or public['scenario_range']['base'] is not None:raise RuntimeError(issuer.ticker)
  return public
 is_pass=availability=='available';primary='fcff_dcf' if is_pass else 'conditional_estimate';base=scenario['base'];value_field='intrinsic_value_per_share' if is_pass else 'conditional_value_per_share';model={'model':primary,'output_type':value_field,'currency':'USD',value_field:base,'publication_state':'review_required','errors':[],'warnings':[result['warning']]}
 common={'forecast_policy_version':BATCH_08_HISTORY_VERSION,'forecast_years':5,'history_policy_version':a['history_policy_version'],'history_years_used':a['history_years_used'],'normalization_basis':a['normalization_basis'],'assumption_source_mix':a['assumption_source_mix'],'equity_floor_applied':scenario['low']==0,'equity_floor_basis':a['equity_floor_basis'],'source_policy':'Reported SEC facts plus source-linked history and transparent FinSight assumptions; no stock price or analyst target.'}
 if issuer.ticker in EQUITY_EARNINGS_TICKERS or 'equity_earnings' in result['method']:assumptions={**common,'forecast_mode':'normalized_equity_earnings','normalized_earnings_factor':1.0,'earnings_multiple':a['earnings_multiples'][1],'diluted_shares':a['shares'][1],'diluted_shares_low':a['shares'][2],'diluted_shares_high':a['shares'][0]}
 else:assumptions={**common,'forecast_mode':'history_backed_normalized_cash_conversion','cash_conversion_margin_low':a['cash_conversion_margin'][0],'cash_conversion_margin':a['cash_conversion_margin'][1],'cash_conversion_margin_high':a['cash_conversion_margin'][2],'revenue_growth_low':a['growth'][0],'revenue_growth':a['growth'][1],'revenue_growth_high':a['growth'][2],'diluted_shares':a['shares'][1],'diluted_shares_low':a['shares'][2],'diluted_shares_high':a['shares'][0]}
 value=_base(issuer,result,primary=primary,model=model,assumptions=assumptions)
 if is_pass:value['bridge_quality']={'blocking_fields':[],'bounded_fields':[],'complete':True,'decision':'complete','intrinsic_value_range':{'low':base,'midpoint':base,'high':base,'spread_ratio':0.0,'spread_limit':.01},'reason_codes':[],'usable':True}
 public=sanitize_public_artifact(value);expected='available' if is_pass else 'conditional_estimate'
 if public['availability_type']!=expected or public['scenario_range']['base']!=base:raise RuntimeError(f'{issuer.ticker}: public mismatch')
 return public

def run(*,source_root:Path,structural_root:Path,output_root:Path):
 source_root,structural_root,output_root=map(Path,(source_root,structural_root,output_root));before={str(root):_tree(root) for root in PROTECTED};watch=hashlib.sha256(WATCHLIST.read_bytes()).hexdigest();cases=[];reliability={'High':0,'Medium':0,'Low':0}
 for issuer in BATCH_08_MANIFEST:
  result=build_batch_08_history_result(ticker=issuer.ticker,source_root=source_root,structural_root=structural_root);public=_public(issuer,result);availability=result['availability_type'];outcome='pass' if availability=='available' else 'conditional' if availability=='conditional_estimate' else 'withheld';label=None if result['history_reliability'] is None else result['history_reliability']['label'];
  if label:reliability[label]+=1
  case={'ticker':issuer.ticker,'outcome':outcome,'availability_type':availability,'reliability':label,'method':result['method'],**result['scenario_range'],'history_years_used':result['governed_assumptions'].get('history_years_used'),'warning':result['warning']};private={'schema_version':'FINSIGHT-BATCH-08-HISTORY-1','batch':8,'valuation_date':BATCH_08_VALUATION_DATE,'issuer':{'ticker':issuer.ticker,'cik':issuer.cik,'issuer_name':issuer.issuer_name},'history_backed':result,'controlled_outcome':case};_immutable(output_root/'generated'/issuer.ticker/'valuation-private.json',_json(private));_immutable(output_root/'staged-public'/f'{issuer.ticker}.json',_json(public));cases.append(case)
 after={str(root):_tree(root) for root in PROTECTED};watch_after=hashlib.sha256(WATCHLIST.read_bytes()).hexdigest()
 if before!=after or watch!=watch_after:raise RuntimeError('Batch 08 changed protected state')
 report={'schema_version':'FINSIGHT-BATCH-08-HISTORY-REPORT-1','batch':8,'valuation_date':BATCH_08_VALUATION_DATE,'policy_version':BATCH_08_HISTORY_VERSION,'denominator_tickers':list(BATCH_08_TICKERS),'attempted_count':10,'pass_count':sum(r['outcome']=='pass' for r in cases),'conditional_count':sum(r['outcome']=='conditional' for r in cases),'withheld_count':sum(r['outcome']=='withheld' for r in cases),'numeric_count':sum(r['outcome']!='withheld' for r in cases),'pass_tickers':[r['ticker'] for r in cases if r['outcome']=='pass'],'conditional_tickers':[r['ticker'] for r in cases if r['outcome']=='conditional'],'withheld_tickers':[r['ticker'] for r in cases if r['outcome']=='withheld'],'reliability_counts':reliability,'serving_artifacts_changed':False,'serving_hash_before':before,'serving_hash_after':after,'watchlist_changed':False,'watchlist_sha256':watch,'cases':cases};_immutable(output_root/'batch-08-report.json',_json(report));return report

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',required=True,type=Path);p.add_argument('--structural-root',required=True,type=Path);p.add_argument('--output-root',required=True,type=Path);r=run(**vars(p.parse_args()));print(json.dumps({k:r[k] for k in ('attempted_count','pass_count','conditional_count','withheld_count','numeric_count','reliability_counts','serving_artifacts_changed','watchlist_changed')},sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
