"""Public-safe and frontend artifacts for filing-only U.S. valuations."""

from __future__ import annotations

import json
from copy import deepcopy
from math import isclose, isfinite
from pathlib import Path
from typing import Any

from .automated_review import REVIEW_VERSION, assess_artifact
from .bridge_policy import BridgeAssessment, POLICY_VERSION
from .equity_models import public_equity_artifact
from .reliability import (
    accounting_label,
    lowest_label,
    relative_movement,
    scenario_label,
)
from .sec_client import normalize_cik
from .xbrl import load_concept_config


def write_json(path: Path, value: Any) -> None:
    """Atomically write a JSON artifact."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def write_javascript_module(path: Path, value: Any, *, generator: str) -> None:
    """Atomically write a generated frontend module."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        f"// Generated by {generator}.\n"
        "// Do not edit by hand; regenerate from the frozen SEC source cache.\n"
        f"export default {json.dumps(value, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def sec_cache_manifest(cache: Path, cik: str | int) -> dict[str, Any]:
    """Return durable provenance metadata for both SEC source responses."""
    normalized = normalize_cik(cik)
    records = []
    for name in (
        f"CIK{normalized}-submissions.json",
        f"CIK{normalized}-companyfacts.json",
    ):
        metadata_path = cache / f"{name}.meta.json"
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        records.append({"cache_file": name, **metadata})
    return {"status": "frozen_sec_cache", "records": records}


def slim_companyfacts(companyfacts: dict[str, Any]) -> dict[str, Any]:
    """Keep only SEC concepts the normalizer needs for a reproducible fixture."""
    required: dict[str, set[str]] = {}
    for definition in load_concept_config()["fields"].values():
        for reference in definition["concepts"]:
            namespace, separator, concept = reference.partition(":")
            if not separator:
                namespace, concept = "us-gaap", namespace
            required.setdefault(namespace, set()).add(concept)
    return {
        "cik": companyfacts["cik"],
        "entityName": companyfacts["entityName"],
        "facts": {
            namespace: {
                concept: companyfacts["facts"][namespace][concept]
                for concept in concepts
                if concept in companyfacts.get("facts", {}).get(namespace, {})
            }
            for namespace, concepts in required.items()
        },
    }


def slim_submissions(submissions: dict[str, Any]) -> dict[str, Any]:
    """Keep filing identity fields needed to attribute the valuation period."""
    recent = submissions["filings"]["recent"]
    keep = (
        "accessionNumber",
        "filingDate",
        "reportDate",
        "acceptanceDateTime",
        "act",
        "form",
        "fileNumber",
        "filmNumber",
        "items",
        "size",
        "isXBRL",
        "isInlineXBRL",
        "primaryDocument",
        "primaryDocDescription",
    )
    return {
        key: submissions.get(key)
        for key in (
            "cik",
            "entityType",
            "sic",
            "sicDescription",
            "name",
            "tickers",
            "exchanges",
            "category",
            "fiscalYearEnd",
        )
    } | {"filings": {"recent": {key: recent.get(key, []) for key in keep}, "files": []}}


def _source_financial_statement(
    result: dict[str, Any], submissions: dict[str, Any]
) -> dict[str, Any]:
    revenue_source = result["financials"]["ttm"]["sources"]["revenue"]
    source = revenue_source.get("current_ytd")
    if source is None:
        source = revenue_source.get("sources", [{}])[-1]
    recent = submissions.get("filings", {}).get("recent", {})
    accessions = recent.get("accessionNumber", [])
    accession = source.get("accession")
    source_index = accessions.index(accession) if accession in accessions else None
    primary_documents = recent.get("primaryDocument", [])
    primary_document = (
        primary_documents[source_index]
        if source_index is not None and source_index < len(primary_documents)
        else None
    )
    filing_url = None
    if accession and primary_document:
        filing_url = (
            "https://www.sec.gov/Archives/edgar/data/"
            f"{int(result['issuer']['cik'])}/{accession.replace('-', '')}/{primary_document}"
        )
    return {
        "form": source.get("form"),
        "period_end": result["financial_period_end"],
        "filed_date": source.get("filed"),
        "accession": accession,
        "url": filing_url,
        "note": "Latest financial statement used; this does not claim to be the issuer's latest disclosure of every type.",
    }


def _public_model(model: dict[str, Any]) -> dict[str, Any]:
    return {
        "model": model["model"],
        "output_type": model["output_type"],
        "currency": model.get("currency", "USD"),
        "intrinsic_value_per_share": model.get("intrinsic_value_per_share"),
        "publication_state": model["publication_state"],
        "errors": model.get("errors", []),
        "warnings": model.get("warnings", []),
    }


PUBLICATION_STATES = {"pass", "review_required", "withheld"}
_STATE_STRICTNESS = {"pass": 0, "review_required": 1, "withheld": 2}
PUBLIC_SCHEMA_VERSION = "US-PUBLIC-VALUATION-1.1"
_LEGACY_SCHEMA_VERSIONS = {
    "US-PUBLIC-VALUATION-1.0",
    "US-VALUATION-RESULT-1.0",
}
_PUBLIC_MODEL_NAMES = {"fcff_dcf", "residual_income", "ddm", "ffo"}
_BRIDGE_SPREAD_LIMIT = 0.01
_SPREAD_BOUNDARY_RELATIVE_TOLERANCE = 1e-14
_INVALID_STATE_ERROR = (
    "Public artifact has an unsupported publication state and was withheld."
)
_INVALID_BRIDGE_ERROR = (
    "Public bridge quality is invalid or missing; valuation was withheld."
)
_INVALID_AUTOMATED_REVIEW_ERROR = (
    "Public automated review is invalid; valuation was withheld."
)
_INCONSISTENT_MODEL_POLICY_ERROR = (
    "Public model policy is inconsistent with FCFF valuation surfaces and was withheld."
)
_INCONSISTENT_MODEL_IDENTITY_ERROR = (
    "Public model key and discriminator are inconsistent; valuation was withheld."
)
_INVALID_PRIMARY_MODEL_ERROR = (
    "Public primary model policy is invalid or missing; valuation was withheld."
)

_BRIDGE_FIELDS = (
    "cash",
    "commercial_paper",
    "current_debt",
    "finance_lease_current",
    "finance_lease_noncurrent",
    "finance_lease_total",
    "marketable_securities_current",
    "marketable_securities_noncurrent",
    "noncontrolling_interests",
    "noncurrent_debt",
    "preferred_equity",
    "total_interest_bearing_debt",
)
_PUBLIC_BRIDGE_REASONS = (
    "BASE_ENTERPRISE_VALUE_UNAVAILABLE",
    "BRIDGE_EVIDENCE_CONFLICT",
    "BRIDGE_EVIDENCE_NOT_CURRENT",
    "BRIDGE_EVIDENCE_NOT_PRODUCTION",
    "BRIDGE_EVIDENCE_SOURCE_INCOMPLETE",
    "BRIDGE_EVIDENCE_UNUSABLE",
    "BRIDGE_FIELD_IDENTITY_MISMATCH",
    "BRIDGE_FIELD_MISSING_OR_INVALID",
    "BRIDGE_POLICY_WITHHELD",
    "BRIDGE_QUALITY_INVALID_OR_MISSING",
    "CURRENT_NOTE_SUPPLIES_FINITE_RANGE",
    "FINANCE_LEASE_AGGREGATE_CONFLICT",
    "FINANCE_LEASE_AGGREGATE_INCOMPLETE_COVERAGE",
    "JOINT_INTRINSIC_VALUE_SPREAD_EXCEEDS_LIMIT",
    "NONFINITE_INTRINSIC_VALUE_RESULT",
    "NONPOSITIVE_INTRINSIC_VALUE_MIDPOINT",
    "STALE_STALE_REPORTED_FACT",
    "TOTAL_DEBT_AGGREGATE_CONFLICT",
    "TOTAL_DEBT_AGGREGATE_INCOMPLETE_COVERAGE",
    "UNRESOLVED_UNSPECIFIED",
)
_PUBLIC_RELIABILITY_REASONS = (
    *_PUBLIC_BRIDGE_REASONS,
    "INTERIM_FFO_ROUTE",
    "LEGACY_ARTIFACT_NOT_REGENERATED",
    "RELIABILITY_PAYLOAD_INVALID",
    "VALUATION_WITHHELD",
)
_RELIABILITY_KEYS = {
    "label",
    "accounting_label",
    "scenario_label",
    "model_cap",
    "source_cap",
    "accounting_impact_ratio",
    "scenario_movement_ratio",
    "reasons",
}
_RELIABILITY_LABELS = {"High", "Medium", "Low"}
_BRIDGE_QUALITY_KEYS = {
    "decision",
    "complete",
    "usable",
    "bounded_fields",
    "blocking_fields",
    "reason_codes",
    "intrinsic_value_range",
}
_BRIDGE_RANGE_KEYS = {
    "low",
    "midpoint",
    "high",
    "spread_ratio",
    "spread_limit",
}
_PRIVATE_ASSESSMENT_KEYS = {
    "decision",
    "usable",
    "intrinsic_value_range",
    "spread_ratio",
    "spread_limit",
    "blocking_fields",
    "bounded_fields",
    "reason_codes",
    "warning",
    "policy_version",
}
_PRIVATE_RANGE_KEYS = {"low", "midpoint", "high"}
_AUTOMATED_REVIEW_KEYS = {
    "review_version",
    "decision",
    "publication_state",
    "evidence_status",
    "blocking_reasons",
    "repair_actions",
    "warnings",
}
_PUBLIC_AUTOMATED_REVIEW_FIELDS = (
    "review_version",
    "decision",
    "publication_state",
    "evidence_status",
    "blocking_reasons",
    "repair_actions",
    "warnings",
)
_AUTOMATED_DECISION_STATES = {
    "approved": "pass",
    "approved_with_caveat": "review_required",
    "blocked": "withheld",
}
_PUBLIC_TOP_LEVEL_FIELDS = (
    "schema_version",
    "valuation_date",
    "market",
    "currency",
    "ticker",
    "issuer",
    "source_financial_statement",
    "model_policy",
    "public_assumptions",
    "models",
    "scenarios",
    "scenario_range",
    "sensitivities",
    "forecast_quality",
    "review",
    "automated_review",
    "bridge_quality",
    "reliability",
    "methodology",
    "data_boundary",
)
_PUBLIC_ISSUER_FIELDS = (
    "cik",
    "ticker",
    "issuer_name",
    "filing_regime",
    "accounting_standard",
    "sec_sic_code",
    "sec_sic_label",
    "finsight_sector",
    "primary_archetype",
    "secondary_archetypes",
    "classification_confidence",
    "mapping_version",
    "classification_reason",
    "override_applied",
    "source_accessions",
)
_PUBLIC_SOURCE_FIELDS = (
    "form",
    "period_end",
    "filed_date",
    "accession",
    "url",
    "note",
)
_PUBLIC_POLICY_FIELDS = (
    "primary",
    "supporting",
    "blend_models",
    "reason",
    "fallback_from",
)
_PUBLIC_MODEL_FIELDS = (
    "model",
    "output_type",
    "currency",
    "intrinsic_value_per_share",
    "publication_state",
    "errors",
    "warnings",
)
_PUBLIC_SCENARIO_RANGE_FIELDS = ("low", "base", "high", "label")
_PUBLIC_REVIEW_FIELDS = (
    "publication_state",
    "confidence_grade",
    "errors",
    "warnings",
    "price_dependent_inputs_used",
    "prohibited_output_check",
)
_PUBLIC_PROHIBITED_OUTPUT_FIELDS = (
    "current_price",
    "upside_downside",
    "buy_hold_sell",
    "trading_multiples",
)
_PUBLIC_ASSUMPTION_FIELDS = (
    "forecast_policy_version",
    "forecast_years",
    "forecast_mode",
    "initial_revenue_growth",
    "target_operating_margin",
    "segment_assumptions",
    "sales_to_capital",
    "terminal_growth",
    "discount_policy_version",
    "discount_calibration_type",
    "policy_wacc",
    "risk_free_rate",
    "risk_free_effective_date",
    "risk_free_source_url",
    "equity_risk_premium",
    "cost_of_equity",
    "policy_beta",
    "book_value_per_share",
    "current_roe",
    "current_payout_ratio",
    "terminal_roe",
    "last_dividend",
    "high_dividend_growth",
    "high_growth_years",
    "ffo_per_share",
    "pffo_multiple",
)
_PUBLIC_SEGMENT_ASSUMPTION_FIELDS = (
    "label",
    "initial_revenue_growth",
    "target_operating_margin",
    "target_gross_margin",
)
_PUBLIC_SENSITIVITY_FIELDS = (
    "field",
    "delta",
    "intrinsic_value_per_share",
    "publication_state",
    "terminal_marginal_roic",
    "initial_marginal_roic",
)
_PUBLIC_FORECAST_QUALITY_FIELDS = (
    "policy_version",
    "status",
    "errors",
    "warnings",
    "checks",
)
_PUBLIC_FORECAST_CHECK_FIELDS = (
    "status",
    "value",
    "limit",
    "target",
    "revenue_cagr",
    "fcff_cagr",
    "review_threshold",
    "available_periods",
    "normalized_period_end",
)
_PUBLIC_FORECAST_CHECK_VALUE_FIELDS = (
    "segment_revenue_to_consolidated",
    "segment_operating_income_to_consolidated",
    "gross_profit_less_opex_to_operating_income",
)
_PUBLIC_METHODOLOGY_FIELDS = (
    "forecast_policy",
    "sector_framework",
    "source_policy",
)
_PUBLIC_DATA_BOUNDARY_FIELDS = (
    "raw_financial_statement_values_included",
    "stock_prices_used",
    "public_payload_contains",
)


def _allowlisted_mapping(
    value: object, fields: tuple[str, ...]
) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {}
    return {key: deepcopy(value[key]) for key in fields if key in value}


def _canonical_model(value: object) -> object:
    if not isinstance(value, dict):
        return deepcopy(value)
    return _allowlisted_mapping(value, _PUBLIC_MODEL_FIELDS)


def _canonical_models(value: object) -> object:
    if not isinstance(value, dict):
        return deepcopy(value)
    return {name: _canonical_model(model) for name, model in value.items()}


def _canonical_scenarios(value: object) -> object:
    if not isinstance(value, dict):
        return deepcopy(value)
    return {
        name: (
            {model_name: _canonical_model(model) for model_name, model in scenario.items()}
            if isinstance(scenario, dict)
            else deepcopy(scenario)
        )
        for name, scenario in value.items()
    }


def _canonical_public_assumptions(value: object) -> dict[str, Any]:
    public = _allowlisted_mapping(value, _PUBLIC_ASSUMPTION_FIELDS)
    segments = public.get("segment_assumptions")
    if isinstance(segments, dict):
        public["segment_assumptions"] = {
            name: _allowlisted_mapping(
                segment, _PUBLIC_SEGMENT_ASSUMPTION_FIELDS
            )
            for name, segment in segments.items()
            if isinstance(segment, dict)
        }
    elif "segment_assumptions" in public:
        public["segment_assumptions"] = {}
    return public


def _canonical_forecast_quality(value: object) -> dict[str, Any]:
    quality = _allowlisted_mapping(value, _PUBLIC_FORECAST_QUALITY_FIELDS)
    checks = quality.get("checks")
    if isinstance(checks, dict):
        canonical_checks: dict[str, Any] = {}
        for name, check in checks.items():
            if not isinstance(check, dict):
                continue
            canonical = _allowlisted_mapping(
                check, _PUBLIC_FORECAST_CHECK_FIELDS
            )
            if isinstance(canonical.get("value"), dict):
                canonical["value"] = _allowlisted_mapping(
                    canonical["value"], _PUBLIC_FORECAST_CHECK_VALUE_FIELDS
                )
            canonical_checks[name] = canonical
        quality["checks"] = canonical_checks
    elif "checks" in quality:
        quality["checks"] = {}
    return quality


def _canonical_review(value: object) -> dict[str, Any]:
    review = _allowlisted_mapping(value, _PUBLIC_REVIEW_FIELDS)
    if "prohibited_output_check" in review:
        review["prohibited_output_check"] = _allowlisted_mapping(
            review["prohibited_output_check"],
            _PUBLIC_PROHIBITED_OUTPUT_FIELDS,
        )
    return review


def _canonical_public_artifact(value: object) -> dict[str, Any]:
    """Copy only the explicit public artifact contract and its nested DTOs."""
    public = _allowlisted_mapping(value, _PUBLIC_TOP_LEVEL_FIELDS)
    public["issuer"] = _allowlisted_mapping(
        public.get("issuer"), _PUBLIC_ISSUER_FIELDS
    )
    public["source_financial_statement"] = _allowlisted_mapping(
        public.get("source_financial_statement"), _PUBLIC_SOURCE_FIELDS
    )
    public["model_policy"] = _allowlisted_mapping(
        public.get("model_policy"), _PUBLIC_POLICY_FIELDS
    )
    public["public_assumptions"] = _canonical_public_assumptions(
        public.get("public_assumptions")
    )
    public["models"] = _canonical_models(public.get("models"))
    public["scenarios"] = _canonical_scenarios(public.get("scenarios"))
    if "scenario_range" in public:
        public["scenario_range"] = _allowlisted_mapping(
            public["scenario_range"], _PUBLIC_SCENARIO_RANGE_FIELDS
        )
    if "sensitivities" in public and isinstance(public["sensitivities"], list):
        public["sensitivities"] = [
            _allowlisted_mapping(row, _PUBLIC_SENSITIVITY_FIELDS)
            if isinstance(row, dict)
            else deepcopy(row)
            for row in public["sensitivities"]
        ]
    if "forecast_quality" in public:
        public["forecast_quality"] = _canonical_forecast_quality(
            public["forecast_quality"]
        )
    public["review"] = _canonical_review(public.get("review"))
    if "automated_review" in public:
        public["automated_review"] = _allowlisted_mapping(
            public["automated_review"], _PUBLIC_AUTOMATED_REVIEW_FIELDS
        )
    if "methodology" in public:
        public["methodology"] = _allowlisted_mapping(
            public["methodology"], _PUBLIC_METHODOLOGY_FIELDS
        )
    if "data_boundary" in public:
        public["data_boundary"] = _allowlisted_mapping(
            public["data_boundary"], _PUBLIC_DATA_BOUNDARY_FIELDS
        )
    return public


def _legacy_fcff_fallback_reason(artifact: dict[str, Any]) -> str | None:
    """Return a repair reason for an old FCFF-to-equity fallback artifact."""
    policy = artifact.get("model_policy")
    if not isinstance(policy, dict):
        return None
    primary = policy.get("primary")
    if primary not in {"residual_income", "ddm", "ffo"}:
        return None
    fallback_from = policy.get("fallback_from")
    policy_reason = str(policy.get("reason", "")).lower()
    if fallback_from == "fcff_dcf" or (
        "fcff" in policy_reason
        and "bridge" in policy_reason
        and "fallback" in policy_reason
    ):
        return (
            "Legacy FCFF fallback artifact is not publishable; repair the current "
            "enterprise-to-equity bridge or regenerate through the governed model route."
        )
    return None


def _stricter_state(*states: str) -> str:
    return max(states, key=lambda state: _STATE_STRICTNESS[state])


def _deduplicated_strings(value: object) -> list[str] | None:
    if not isinstance(value, list) or any(
        not isinstance(item, str) for item in value
    ):
        return None
    return list(dict.fromkeys(value))


def _append_unique(messages: list[str], message: str) -> None:
    if message not in messages:
        messages.append(message)


def _canonical_identifiers(
    value: object,
    *,
    allowed: tuple[str, ...],
) -> list[str]:
    if not isinstance(value, list) or any(
        not isinstance(item, str) for item in value
    ):
        raise ValueError("identifier list is malformed")
    if len(value) != len(set(value)) or any(item not in allowed for item in value):
        raise ValueError("identifier list contains duplicates or unknown values")
    present = set(value)
    return [item for item in allowed if item in present]


def _json_number(value: object, *, nullable: bool = False) -> float | None:
    if value is None and nullable:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError("value must be a JSON-safe finite number")
    normalized = float(value)
    if not isfinite(normalized):
        raise ValueError("value must be a JSON-safe finite number")
    return normalized


def _validated_public_reliability(value: object) -> dict[str, Any] | None:
    """Validate and copy only the allowlisted public reliability DTO."""
    try:
        if not isinstance(value, dict) or set(value) != _RELIABILITY_KEYS:
            raise ValueError("reliability has an unsupported shape")
        labels = {
            key: value[key]
            for key in (
                "label",
                "accounting_label",
                "scenario_label",
                "model_cap",
                "source_cap",
            )
        }
        if any(label not in _RELIABILITY_LABELS for label in labels.values()):
            raise ValueError("reliability label is invalid")

        accounting_impact = _json_number(value["accounting_impact_ratio"])
        scenario_movement = _json_number(value["scenario_movement_ratio"])
        assert accounting_impact is not None and scenario_movement is not None
        if accounting_impact < 0 or scenario_movement < 0:
            raise ValueError("reliability ratios must be nonnegative")

        reasons = _canonical_identifiers(
            value["reasons"], allowed=_PUBLIC_RELIABILITY_REASONS
        )
        if labels["accounting_label"] != accounting_label(accounting_impact):
            raise ValueError("accounting label disagrees with its ratio")
        if labels["scenario_label"] != scenario_label(scenario_movement):
            raise ValueError("scenario label disagrees with its ratio")
        expected_label = lowest_label(
            labels["accounting_label"],
            labels["scenario_label"],
            labels["model_cap"],
            labels["source_cap"],
        )
        if labels["label"] != expected_label:
            raise ValueError("overall reliability label is inconsistent")
        return {
            **labels,
            "accounting_impact_ratio": accounting_impact,
            "scenario_movement_ratio": scenario_movement,
            "reasons": reasons,
        }
    except (
        AssertionError,
        KeyError,
        TypeError,
        ValueError,
        OverflowError,
    ):
        return None


def _ratios_agree(left: float, right: float) -> bool:
    return isclose(left, right, rel_tol=1e-14, abs_tol=0.0)


def _reliability_matches_artifact(
    reliability: dict[str, Any],
    *,
    primary: object,
    scenario_range: dict[str, float] | None,
    bridge_quality: dict[str, Any] | None,
) -> bool:
    if scenario_range is None:
        return False
    try:
        expected_scenario = _json_number(
            relative_movement(
                low=scenario_range["low"],
                base=scenario_range["base"],
                high=scenario_range["high"],
            )
        )
        assert expected_scenario is not None
        if not _ratios_agree(
            reliability["scenario_movement_ratio"], expected_scenario
        ):
            return False

        if primary == "fcff_dcf":
            if not isinstance(bridge_quality, dict):
                return False
            value_range = bridge_quality["intrinsic_value_range"]
            if bridge_quality["decision"] == "complete":
                expected_accounting = 0.0
            elif bridge_quality["decision"] == "bounded_review":
                expected_accounting = _json_number(
                    relative_movement(
                        low=value_range["low"],
                        base=value_range["midpoint"],
                        high=value_range["high"],
                    )
                )
                assert expected_accounting is not None
            else:
                return False
            expected_cap = accounting_label(expected_accounting)
            return (
                _ratios_agree(
                    reliability["accounting_impact_ratio"],
                    expected_accounting,
                )
                and reliability["accounting_label"] == expected_cap
                and reliability["source_cap"] == expected_cap
            )

        return (
            primary in {"residual_income", "ddm", "ffo"}
            and reliability["accounting_impact_ratio"] == 0.0
            and reliability["accounting_label"] == "High"
        )
    except (
        AssertionError,
        KeyError,
        TypeError,
        ValueError,
        OverflowError,
        ZeroDivisionError,
    ):
        return False


def _fallback_reliability(
    scenario_range: object,
    *,
    reason: str,
) -> dict[str, Any] | None:
    try:
        if not isinstance(scenario_range, dict):
            raise ValueError("scenario range is malformed")
        movement = _json_number(
            relative_movement(
                low=scenario_range["low"],
                base=scenario_range["base"],
                high=scenario_range["high"],
            )
        )
        assert movement is not None
        return {
            "label": "Low",
            "accounting_label": "Low",
            "scenario_label": "Low",
            "model_cap": "Low",
            "source_cap": "Low",
            "accounting_impact_ratio": 0.0,
            "scenario_movement_ratio": movement,
            "reasons": [reason],
        }
    except (KeyError, TypeError, ValueError, OverflowError):
        return None


def _withheld_reliability() -> dict[str, Any]:
    return {
        "label": "Low",
        "accounting_label": "Low",
        "scenario_label": "Low",
        "model_cap": "Low",
        "source_cap": "Low",
        "accounting_impact_ratio": None,
        "scenario_movement_ratio": None,
        "reasons": ["VALUATION_WITHHELD"],
    }


def _spread_within_limit(spread_ratio: float) -> bool:
    return spread_ratio <= _BRIDGE_SPREAD_LIMIT or isclose(
        spread_ratio,
        _BRIDGE_SPREAD_LIMIT,
        rel_tol=_SPREAD_BOUNDARY_RELATIVE_TOLERANCE,
        abs_tol=0.0,
    )


def _invalid_bridge_quality() -> dict[str, Any]:
    return {
        "decision": "withheld",
        "complete": False,
        "usable": False,
        "bounded_fields": [],
        "blocking_fields": [],
        "reason_codes": ["BRIDGE_QUALITY_INVALID_OR_MISSING"],
        "intrinsic_value_range": {
            "low": None,
            "midpoint": None,
            "high": None,
            "spread_ratio": None,
            "spread_limit": _BRIDGE_SPREAD_LIMIT,
        },
    }


def _validated_public_bridge_quality(
    value: object,
    *,
    allow_bounded_over_limit: bool = False,
) -> dict[str, Any] | None:
    """Validate and canonicalize only the allowlisted public bridge DTO."""
    try:
        if not isinstance(value, dict) or set(value) != _BRIDGE_QUALITY_KEYS:
            raise ValueError("bridge quality has an unsupported shape")
        decision = value["decision"]
        complete = value["complete"]
        usable = value["usable"]
        if decision not in {"complete", "bounded_review", "withheld"}:
            raise ValueError("unsupported bridge decision")
        if not isinstance(complete, bool) or not isinstance(usable, bool):
            raise ValueError("bridge booleans are malformed")

        bounded_fields = _canonical_identifiers(
            value["bounded_fields"], allowed=_BRIDGE_FIELDS
        )
        blocking_fields = _canonical_identifiers(
            value["blocking_fields"], allowed=_BRIDGE_FIELDS
        )
        reason_codes = _canonical_identifiers(
            value["reason_codes"], allowed=_PUBLIC_BRIDGE_REASONS
        )

        raw_range = value["intrinsic_value_range"]
        if not isinstance(raw_range, dict) or set(raw_range) != _BRIDGE_RANGE_KEYS:
            raise ValueError("bridge range has an unsupported shape")
        spread_limit = _json_number(raw_range["spread_limit"])
        if spread_limit != _BRIDGE_SPREAD_LIMIT:
            raise ValueError("bridge spread limit does not match policy")
        spread_ratio = _json_number(
            raw_range["spread_ratio"], nullable=True
        )
        if spread_ratio is not None and spread_ratio < 0:
            raise ValueError("bridge spread ratio cannot be negative")

        absolute_values = (
            raw_range["low"],
            raw_range["midpoint"],
            raw_range["high"],
        )
        all_null = all(item is None for item in absolute_values)
        if not all_null and any(item is None for item in absolute_values):
            raise ValueError("bridge range cannot be partially null")
        if all_null:
            low = midpoint = high = None
            expected_spread = None
        else:
            low = _json_number(absolute_values[0])
            midpoint = _json_number(absolute_values[1])
            high = _json_number(absolute_values[2])
            assert low is not None and midpoint is not None and high is not None
            if not low <= midpoint <= high or not isclose(
                midpoint,
                (low + high) / 2,
                rel_tol=1e-14,
                abs_tol=0.0,
            ):
                raise ValueError("bridge range arithmetic is invalid")
            expected_spread = (
                0.0
                if low == high
                else (high - low) / midpoint
                if midpoint > 0
                else None
            )

        if decision == "complete":
            if (
                complete is not True
                or usable is not True
                or bounded_fields
                or blocking_fields
                or spread_ratio != 0.0
                or (
                    not all_null
                    and (low != midpoint or midpoint != high)
                )
            ):
                raise ValueError("complete bridge quality is inconsistent")
        elif decision == "bounded_review":
            if (
                complete is not False
                or usable is not True
                or not bounded_fields
                or blocking_fields
                or spread_ratio is None
                or (
                    not allow_bounded_over_limit
                    and not _spread_within_limit(spread_ratio)
                )
                or all_null
                or midpoint is None
                or midpoint <= 0
                or expected_spread is None
                or not isclose(
                    spread_ratio,
                    expected_spread,
                    rel_tol=1e-14,
                    abs_tol=0.0,
                )
            ):
                raise ValueError("bounded bridge quality is inconsistent")
        else:
            invalid_boundary = reason_codes == [
                "BRIDGE_QUALITY_INVALID_OR_MISSING"
            ]
            if complete is not False or usable is not False:
                raise ValueError("withheld bridge quality is inconsistent")
            if invalid_boundary:
                if (
                    bounded_fields
                    or blocking_fields
                    or spread_ratio is not None
                    or not all_null
                ):
                    raise ValueError("invalid bridge sentinel is malformed")
            elif not bounded_fields and not blocking_fields:
                raise ValueError("withheld bridge quality lacks affected fields")
            elif not all_null:
                if midpoint is None or midpoint <= 0:
                    if (
                        spread_ratio is not None
                        or "NONPOSITIVE_INTRINSIC_VALUE_MIDPOINT"
                        not in reason_codes
                    ):
                        raise ValueError("nonpositive bridge range is malformed")
                elif (
                    spread_ratio is None
                    or expected_spread is None
                    or not isclose(
                        spread_ratio,
                        expected_spread,
                        rel_tol=1e-14,
                        abs_tol=0.0,
                    )
                    or _spread_within_limit(spread_ratio)
                    or "JOINT_INTRINSIC_VALUE_SPREAD_EXCEEDS_LIMIT"
                    not in reason_codes
                ):
                    raise ValueError("withheld bridge spread is malformed")
            elif spread_ratio is not None and (
                _spread_within_limit(spread_ratio)
                or "JOINT_INTRINSIC_VALUE_SPREAD_EXCEEDS_LIMIT"
                not in reason_codes
            ):
                raise ValueError("scrubbed bridge spread is malformed")

        return {
            "decision": decision,
            "complete": complete,
            "usable": usable,
            "bounded_fields": bounded_fields,
            "blocking_fields": blocking_fields,
            "reason_codes": reason_codes,
            "intrinsic_value_range": {
                "low": low,
                "midpoint": midpoint,
                "high": high,
                "spread_ratio": spread_ratio,
                "spread_limit": _BRIDGE_SPREAD_LIMIT,
            },
        }
    except (KeyError, TypeError, ValueError, OverflowError, ZeroDivisionError):
        return None


def _validated_scrubbed_bounded_bridge_quality(
    value: object,
    *,
    allow_bounded_over_limit: bool = False,
) -> dict[str, Any] | None:
    """Validate the null-valued form produced only after public withholding."""
    try:
        if not isinstance(value, dict) or value.get("decision") != "bounded_review":
            raise ValueError("not a scrubbed bounded bridge")
        raw_range = value["intrinsic_value_range"]
        if not isinstance(raw_range, dict) or set(raw_range) != _BRIDGE_RANGE_KEYS:
            raise ValueError("bridge range has an unsupported shape")
        if any(raw_range[key] is not None for key in ("low", "midpoint", "high")):
            raise ValueError("scrubbed bridge absolutes must be null")
        spread_ratio = _json_number(raw_range["spread_ratio"])
        assert spread_ratio is not None

        probe = deepcopy(value)
        half_width = spread_ratio * 50.0
        probe["intrinsic_value_range"].update(
            {
                "low": 100.0 - half_width,
                "midpoint": 100.0,
                "high": 100.0 + half_width,
            }
        )
        validated = _validated_public_bridge_quality(
            probe,
            allow_bounded_over_limit=allow_bounded_over_limit,
        )
        if validated is None:
            raise ValueError("scrubbed bounded bridge metadata is invalid")
        validated["intrinsic_value_range"].update(
            {"low": None, "midpoint": None, "high": None}
        )
        return validated
    except (
        AssertionError,
        KeyError,
        TypeError,
        ValueError,
        OverflowError,
    ):
        return None


def _withheld_value_sink(value: object) -> bool:
    return (
        isinstance(value, dict)
        and value.get("publication_state") == "withheld"
        and value.get("intrinsic_value_per_share") is None
    )


def _artifact_is_fully_scrubbed(artifact: object) -> bool:
    """Recognize only an artifact previously scrubbed at every value sink."""
    if not isinstance(artifact, dict):
        return False
    review = artifact.get("review")
    models = artifact.get("models")
    scenarios = artifact.get("scenarios")
    scenario_range = artifact.get("scenario_range")
    sensitivities = artifact.get("sensitivities", [])
    if (
        not isinstance(review, dict)
        or review.get("publication_state") != "withheld"
        or not isinstance(models, dict)
        or not _withheld_value_sink(models.get("fcff_dcf"))
        or not all(_withheld_value_sink(model) for model in models.values())
        or not isinstance(scenarios, dict)
        or not all(
            isinstance(scenario, dict)
            and all(_withheld_value_sink(model) for model in scenario.values())
            for scenario in scenarios.values()
        )
        or not isinstance(sensitivities, list)
        or not all(_withheld_value_sink(row) for row in sensitivities)
        or not isinstance(scenario_range, dict)
        or any(scenario_range.get(key) is not None for key in ("low", "base", "high"))
    ):
        return False
    return True


def _artifact_has_fcff_surface(artifact: dict[str, Any]) -> bool:
    models = artifact.get("models")
    scenarios = artifact.get("scenarios")
    return (
        "bridge_quality" in artifact
        or (
            isinstance(models, dict)
            and any(
                name == "fcff_dcf"
                or (isinstance(model, dict) and model.get("model") == "fcff_dcf")
                for name, model in models.items()
            )
        )
        or (
            isinstance(scenarios, dict)
            and any(
                isinstance(scenario, dict)
                and any(
                    name == "fcff_dcf"
                    or (
                        isinstance(model, dict)
                        and model.get("model") == "fcff_dcf"
                    )
                    for name, model in scenario.items()
                )
                for scenario in scenarios.values()
            )
        )
    )


def _artifact_model_identities_agree(artifact: dict[str, Any]) -> bool:
    def collection_agrees(value: object) -> bool:
        return not isinstance(value, dict) or all(
            not isinstance(model, dict)
            or "model" not in model
            or model["model"] == name
            for name, model in value.items()
        )

    models = artifact.get("models")
    scenarios = artifact.get("scenarios")
    return collection_agrees(models) and (
        not isinstance(scenarios, dict)
        or all(collection_agrees(scenario) for scenario in scenarios.values())
    )


def _bridge_absolutes_match_canonical_fcff(
    bridge_quality: dict[str, Any],
    models: dict[str, Any],
) -> bool:
    value_range = bridge_quality["intrinsic_value_range"]
    if all(value_range[key] is None for key in ("low", "midpoint", "high")):
        return True
    fcff = models.get("fcff_dcf")
    if not isinstance(fcff, dict):
        return False
    try:
        canonical = _json_number(fcff.get("intrinsic_value_per_share"))
        midpoint = _json_number(value_range["midpoint"])
    except (TypeError, ValueError, OverflowError):
        return False
    assert canonical is not None and midpoint is not None
    return isclose(canonical, midpoint, rel_tol=1e-14, abs_tol=0.0)


def _public_bridge_quality(result: dict[str, Any]) -> dict[str, Any]:
    """Build a public DTO from the final private assessment and aliases only."""
    try:
        balance = result["financials"]["balance_sheet"]
        if not isinstance(balance, dict):
            raise ValueError("balance sheet must be a mapping")
        raw = balance["bridge_uncertainty"]
        if not isinstance(raw, dict) or set(raw) != _PRIVATE_ASSESSMENT_KEYS:
            raise ValueError("private bridge assessment has an unsupported shape")
        if raw["policy_version"] != POLICY_VERSION:
            raise ValueError("private bridge policy version mismatch")
        if _json_number(raw["spread_limit"]) != _BRIDGE_SPREAD_LIMIT:
            raise ValueError("private bridge spread limit mismatch")
        _json_number(raw["spread_ratio"], nullable=True)

        raw_range = raw["intrinsic_value_range"]
        if raw_range is not None:
            if not isinstance(raw_range, dict) or set(raw_range) != _PRIVATE_RANGE_KEYS:
                raise ValueError("private bridge range has an unsupported shape")
            for key in _PRIVATE_RANGE_KEYS:
                _json_number(raw_range[key])

        raw_blocking = _canonical_identifiers(
            raw["blocking_fields"], allowed=_BRIDGE_FIELDS
        )
        raw_bounded = _canonical_identifiers(
            raw["bounded_fields"], allowed=_BRIDGE_FIELDS
        )
        raw_reasons = _canonical_identifiers(
            raw["reason_codes"], allowed=_PUBLIC_BRIDGE_REASONS
        )
        assessment = BridgeAssessment.from_dict(raw)

        alias_blocking = _canonical_identifiers(
            balance["bridge_blocking_fields"], allowed=_BRIDGE_FIELDS
        )
        alias_bounded = _canonical_identifiers(
            balance["bridge_bounded_fields"], allowed=_BRIDGE_FIELDS
        )
        alias_missing = _canonical_identifiers(
            balance["bridge_missing_fields"], allowed=_BRIDGE_FIELDS
        )
        for key in ("bridge_complete", "bridge_can_value", "bridge_usable"):
            if not isinstance(balance[key], bool):
                raise ValueError(f"{key} must be a boolean")
        if (
            balance["bridge_decision"] != assessment.decision
            or balance["bridge_usable"] != assessment.usable
            or balance["bridge_complete"] != (assessment.decision == "complete")
            or balance["bridge_can_value"] != (not raw_blocking)
            or alias_blocking != raw_blocking
            or alias_bounded != raw_bounded
            or alias_missing
            != [
                field
                for field in _BRIDGE_FIELDS
                if field in set(raw_blocking) | set(raw_bounded)
            ]
            or list(assessment.blocking_fields) != sorted(raw_blocking)
            or list(assessment.bounded_fields) != sorted(raw_bounded)
            or list(assessment.reason_codes) != sorted(raw_reasons)
        ):
            raise ValueError("private bridge aliases disagree with assessment")

        reason_codes = list(raw_reasons)
        if (
            assessment.decision == "withheld"
            and assessment.spread_ratio is not None
            and not _spread_within_limit(float(assessment.spread_ratio))
        ):
            reason_codes = _canonical_identifiers(
                list(
                    dict.fromkeys(
                        [
                            *reason_codes,
                            "JOINT_INTRINSIC_VALUE_SPREAD_EXCEEDS_LIMIT",
                        ]
                    )
                ),
                allowed=_PUBLIC_BRIDGE_REASONS,
            )
        value_range = assessment.intrinsic_value_range
        candidate = {
            "decision": assessment.decision,
            "complete": balance["bridge_complete"],
            "usable": assessment.usable,
            "bounded_fields": raw_bounded,
            "blocking_fields": raw_blocking,
            "reason_codes": reason_codes,
            "intrinsic_value_range": {
                "low": value_range.low if value_range is not None else None,
                "midpoint": (
                    value_range.midpoint if value_range is not None else None
                ),
                "high": value_range.high if value_range is not None else None,
                "spread_ratio": assessment.spread_ratio,
                "spread_limit": _BRIDGE_SPREAD_LIMIT,
            },
        }
        validated = _validated_public_bridge_quality(
            candidate,
            allow_bounded_over_limit=True,
        )
        if validated is None:
            raise ValueError("derived bridge quality did not validate")
        return validated
    except (
        AssertionError,
        KeyError,
        TypeError,
        ValueError,
        OverflowError,
        ZeroDivisionError,
    ):
        return _invalid_bridge_quality()


def _valid_automated_review(value: object) -> bool:
    if not isinstance(value, dict) or set(value) != _AUTOMATED_REVIEW_KEYS:
        return False
    decision = value.get("decision")
    if (
        value.get("review_version") != REVIEW_VERSION
        or decision not in _AUTOMATED_DECISION_STATES
        or value.get("publication_state")
        != _AUTOMATED_DECISION_STATES.get(decision)
        or value.get("evidence_status") not in {"missing", "incomplete", "complete"}
    ):
        return False
    for key in ("blocking_reasons", "repair_actions", "warnings"):
        items = value.get(key)
        if (
            not isinstance(items, list)
            or any(not isinstance(item, str) for item in items)
            or len(items) != len(set(items))
        ):
            return False
    if decision == "blocked":
        return bool(value["blocking_reasons"])
    return not value["blocking_reasons"]


def _invalid_automated_review() -> dict[str, Any]:
    return {
        "review_version": REVIEW_VERSION,
        "decision": "blocked",
        "publication_state": "withheld",
        "evidence_status": "missing",
        "blocking_reasons": ["invalid_automated_review_payload"],
        "repair_actions": [],
        "warnings": [],
    }


def sanitize_public_artifact(artifact: dict[str, Any]) -> dict[str, Any]:
    """Validate public state vocabulary and fail closed at every serving boundary."""
    incoming = deepcopy(artifact) if isinstance(artifact, dict) else {}
    was_fully_scrubbed = _artifact_is_fully_scrubbed(incoming)
    public = _canonical_public_artifact(incoming)
    schema_version = public.get("schema_version")
    schema_is_current = schema_version == PUBLIC_SCHEMA_VERSION
    schema_is_legacy = schema_version in _LEGACY_SCHEMA_VERSIONS
    review = public.get("review")
    if not isinstance(review, dict):
        review = {}
        public["review"] = review
    invalid_state = (
        review.get("publication_state") not in PUBLICATION_STATES
        or not (schema_is_current or schema_is_legacy)
    )
    errors = _deduplicated_strings(review.get("errors", []))
    warnings = _deduplicated_strings(review.get("warnings", []))
    if errors is None or warnings is None:
        invalid_state = True
    review["errors"] = errors or []
    review["warnings"] = warnings or []

    if not _artifact_model_identities_agree(public):
        invalid_state = True
        _append_unique(review["errors"], _INCONSISTENT_MODEL_IDENTITY_ERROR)

    policy = public.get("model_policy")
    primary = policy.get("primary") if isinstance(policy, dict) else None
    if primary not in _PUBLIC_MODEL_NAMES:
        invalid_state = True
        _append_unique(review["errors"], _INVALID_PRIMARY_MODEL_ERROR)
    policy_declares_fcff = primary == "fcff_dcf"
    has_fcff_surface = _artifact_has_fcff_surface(public)
    fcff_required = policy_declares_fcff or has_fcff_surface
    if has_fcff_surface and not policy_declares_fcff:
        invalid_state = True
        _append_unique(review["errors"], _INCONSISTENT_MODEL_POLICY_ERROR)

    automated_ceiling = "pass"
    if schema_is_current:
        stored_automated_review = public.get("automated_review")
        recomputed_automated_review = assess_artifact(public)
        public["automated_review"] = (
            stored_automated_review
            if was_fully_scrubbed
            and _valid_automated_review(stored_automated_review)
            else recomputed_automated_review
        )
        automated_ceiling = public["automated_review"]["publication_state"]
    elif "automated_review" in public or fcff_required:
        if _valid_automated_review(public.get("automated_review")):
            automated_ceiling = public["automated_review"]["publication_state"]
        else:
            public["automated_review"] = _invalid_automated_review()
            automated_ceiling = "withheld"
            _append_unique(review["errors"], _INVALID_AUTOMATED_REVIEW_ERROR)

    fallback_reason = _legacy_fcff_fallback_reason(public)
    if fallback_reason:
        _append_unique(review["errors"], fallback_reason)
        invalid_state = True

    models = public.get("models")
    if not isinstance(models, dict):
        models = {}
        public["models"] = models
        invalid_state = True
    for name, model in list(models.items()):
        if not isinstance(model, dict):
            models[name] = {
                "publication_state": "withheld",
                "intrinsic_value_per_share": None,
            }
            invalid_state = True
        elif model.get("publication_state") not in PUBLICATION_STATES:
            model["publication_state"] = "withheld"
            model["intrinsic_value_per_share"] = None
            invalid_state = True
        elif model["publication_state"] == "withheld":
            model["intrinsic_value_per_share"] = None
        else:
            try:
                value = _json_number(model.get("intrinsic_value_per_share"))
                if value is None or value <= 0:
                    raise ValueError("model value must be finite and positive")
            except (TypeError, ValueError, OverflowError):
                model["publication_state"] = "withheld"
                model["intrinsic_value_per_share"] = None
                invalid_state = True

    if not isinstance(primary, str) or not isinstance(models.get(primary), dict):
        invalid_state = True
        _append_unique(review["errors"], _INVALID_PRIMARY_MODEL_ERROR)

    bridge_quality: dict[str, Any] | None = None
    bridge_ceiling = "pass"
    if fcff_required:
        bridge_quality = _validated_public_bridge_quality(
            public.get("bridge_quality"),
            allow_bounded_over_limit=schema_is_current,
        )
        if bridge_quality is None and was_fully_scrubbed:
            bridge_quality = _validated_scrubbed_bounded_bridge_quality(
                public.get("bridge_quality"),
                allow_bounded_over_limit=schema_is_current,
            )
        if (
            bridge_quality is not None
            and bridge_quality["decision"] == "complete"
            and all(
                bridge_quality["intrinsic_value_range"][key] is None
                for key in ("low", "midpoint", "high")
            )
            and not was_fully_scrubbed
        ):
            bridge_quality = None
        if bridge_quality is not None and not _bridge_absolutes_match_canonical_fcff(
            bridge_quality, models
        ):
            bridge_quality = None
        if bridge_quality is None:
            bridge_quality = _invalid_bridge_quality()
            _append_unique(review["errors"], _INVALID_BRIDGE_ERROR)
        public["bridge_quality"] = bridge_quality
        bridge_ceiling = {
            "complete": "pass",
            "bounded_review": "review_required",
            "withheld": "withheld",
        }[bridge_quality["decision"]]

    canonical_primary_ceiling = "withheld"
    canonical_primary = models.get(primary) if isinstance(primary, str) else None
    if isinstance(canonical_primary, dict):
        canonical_primary_ceiling = canonical_primary["publication_state"]

    scenarios = public.get("scenarios")
    if not isinstance(scenarios, dict):
        scenarios = {}
        public["scenarios"] = scenarios
        invalid_state = True
    for scenario_name, scenario in list(scenarios.items()):
        if not isinstance(scenario, dict) or not scenario:
            scenarios[scenario_name] = {}
            invalid_state = True
            continue
        for model_name, model in list(scenario.items()):
            if not isinstance(model, dict):
                scenario[model_name] = {
                    "publication_state": "withheld",
                    "intrinsic_value_per_share": None,
                }
                invalid_state = True
            elif model.get("publication_state") not in PUBLICATION_STATES:
                model["publication_state"] = "withheld"
                model["intrinsic_value_per_share"] = None
                invalid_state = True
            elif model["publication_state"] == "withheld":
                model["intrinsic_value_per_share"] = None
            else:
                try:
                    value = _json_number(model.get("intrinsic_value_per_share"))
                    if value is None or value <= 0:
                        raise ValueError(
                            "scenario value must be finite and positive"
                        )
                except (TypeError, ValueError, OverflowError):
                    model["publication_state"] = "withheld"
                    model["intrinsic_value_per_share"] = None
                    invalid_state = True

    sensitivities = public.get("sensitivities", [])
    if "sensitivities" in public and not isinstance(sensitivities, list):
        sensitivities = []
        public["sensitivities"] = sensitivities
        invalid_state = True
    for index, row in enumerate(list(sensitivities)):
        if not isinstance(row, dict):
            sensitivities[index] = {
                "publication_state": "withheld",
                "intrinsic_value_per_share": None,
            }
            invalid_state = True
        elif row.get("publication_state") not in PUBLICATION_STATES:
            row["publication_state"] = "withheld"
            row["intrinsic_value_per_share"] = None
            invalid_state = True

    raw_scenario_range = public.get("scenario_range")
    reliability_scenario_range: dict[str, float] | None = None
    if not isinstance(raw_scenario_range, dict):
        raw_scenario_range = {}
        invalid_state = True
    raw_range_values = [
        raw_scenario_range.get(key) for key in ("low", "base", "high")
    ]
    if all(value is None for value in raw_range_values):
        if review.get("publication_state") != "withheld" and not was_fully_scrubbed:
            invalid_state = True
    elif any(value is None for value in raw_range_values):
        invalid_state = True
    else:
        try:
            low = _json_number(raw_range_values[0])
            base = _json_number(raw_range_values[1])
            high = _json_number(raw_range_values[2])
            assert low is not None and base is not None and high is not None
            if base <= 0 or not low <= base <= high:
                raise ValueError("scenario range arithmetic is invalid")
            reliability_scenario_range = {
                "low": low,
                "base": base,
                "high": high,
            }
            derived_movement = _json_number(
                relative_movement(low=low, base=base, high=high)
            )
            if derived_movement is None:
                raise ValueError("scenario movement is not finite")
        except (
            AssertionError,
            TypeError,
            ValueError,
            OverflowError,
        ):
            invalid_state = True

    native_state = review.get("publication_state")
    if native_state not in PUBLICATION_STATES:
        native_state = "withheld"
    if invalid_state:
        native_state = "withheld"
        _append_unique(review["errors"], _INVALID_STATE_ERROR)
    effective_review_state = _stricter_state(
        native_state,
        automated_ceiling,
        bridge_ceiling,
        canonical_primary_ceiling,
    )
    review["publication_state"] = effective_review_state

    for model in models.values():
        effective_state = _stricter_state(
            model["publication_state"], bridge_ceiling
        )
        if effective_review_state == "withheld" or effective_state == "withheld":
            model["publication_state"] = "withheld"
            model["intrinsic_value_per_share"] = None
        else:
            model["publication_state"] = effective_state

    scenario_withheld = False
    for scenario in scenarios.values():
        for model in scenario.values():
            effective_state = _stricter_state(
                model["publication_state"], bridge_ceiling
            )
            if effective_review_state == "withheld" or effective_state == "withheld":
                model["publication_state"] = "withheld"
                model["intrinsic_value_per_share"] = None
                scenario_withheld = True
            else:
                model["publication_state"] = effective_state

    for row in sensitivities:
        effective_state = _stricter_state(
            row["publication_state"], bridge_ceiling
        )
        if effective_review_state == "withheld" or effective_state == "withheld":
            row["publication_state"] = "withheld"
            row["intrinsic_value_per_share"] = None
        else:
            row["publication_state"] = effective_state

    scrub_scenario_range = (
        effective_review_state == "withheld" or scenario_withheld
    )
    public["scenario_range"] = {
        "low": None if scrub_scenario_range else raw_scenario_range.get("low"),
        "base": None if scrub_scenario_range else raw_scenario_range.get("base"),
        "high": None if scrub_scenario_range else raw_scenario_range.get("high"),
        "label": raw_scenario_range.get(
            "label", "assumption range, not a statistical confidence interval"
        ),
    }

    if bridge_quality is not None and (
        bridge_quality["decision"] == "withheld"
        or effective_review_state == "withheld"
    ):
        bridge_range = bridge_quality["intrinsic_value_range"]
        bridge_range["low"] = None
        bridge_range["midpoint"] = None
        bridge_range["high"] = None

    if effective_review_state == "withheld":
        public["reliability"] = _withheld_reliability()
    elif schema_is_current:
        reliability = _validated_public_reliability(public.get("reliability"))
        if reliability is not None and not _reliability_matches_artifact(
            reliability,
            primary=primary,
            scenario_range=reliability_scenario_range,
            bridge_quality=bridge_quality,
        ):
            reliability = None
        if reliability is None:
            reliability = _fallback_reliability(
                reliability_scenario_range,
                reason="RELIABILITY_PAYLOAD_INVALID",
            )
        public["reliability"] = reliability or _withheld_reliability()
    else:
        public["reliability"] = _fallback_reliability(
            reliability_scenario_range,
            reason="LEGACY_ARTIFACT_NOT_REGENERATED",
        ) or _withheld_reliability()
    return public


def _public_fcff_result(
    result: dict[str, Any], submissions: dict[str, Any]
) -> dict[str, Any]:
    """Build the FCFF-specific public surface before canonical review."""
    assumptions = result["forecast_assumptions"]
    discount_rate = result["discount_rate"]
    market_assumptions = discount_rate["market_assumptions"]
    segment_forecast = assumptions.get("segment_forecast")
    forecast_mode = (
        segment_forecast["mode"]
        if segment_forecast
        else (
            "unavailable"
            if assumptions.get("forecast_evidence_status")
            == "unavailable_for_normalized_period"
            else "consolidated"
        )
    )
    segment_assumptions = (
        {
            key: {
                "label": segment["label"],
                "initial_revenue_growth": segment["initial_revenue_growth"],
                "target_operating_margin": segment.get("target_operating_margin"),
                "target_gross_margin": segment.get("target_gross_margin"),
            }
            for key, segment in segment_forecast["segments"].items()
        }
        if segment_forecast
        else {}
    )
    public = {
        "schema_version": PUBLIC_SCHEMA_VERSION,
        "valuation_date": result["valuation_date"],
        "market": "US",
        "currency": "USD",
        "ticker": result["issuer"]["ticker"],
        "issuer": {
            key: result["issuer"][key]
            for key in (
                "cik",
                "ticker",
                "issuer_name",
                "finsight_sector",
                "primary_archetype",
                "secondary_archetypes",
                "classification_confidence",
                "mapping_version",
                "classification_reason",
            )
        },
        "source_financial_statement": _source_financial_statement(
            result, submissions
        ),
        "model_policy": result["model_policy"],
        "public_assumptions": {
            "forecast_policy_version": assumptions.get("forecast_policy_version"),
            "forecast_years": assumptions.get("forecast_years"),
            "forecast_mode": forecast_mode,
            "initial_revenue_growth": assumptions.get("initial_revenue_growth"),
            "target_operating_margin": assumptions.get("target_operating_margin"),
            "segment_assumptions": segment_assumptions,
            "sales_to_capital": assumptions.get("sales_to_capital"),
            "terminal_growth": assumptions.get("terminal_growth"),
            "discount_policy_version": market_assumptions["policy_version"],
            "discount_calibration_type": discount_rate["calibration_type"],
            "policy_wacc": discount_rate["wacc"],
            "risk_free_rate": market_assumptions["risk_free_rate"],
            "risk_free_effective_date": market_assumptions[
                "risk_free_effective_date"
            ],
            "risk_free_source_url": market_assumptions["risk_free_source_url"],
            "equity_risk_premium": market_assumptions["equity_risk_premium"],
        },
        "models": {key: _public_model(model) for key, model in result["models"].items()},
        "scenarios": {
            name: {"fcff_dcf": _public_model(scenario["fcff_dcf"])}
            for name, scenario in result["scenarios"].items()
        },
        "scenario_range": result["scenario_range"],
        "forecast_quality": result["forecast_quality"],
        "review": deepcopy(result["review"]),
        "bridge_quality": _public_bridge_quality(result),
        "methodology": result["methodology"],
        "data_boundary": {
            "raw_financial_statement_values_included": False,
            "stock_prices_used": False,
            "public_payload_contains": "derived valuation outputs, governed assumptions, methodology, warnings, and filing attribution",
        },
    }
    return public


def public_result(
    result: dict[str, Any],
    submissions: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Canonically serialize, review, sanitize, and grade a valuation result."""
    policy = result.get("model_policy")
    primary = policy.get("primary") if isinstance(policy, dict) else None
    if primary == "fcff_dcf":
        if not isinstance(submissions, dict):
            raise ValueError("submissions are required for FCFF publication")
        public = _public_fcff_result(result, submissions)
    elif primary in {"residual_income", "ddm", "ffo"}:
        public = public_equity_artifact(result)
    else:
        raise ValueError("unsupported primary model for public serialization")

    public["schema_version"] = PUBLIC_SCHEMA_VERSION
    if "reliability" in result:
        public["reliability"] = deepcopy(result["reliability"])
    else:
        public.pop("reliability", None)

    return sanitize_public_artifact(public)


def frontend_company(
    result: dict[str, Any], public: dict[str, Any], issuer_metadata: dict[str, Any]
) -> dict[str, Any]:
    """Build a frontend record without copying private filing amounts."""
    public = sanitize_public_artifact(public)
    financials = result["financials"]
    annual = [
        {
            "period": f"FY {row['fiscal_year']}",
            "fiscalYear": row["fiscal_year"],
            "periodEnd": row["period_end"],
            "source": {"label": "SEC annual filing period loaded"},
        }
        for row in financials["annual"]
    ]
    quarterly = [
        {
            "period": f"FY {row['fiscal_year']} Q{row['fiscal_quarter']}",
            "fiscalYear": row["fiscal_year"],
            "fiscalQuarter": row["fiscal_quarter"],
            "periodEnd": row["period_end"],
            "source": {"label": "SEC stand-alone quarter reconstructed"},
        }
        for row in financials["quarterly"]["revenue"]
    ]
    short_name = issuer_metadata["short_name"]
    source = public["source_financial_statement"]
    source_label = issuer_metadata.get(
        "source_label",
        f"Latest financial statement used: {short_name} Form {source['form']} for {source['period_end']}, filed {source['filed_date']}",
    )
    valuation_note = issuer_metadata.get(
        "valuation_note",
        f"The displayed range comes from filing-derived {short_name} inputs and governed public-economic assumptions. It excludes market price.",
    )
    return {
        "symbol": issuer_metadata.get("ticker", result["issuer"]["ticker"]),
        "name": result["issuer"]["issuer_name"],
        "shortName": short_name,
        "market": "US",
        "currency": "USD",
        "sector": result["issuer"]["finsight_sector"],
        "subsector": issuer_metadata["subsector"],
        "archetype": result["issuer"]["primary_archetype"],
        "color": issuer_metadata.get("color", "#555555"),
        "dataConfidence": issuer_metadata.get("data_confidence", 0.82),
        "insight": issuer_metadata["insight"],
        "source": {"label": source_label, "href": source["url"]},
        "financials": {
            "period": f"TTM ended {result['financial_period_end']}",
            "fiscalYear": int(result["financial_period_end"][:4]),
            "periodEnd": result["financial_period_end"],
            "source": {"label": "SEC filing periods loaded; raw amounts remain private"},
        },
        "financialHistory": {"annual": annual, "quarterly": quarterly},
        "valuation": {
            "us": public,
            "modelPolicy": {
                "primary": "fcff_dcf",
                "crossChecks": ["epv"],
                "publishable": public["review"]["publication_state"] != "withheld",
                "reason": public["model_policy"]["reason"],
                "warnings": public["review"]["warnings"],
            },
            "note": valuation_note,
        },
    }
