"""History-backed practical baselines for controlled Universe Reset Batch 24."""
from __future__ import annotations
import copy,json
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _no_preferred
from .batch_16_history import _share_point
from .batch_24 import BATCH_24_TICKERS,BATCH_24_VALUATION_DATE
from .history import build_cash_fcff_history_profile
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config
BATCH_24_HISTORY_VERSION='BATCH-24-INDUSTRIALS-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'BLDR','TT','XYL','ALLE'});CONDITIONAL_TICKERS=frozenset({'NOC','TDG','GNRC','HII','UBER','ETN'});WITHHELD_TICKERS=frozenset()
def _shares(w,c):hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;weighted:float;current:float;current_end:str;growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalidation:str;formula:str
 @property
 def shares(self):return _shares(self.weighted,self.current)
P={
'NOC':Policy('defense_program_claim_adjusted_faded_fcff','2026-06-30',2.735e9,15.191e9,0.,142.4e6,142_063_026.,'2026-07-16',(-.02,.03,.06),(.11,.095,.085),(.005,.015,.025),'Conditional Low defense-program baseline. Five-year history and current bridge are finite, while cumulative B-21 program losses, contract cash, capacity investment, and a $402M unaccrued environmental possible-loss tail remain material.','Invalidate if B-21 or other program performance, contract cash, capacity investment, environmental recovery/loss, pensions, debt, or shares changes materially.','$2.307B cash plus $428M securities; $15.191B debt. Environmental claim range is $446M/$44M/$44M from $552M accrual + $402M possible unaccrued loss - $508M recorded recovery.'),
'TDG':Policy('post_acquisition_leveraged_aerospace_parts_faded_fcff','2026-06-27',2.773e9,32.989e9,90e6,57.9e6,55_276_525.,'2026-07-31',(0.,.06,.10),(.115,.10,.09),(.005,.015,.025),'Conditional Low leveraged aerospace-parts baseline. Cash history is finite, while $3.159B YTD acquisitions, a subsequent $1.1B acquisition, high leverage, redeemable NCI, and acquired conversion remain material.','Invalidate if subsequent acquisitions, acquired cash conversion, debt, redeemable NCI, pricing, claims, or shares changes materially.','$32.989B debt carrying amount plus $9M NCI and $81M redeemable NCI.'),
'BLDR':Policy('housing_cycle_building_products_faded_fcff','2026-06-30',65.651e6,4.632386e9,0.,108.710e6,107_596_457.,'2026-07-23',(-.05,0.,.04),(.11,.095,.085),(0.,.01,.02),'Source-bounded housing-cycle building-products baseline. Five-year cash history, current debt, cash, shares, zero preferred stock, and ordinary acquisition treatment reconcile.','Invalidate if housing demand, lumber prices, working capital, debt/leases, claims, acquisitions, or shares changes materially.','$4.632386B debt carrying amount; no nonzero NCI/preferred claim.'),
'TT':Policy('climate_systems_faded_fcff','2026-06-30',1.3183e9,4.6168e9,22.2e6,222.8e6,220_023_177.,'2026-07-24',(0.,.06,.10),(.105,.09,.08),(.005,.015,.025),'Source-bounded climate-systems baseline. Five-year cash history and current acquisition, debt, NCI, warranty, pension, discontinued-operation, and share evidence reconcile within the governed range.','Invalidate if acquired cash conversion, warranty/pension cash, debt, NCI, discontinued operations, or shares changes materially.','$693.1M current plus $3.9237B noncurrent debt and $22.2M NCI; warranties/pensions remain operating cash items.'),
'GNRC':Policy('standby_power_cycle_faded_fcff','2026-06-30',264.921e6,1.281010e9,.372e6,59.436379e6,59_006_361.,'2026-07-31',(-.06,.02,.07),(.115,.10,.09),(0.,.01,.02),'Conditional Low standby-power cycle baseline. Five-year history retains the weak 2022 cash year, while acquisition integration, tariffs/refunds, goodwill impairment, warranties, and volatile channel/outage demand remain material.','Invalidate if outage demand, channel inventory, tariffs/refunds, warranty cash, acquisitions, impairment, debt/leases, NCI, or shares changes materially.','$1.281010B debt/capital leases plus $5K NCI and $367K redeemable NCI.'),
'HII':Policy('shipbuilding_program_normalized_faded_fcff','2026-06-30',12e6,2.702e9,0.,39.4e6,39_404_598.,'2026-07-24',(-.03,.02,.05),(.115,.10,.09),(0.,.01,.02),'Conditional Low shipbuilding-program baseline. Five-year history provides a finite normalized range, while current post-capex cash is negative and contract-asset, program-timing, pension, and cash-buffer risk remain material.','Invalidate if ship delivery/program cash, contract assets/liabilities, capex, pensions, debt, claims, or shares changes materially.','$2.702B noncurrent debt; $12M cash/restricted cash. Operating contract liabilities remain inside cash conversion.'),
'XYL':Policy('water_infrastructure_faded_fcff','2026-06-30',1.276e9,2.926e9,245e6,239.967e6,233_486_812.,'2026-07-24',(0.,.05,.08),(.105,.09,.08),(.005,.015,.025),'Source-bounded water-infrastructure baseline. Five-year cash history, current debt, NCI/redeemable NCI, shares, warranty, restructuring, and supplier-finance treatment reconcile.','Invalidate if water demand, integration, cash conversion, debt, NCI, restructuring, supplier finance, warranties, or shares changes materially.','$2.926B combined debt plus $3M NCI and $242M redeemable NCI.'),
'UBER':Policy('marketplace_restricted_funds_faded_fcff','2026-06-30',5.504e9,12.723e9,1.083e9,2.060763e9,2_042_560_121.,'2026-07-31',(-.05,.08,.15),(.12,.10,.09),(0.,.01,.02),'Conditional Low marketplace baseline. Corporate cash/unrestricted securities, debt, NCI, shares, and five-year cash history are finite, while restricted funds, driver/merchant balances, acquisitions, strategic investments, legal/tax reserves, and rapid cash-conversion change remain material.','Invalidate if restricted/customer funds, driver/merchant balances, acquisitions, investments, legal/tax reserves, debt, NCI, cash conversion, or shares changes materially.','$4.870B cash plus only $634M unrestricted residual of $10.120B AFS debt securities after excluding $9.486B restricted investments. $12.723B debt plus $903M nonredeemable and $180M redeemable NCI.'),
'ETN':Policy('post_acquisition_electrical_systems_faded_fcff','2026-06-30',695e6,20.611e9,45e6,389.4e6,388.4e6,'2026-06-30',(0.,.06,.10),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-acquisition electrical-systems baseline. Current operations are finite, while $11.079B H1 acquisition cash, new short-term funding, goodwill, supplier finance, restructuring, pensions, and acquired conversion remain material.','Invalidate if acquired cash conversion, purchase accounting, acquisition funding, supplier finance, restructuring, pensions, NCI, or shares changes materially.','$18.520B total long-term debt plus $2.091B short-term borrowings and $45M NCI; $483M cash plus $212M short-term investments.'),
'ALLE':Policy('security_products_faded_fcff','2026-06-30',387.2e6,2.0408e9,0.,86.3e6,85_036_786.,'2026-07-20',(0.,.05,.08),(.105,.09,.08),(.005,.015,.025),'Source-bounded security-products baseline. Five-year cash history, current cash/investments, debt, shares, warranties, leases, acquisitions, and restructuring reconcile.','Invalidate if commercial demand, pricing, cash conversion, investments, debt/leases, warranties, claims, acquisitions, or shares changes materially.','$320.6M cash plus $66.6M nonmarketable debt/equity investments; $2.0408B debt carrying amount.'),
}
POINT={
'NOC':(('CashAndCashEquivalentsAtCarryingValue',2.307e9),('MarketableSecurities',428e6),('LongTermDebtCurrent',763e6),('LongTermDebtNoncurrent',14.428e9),('PreferredStockValue',0.)),
'TDG':(('CashAndCashEquivalentsAtCarryingValue',2.773e9),('DebtInstrumentCarryingAmount',32.989e9),('MinorityInterest',9e6),('RedeemableNoncontrollingInterestEquityCarryingAmount',81e6)),
'BLDR':(('CashAndCashEquivalentsAtCarryingValue',65.651e6),('DebtInstrumentCarryingAmount',4.632386e9)),
'TT':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations',1.3183e9),('DebtCurrent',693.1e6),('LongTermDebtNoncurrent',3.9237e9),('MinorityInterest',22.2e6)),
'GNRC':(('CashAndCashEquivalentsAtCarryingValue',264.921e6),('DebtAndCapitalLeaseObligations',1.281010e9),('MinorityInterest',5e3),('RedeemableNoncontrollingInterestEquityCarryingAmount',367e3)),
'HII':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',12e6),('LongTermDebtNoncurrent',2.702e9)),
'XYL':(('CashAndCashEquivalentsAtCarryingValue',1.276e9),('DebtLongtermAndShorttermCombinedAmount',2.926e9),('MinorityInterest',3e6),('RedeemableNoncontrollingInterestEquityCarryingAmount',242e6)),
'UBER':(('CashAndCashEquivalentsAtCarryingValue',4.870e9),('AvailableForSaleSecuritiesDebtSecurities',10.120e9),('RestrictedInvestments',9.486e9),('LongTermDebt',12.723e9),('NonredeemableNoncontrollingInterest',903e6),('RedeemableNoncontrollingInterestEquityCarryingAmount',180e6)),
'ETN':(('CashAndCashEquivalentsAtCarryingValue',483e6),('ShortTermInvestments',212e6),('LongTermDebt',18.520e9),('ShortTermBorrowings',2.091e9),('MinorityInterest',45e6)),
'ALLE':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',320.6e6),('DebtAndEquityInvestmentsWithoutReadilyDeterminableFairValues',66.6e6),('DebtInstrumentCarryingAmount',2.0408e9)),
}
START={'NOC':'2026-01-01','TDG':'2025-10-01','BLDR':'2026-01-01','TT':'2026-01-01','GNRC':'2026-01-01','HII':'2026-01-01','XYL':'2026-01-01','UBER':'2026-01-01','ETN':'2026-01-01','ALLE':'2026-01-01'}
def _norm(t,sub,facts):
 if t not in {'NOC','TDG'}:return _normalizer(sub,facts)
 c=copy.deepcopy(load_concept_config())
 if t=='NOC':c['fields']['interest_expense']['concepts'].append('InterestAndDebtExpense')
 else:c['fields']['interest_expense']['concepts']=['InterestPaidNet']
 return _normalizer(sub,facts,concept_config=c)
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]];rows.append(_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=p.weighted,period_start=START[t],period_end=p.period));rows.append(_share_point(st,expected=p.current,end=p.current_end))
 if t!='TDG':rows.append(_no_preferred(st,p.period))
 return rows
EVENT={'NOC':('ordinary defense program execution',{'pension_obligation_usd':1.086e9}),'TDG':('current and subsequent acquisitions',{'ytd_acquisition_cash_usd':3.159e9,'subsequent_acquisition_expected_usd':1.1e9}),'BLDR':('housing cycle and ordinary bolt-ons',{'h1_acquisition_cash_usd':25.907e6}),'TT':('current-year climate acquisition',{'h1_acquisition_cash_usd':742e6,'warranty_accrual_usd':459.7e6}),'GNRC':('standby-power cycle, tariffs, and warranties',{'h1_acquisition_cash_usd':211.82e6,'tariff_refund_usd':61.4e6,'warranty_claims_usd':363.774e6}),'HII':('shipbuilding program cash timing',{'current_ttm_cash_fcff_negative':True}),'XYL':('ordinary water-infrastructure operations',{'redeemable_nci_usd':242e6}),'UBER':('marketplace acquisitions and restricted funds',{'h1_acquisition_cash_usd':653e6,'restricted_investments_usd':9.486e9,'driver_merchant_liability_usd':1.773e9}),'ETN':('current-year electrical acquisition',{'h1_acquisition_cash_usd':11.079e9,'short_term_borrowings_usd':2.091e9}),'ALLE':('ordinary security-products operations',{'h1_acquisition_cash_usd':75.5e6})}
def _events(t,f,st):
 matter,terms=EVENT[t];rows=[{'source_kind':'controlling_filing_narrative','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':matter,'reported_terms':terms,'reported_vs_estimated':'reported_narrative'}];spec={'TDG':('PaymentsToAcquireBusinessesNetOfCashAcquired','2025-10-01',3.159e9),'BLDR':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',25.907e6),'TT':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',742e6),'GNRC':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',211.82e6),'UBER':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',653e6),'ETN':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',11.079e9),'ALLE':('PaymentsToAcquireBusinessesAndInterestInAffiliates','2026-01-01',75.5e6)}
 if t in spec:n,s,v=spec[t];rows.append(_structural_flow(st,name=n,start=s,end=P[t].period,expected=v))
 if t=='NOC':rows.extend((_point(st,name='AccrualForEnvironmentalLossContingencies',expected=552e6,period_end='2026-06-30'),_point(st,name='RecordedThirdPartyEnvironmentalRecoveriesAmount',expected=508e6,period_end='2026-06-30'),_point(st,name='LossContingencyRangeOfPossibleLossPortionNotAccrued',expected=402e6,period_end='2026-06-30')))
 return rows
def build_batch_24_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 p=P[ticker];q=Path(source_root)/ticker;sub=json.loads((q/'submissions.json').read_text());facts=json.loads((q/'companyfacts.json').read_text());m=json.loads((q/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,sub)
 if st['source_accession']!=f['accession']:raise ValueError(ticker)
 n=_norm(ticker,sub,facts);flows={x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,taxsrc=_normalized_tax_rate(n)
 except ValueError:tax,taxsrc=.21,()
 if not .05<=tax<=.30:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(x) for v in flows.values() for x in v.get('sources',[])];rev=float(flows['revenue']['value']);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_24_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if not prof.full_history or cm is None or gm is None:raise ValueError(f'{ticker}: history unavailable')
 margins=tuple(max(.001,float(x)) for x in (cm.low,cm.base,cm.high));growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0.,min(p.growth[2],gm.high)));claim_range=(446e6,44e6,44e6) if ticker=='NOC' else (p.claims,)*3;rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0.,claim_range[i],p.shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0.,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claim_range[i],'shares':p.shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(ticker)
 ok=ticker in PASS_TICKERS;reasons=() if ok else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ok else 'Low',source_cap='High',reasons=reasons);pub=prof.public_metadata()
 if not ok:pub.update({'normalization_basis':'company_history_with_named_material_transition','assumption_source_mix':'reported_history_and_finsight_policy'})
 ass={**pub,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Exact faded-cash base.','invalidation':p.invalidation};base=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_24_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ok else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked annual and current cash history.'),),warnings=(p.warning,p.invalidation),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_24_HISTORY_VERSION,'availability_type':'available' if ok else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':f,'flow_sources':flows,'annual_cash_sources':list(annual),'tax_rate_sources':list(taxsrc),'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'event_sources':_events(ticker,f,st),'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claim_range,'other_equity_claim_formula':p.formula,'shares':p.shares,'operating_liability_treatment':'Operating leases, supplier finance, pensions, warranties, marketplace balances, and contract liabilities remain inside cash conversion unless explicitly bridged.'},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
if set(P)!=set(BATCH_24_TICKERS) or PASS_TICKERS|CONDITIONAL_TICKERS|WITHHELD_TICKERS!=set(BATCH_24_TICKERS):raise RuntimeError('Batch24 mismatch')
