"""History-backed practical baselines for controlled Universe Reset Batch 18."""
from __future__ import annotations
from copy import deepcopy
from dataclasses import dataclass
import hashlib,json
from pathlib import Path
from typing import Any
from app.valuation.bank import residual_income_valuation
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _no_preferred
from .batch_16_history import _history_source,_share_point
from .batch_18 import BATCH_18_TICKERS,BATCH_18_VALUATION_DATE
from .equity_fact_selection import annual_facts
from .history import HISTORY_POLICY_VERSION,CompanyHistoryProfile,HistoryObservation,build_cash_fcff_history_profile,summarize_history_metric
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config

BATCH_18_HISTORY_VERSION='BATCH-18-INDUSTRIALS-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'HWM','ADP','DOV','EFX','GD'});CONDITIONAL_TICKERS=frozenset({'BA','CAT','CMI','DAL','EMR'});WITHHELD_TICKERS=frozenset();EQUITY_EARNINGS_TICKERS=frozenset({'CAT'})
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:tuple[float,float,float];shares:tuple[float,float,float];growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalidation:str;claim_formula:str
def _shares(weighted,current):
 hi,lo=max(weighted,current),min(weighted,current);return hi,(hi+lo)/2,lo
P={
'HWM':Policy('aerospace_components_faded_fcff','2026-06-30',563e6,4.501e9,(0.,)*3,_shares(402e6,398_801_399.),(.03,.10,.14),(.11,.095,.085),(.01,.02,.025),'Source-bounded aerospace-components cash baseline. Five-year cash history, current cash, complete debt, no preferred/NCI, and shares reconcile; current legal matters are not expected to be materially adverse.','Invalidate if aerospace demand, pricing, cash conversion, debt, separation indemnities, claims, or shares changes materially.','No NCI or preferred claim; restricted cash is excluded from surplus cash.'),
'ADP':Policy('client_funds_reserved_payroll_services_fcff','2026-06-30',4.2301e9,4.9651e9,(475.7e6,)*3,_shares(403.3e6,397_262_737.),(.03,.07,.09),(.105,.09,.08),(.01,.02,.025),'Source-bounded payroll-services baseline. Client funds and matching obligations remain outside surplus cash; the current client-fund shortfall and net legal accrual are reserved explicitly.','Invalidate if employment levels, client-fund assets/obligations, float income, operating cash, debt, claims, or shares changes materially.','$457.7M client-fund obligation excess over funds held plus $18M net litigation claim after the scoped $30M receivable; client funds are not treated as issuer-owned cash.'),
'BA':Policy('post_spirit_aerospace_cycle_faded_fcff','2026-06-30',21.139e9,50.161e9,(1.130e9,)*3,_shares(789.2e6,790_370_020.),(-.03,.03,.08),(.13,.11,.10),(-.01,.01,.02),'Conditional Low post-Spirit aerospace-cycle baseline. The bear residual is negative and floored at zero; the positive base uses a governed through-cycle margin between the full-history median and upper percentile.','Invalidate if production/certification, Spirit integration, program charges, customer advances, debt, claims, cash, or shares changes materially.','$1.115B reported possible loss not accrued plus $15M NCI; cash and current/noncurrent investments are counted once.'),
'CMI':Policy('powertrain_cycle_faded_fcff','2026-06-30',3.924e9,7.695e9,(1.109e9,)*3,_shares(138.6e6,137_664_487.),(-.03,.06,.10),(.11,.095,.085),(0.,.015,.025),'Conditional Low powertrain-cycle baseline. Current cash/debt and five-year history reconcile, while Accelera investment, environmental settlement execution, guarantees, NCI, and cycle assumptions remain material.','Invalidate if powertrain demand, Accelera cash, settlement payments, guarantees, debt, NCI, or shares changes materially.','$1.059B NCI plus $50M maximum reported guarantees; no missing claim is substituted with zero.'),
'DAL':Policy('airline_cycle_faded_fcff','2026-06-30',4.665e9,12.893e9,(0.,)*3,_shares(657e6,657_623_030.),(-.05,.04,.08),(.12,.105,.095),(0.,.01,.02),'Conditional Low airline-cycle baseline. Current cash, debt, shares, and four-year post-pandemic cash history reconcile; fleet capex, fuel, pensions, and operating-cycle sensitivity remain material.','Invalidate if demand, fares, fuel, fleet commitments, pensions, debt/leases, claims, or shares changes materially.','No separately reported preferred/NCI claim; operating leases remain post-rent in cash conversion and are not deducted twice.'),
'DOV':Policy('diversified_industrial_faded_fcff','2026-06-30',1.755971e9,3.259988e9,(0.,)*3,_shares(135.725e6,134_680_225.),(-.02,.02,.05),(.105,.09,.08),(.005,.015,.025),'Source-bounded diversified-industrial cash baseline. Five-year continuing cash history, current cash, aggregate debt, no NCI/preferred, and shares reconcile.','Invalidate if end-market demand, acquisitions/dispositions, cash conversion, debt, claims, or shares changes materially.','No NCI or preferred claim; current cash includes restricted cash in the reported aggregate and is counted once.'),
'EMR':Policy('post_aspentech_automation_faded_fcff','2026-06-30',2.180e9,13.113e9,(15e6,)*3,_shares(562.7e6,557.8e6),(.02,.07,.11),(.11,.095,.085),(.01,.02,.025),'Conditional Low post-AspenTech automation baseline. Five-year cash history and current debt reconcile, while the $7.2B remaining-interest acquisition, software integration, NCI, and portfolio actions remain material.','Invalidate if AspenTech integration, software cash, acquisitions/divestitures, debt, NCI, claims, or shares changes materially.','$15M NCI; current debt is current plus noncurrent and operating leases remain inside cash conversion.'),
'EFX':Policy('post_refinancing_data_services_faded_fcff','2026-06-30',1.1606e9,6.4853e9,(139.7e6,)*3,_shares(119.9e6,117_484_896.),(.01,.05,.07),(.11,.095,.085),(.01,.02,.025),'Source-bounded data-services baseline. The cutoff bridge adds $1B issued notes and $990.5M proceeds once; intended commercial-paper repayment is not assumed without completion evidence.','Invalidate if debt repayment, data demand, mortgage conditions, cybersecurity claims, NCI, or shares changes materially.','$18.2M NCI plus $121.5M redeemable NCI. Post-balance financing adds principal and proceeds once, producing only a $9.5M net-debt increase before repayment evidence.'),
'GD':Policy('defense_backlog_faded_fcff','2026-07-05',4.300e9,7.572e9,(0.,)*3,_shares(273.806e6,270_557_195.),(.02,.07,.10),(.105,.09,.08),(.01,.02,.025),'Source-bounded defense-backlog cash baseline. Five-year source history, current unrestricted cash/debt, no other equity claims, and shares reconcile; the rescission offer is within the governed share range and is assessed immaterial.','Invalidate if backlog conversion, program charges, rescission participation, debt, claims, cash, or shares changes materially.','No preferred/NCI claim; $33M restricted cash is excluded from surplus cash, and the maximum 1,010,925-share rescission offer is bounded inside the diluted-share range and not assumed exercised.'),}
POINT_SPECS={
'HWM':(('CashAndCashEquivalentsAtCarryingValue',563e6),('DebtLongtermAndShorttermCombinedAmount',4.501e9),('PreferredStockSharesOutstanding',0.)),
'ADP':(('CashAndCashEquivalentsAtCarryingValue',4.2301e9),('FundsHeldClients',43.9578e9),('ClientFundsObligations',44.4155e9),('DebtCurrent',1e6),('LongTermDebtNoncurrent',4.9641e9),('LossContingencyAccrualAtCarryingValue',48e6),('LossContingencyReceivable',30e6),('PreferredStockValue',0.)),
'BA':(('CashAndCashEquivalentsAtCarryingValue',7.239e9),('ShortTermInvestments',12.783e9),('LongTermInvestments',1.117e9),('DebtCurrent',4.565e9),('LongTermDebt',45.596e9),('LossContingencyRangeOfPossibleLossPortionNotAccrued',1.115e9),('MinorityInterest',15e6)),
'CMI':(('CashCashEquivalentsAndShortTermInvestments',3.924e9),('DebtInstrumentCarryingAmount',7.695e9),('MinorityInterest',1.059e9)),
'DAL':(('CashAndCashEquivalentsAtCarryingValue',4.665e9),('DebtInstrumentCarryingAmount',12.893e9)),
'DOV':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',1.755971e9),('LongTermDebt',3.259988e9)),
'EMR':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',2.180e9),('DebtCurrent',5.587e9),('LongTermDebtNoncurrent',7.526e9),('MinorityInterest',15e6)),
'EFX':(('CashAndCashEquivalentsAtCarryingValue',170.1e6),('DebtInstrumentCarryingAmount',5.4853e9),('MinorityInterest',18.2e6),('RedeemableNoncontrollingInterestEquityCarryingAmount',121.5e6),('PreferredStockValue',0.)),
'GD':(('CashAndCashEquivalentsAtCarryingValue',4.300e9),('DebtLongtermAndShorttermCombinedAmount',7.572e9)),}
SHARE_STARTS={'HWM':'2026-01-01','ADP':'2025-07-01','BA':'2026-01-01','CMI':'2026-01-01','DAL':'2026-01-01','DOV':'2026-01-01','EMR':'2025-10-01','EFX':'2026-01-01','GD':'2026-01-01'}
SHARE_ENDS={'HWM':'2026-08-03','ADP':'2026-07-31','BA':'2026-07-21','CMI':'2026-06-30','DAL':'2026-06-30','DOV':'2026-07-17','EMR':'2026-06-30','EFX':'2026-07-10','GD':'2026-07-05'}
WEIGHTED_SHARES={'HWM':402e6,'ADP':403.3e6,'BA':789.2e6,'CMI':138.6e6,'DAL':657e6,'DOV':135.725e6,'EMR':562.7e6,'EFX':119.9e6,'GD':273.806e6}
CURRENT_SHARES={'HWM':398_801_399.,'ADP':397_262_737.,'BA':790_370_020.,'CMI':137_664_487.,'DAL':657_623_030.,'DOV':134_680_225.,'EMR':557.8e6,'EFX':117_484_896.,'GD':270_557_195.}
EVENTS={'HWM':{'matter':'ordinary legal and separation-indemnity state','reported_terms':{'management_assessment':'not expected materially adverse'}},'ADP':{'matter':'client-funds investment and obligation state','reported_terms':{'funds_held_usd':43.9578e9,'client_obligations_usd':44.4155e9}},'BA':{'matter':'Spirit acquisition and production recovery','reported_terms':{'spirit_close':'2025-12-08','consideration_usd':8.389e9}},'CMI':{'matter':'Accelera investment, settlement, and guarantees','reported_terms':{'maximum_guarantees_usd':50e6}},'DAL':{'matter':'airline fleet and operating cycle','reported_terms':{'legal_assessment':'current matters not expected materially adverse'}},'DOV':{'matter':'ordinary acquisitions and dispositions','reported_terms':{'current_state':'continuing operations'}},'EMR':{'matter':'AspenTech remaining-interest acquisition','reported_terms':{'close_date':'2025-03-12','cash_purchase_usd':7.2e9}},'EFX':{'matter':'post-balance notes issuance','reported_terms':{'event_source_required':True}},'GD':{'matter':'share rescission offer','reported_terms':{'event_source_required':True}}}
def _config(t):
 c=deepcopy(load_concept_config())
 if t=='ADP':c['fields']['capital_expenditures']['concepts'].append('PaymentsToAcquireOtherPropertyPlantAndEquipment')
 if t=='BA':c['fields']['interest_expense']['concepts'].append('InterestAndDebtExpense')
 if t=='GD':c['fields']['interest_expense']['concepts'].insert(0,'InterestExpenseOperating')
 return c
def _event(event_root,ticker):
 receipt=json.loads((Path(event_root)/ticker/'source-receipt.json').read_text());doc=Path(event_root)/ticker/receipt['primary_document']
 if receipt.get('schema_version')!='FINSIGHT-BATCH-18-EVENT-SOURCE-1' or receipt.get('valuation_date')!=BATCH_18_VALUATION_DATE or hashlib.sha256(doc.read_bytes()).hexdigest()!=receipt.get('document_sha256'):raise ValueError(f'{ticker}: event source invalid')
 return {'source_kind':'sec_current_report','accession':receipt['accession'],'filed':receipt['filed'],'form':receipt['form'],'period_end':receipt['report_date'],'url':receipt['url'],'document_sha256':receipt['document_sha256'],'reported_terms':receipt['reported_terms'],'treatment':receipt['treatment'],'reported_vs_estimated':'reported'}
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT_SPECS[t]];rows.extend((_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=WEIGHTED_SHARES[t],period_start=SHARE_STARTS[t],period_end=p.period),_share_point(st,expected=CURRENT_SHARES[t],end=SHARE_ENDS[t]),_no_preferred(st,p.period)))
 return rows
def _operating(t,filing,st,subs,facts,event_root):
 p=P[t];n=_normalizer(subs,facts,concept_config=_config(t) if t in {'ADP','BA','GD'} else None);flows={x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,taxrows=_normalized_tax_rate(n)
 except ValueError:tax,taxrows=.21,()
 if tax<.05:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(y) for x in flows.values() for y in x.get('sources',[])];rev=float(flows['revenue']['value']);profile=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_18_VALUATION_DATE);cm,gm=profile.metric('cash_conversion_margin'),profile.metric('revenue_growth')
 if not profile.full_history or cm is None or gm is None:raise ValueError(f'{t}: history unavailable')
 margins=tuple(max(.001,x) for x in (cm.low,cm.base,cm.high))
 if t=='BA':margins=(.001,(cm.base+cm.high)/2,cm.high)
 growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0,min(p.growth[2],gm.high)));rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  state=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0,p.claims[i],p.shares[i]);trace=enterprise_cash_flow_dcf(state,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(trace['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0,raw),'raw_value_per_share':raw,'starting_cash_fcff':state.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims[i],'shares':p.shares[i],'limited_liability_floor_applied':raw<0});traces[name]=trace
 scenario={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=scenario['low']<=scenario['base']<=scenario['high'] or scenario['base']<=0:raise ValueError(f'{t}: invalid range')
 ispass=t in PASS_TICKERS;reasons=() if ispass else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=scenario['base'],accounting_base=scenario['base'],accounting_high=scenario['base'],scenario_low=scenario['low'],scenario_base=scenario['base'],scenario_high=scenario['high'],model_cap='High' if ispass else 'Low',source_cap='High',reasons=reasons);public=profile.public_metadata()
 if not ispass:public.update({'normalization_basis':'company_history_with_named_material_dependency','assumption_source_mix':'reported_history_and_finsight_policy'})
 assumptions={**public,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'equity_floor_basis':'limited-liability bear floor with raw residual retained' if scenario['low']==0 else 'not applied','calculator_calibration':'Calculator is calibrated to the exact faded-cash base; private bridge and event schedules remain fixed.','invalidation':p.invalidation};base=BaselineValuation(ticker=t,method=p.method,method_version=BATCH_18_HISTORY_VERSION,low=scenario['low'],base=scenario['base'],high=scenario['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ispass else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(profile.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked annual and current cash conversion anchors the range.'),BaselineAssumption('faded operating states',str({'growth':growth,'wacc':p.wacc,'terminal':p.terminal}),AssumptionClassification.FINSIGHT_ASSUMPTION,'Growth fades over eight years to a governed terminal state.')),warnings=(p.warning,p.invalidation),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{t}/calculator')
 narrative={'source_kind':'controlling_filing_narrative','accession':filing['accession'],'filed':filing['filed'],'period_end':filing['period_end'],'reported_vs_estimated':'reported_narrative',**EVENTS[t]};events=[narrative,*([_event(event_root,t)] if t in {'EFX','GD'} else [])]
 return {'ticker':t,'method':p.method,'model_version':BATCH_18_HISTORY_VERSION,'availability_type':'available' if ispass else 'conditional_estimate','scenario_rows':rows,'scenario_range':scenario,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'ttm_cash_fcff':current},'governed_assumptions':assumptions,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':filing,'flow_sources':flows,'tax_rate_sources':list(taxrows),'company_history_profile':profile.as_private_dict(),'bridge_sources':_bridge(t,st,p),'event_sources':events,'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims,'other_equity_claim_formula':p.claim_formula,'shares':p.shares,'operating_liability_treatment':'Ordinary operating liabilities remain inside cash conversion and are not deducted again.'},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
def _cat(filing,st,facts):
 gaap=facts['facts']['us-gaap'];annual=annual_facts(gaap,concepts=('NetIncomeLossAvailableToCommonStockholdersBasic',),unit='USD',valuation_date=BATCH_18_VALUATION_DATE);obs=[]
 for y in (2021,2022,2023,2024,2025):f=annual[y];obs.append(HistoryObservation('annual',f.period_end,y,f.value,'USD','reported common-stockholder earnings',(_history_source(f),)))
 cur=_structural_flow(st,name='ProfitLoss',start='2026-01-01',end='2026-06-30',expected=6.141e9);curnci=_structural_flow(st,name='NetIncomeLossAttributableToNoncontrollingInterest',start='2026-01-01',end='2026-06-30',expected=-1e6);prior=_structural_flow(st,name='ProfitLoss',start='2025-01-01',end='2025-06-30',expected=4.182e9);ttm=annual[2025].value+cur['value']-curnci['value']-prior['value'];obs.append(HistoryObservation('operating_ttm','2026-06-30',None,ttm,'USD','latest FY + current H1 - NCI - prior H1',(_history_source(annual[2025]),cur,curnci,prior)));metric=summarize_history_metric('normalized_common_earnings',obs);profile=CompanyHistoryProfile(HISTORY_POLICY_VERSION,'mixed_industrial_finance_residual_income',BATCH_18_VALUATION_DATE,tuple(x.period_end for x in obs if x.period_role=='annual'),(metric,),True,'reported_and_company_history');begin,end=21.318e9,19.395e9;avg=(begin+end)/2;shares=_shares(464.3e6,459_674_889.);earn=(metric.low,metric.base,metric.high);div=1.399e9;payout=min(1,div*2/ttm);coe,troe,tg=(.12,.10,.085),(.12,.22,.32),(.01,.02,.025);rows=[];traces={};multiples=[]
 for i,name in enumerate(('bear','base','bull')):
  tr=residual_income_valuation(book_value_per_share=end/shares[i],current_roe=earn[i]/avg,cost_of_equity=coe[i],current_payout_ratio=payout,terminal_roe=troe[i],terminal_growth=tg[i],years=5);raw=float(tr['intrinsic_value']);multiple=raw*shares[i]/earn[i];rows.append({'name':name,'conditional_value_per_share':raw,'raw_value_per_share':raw,'normalized_common_earnings':earn[i],'book_value_per_share':end/shares[i],'current_roe':earn[i]/avg,'current_payout_ratio':payout,'cost_of_equity':coe[i],'terminal_roe':troe[i],'terminal_growth':tg[i],'earnings_multiple':multiple,'shares':shares[i],'limited_liability_floor_applied':False});traces[name]=tr;multiples.append(multiple)
 scenario={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']};reasons=('CONSOLIDATED_MODEL_FALLBACK','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=scenario['base'],accounting_base=scenario['base'],accounting_high=scenario['base'],scenario_low=scenario['low'],scenario_base=scenario['base'],scenario_high=scenario['high'],model_cap='Low',source_cap='High',reasons=reasons);warning='Conditional Low mixed industrial/captive-finance residual-income baseline. Common equity and earnings avoid double-counting Financial Products debt, while equipment cycle, finance receivables, credit losses, and capital allocation remain material.';invalid='Invalidate if common equity/earnings, finance receivables/credit losses, equipment cycle, payout, capital allocation, or shares changes materially.';ass={**profile.public_metadata(),'normalization_basis':'reported_common_equity_and_history_residual_income','assumption_source_mix':'reported_common_equity_earnings_dividends_and_finsight_policy','normalized_common_earnings':earn,'earnings_multiples':tuple(multiples),'shares':shares,'book_equity':end,'average_common_equity':avg,'current_payout_ratio':payout,'cost_of_equity':coe,'terminal_roe':troe,'terminal_growth':tg,'route_is_equity_level':True,'ev_debt_bridge_applied':False,'equity_floor_basis':'not applied','calculator_calibration':'Calculator varies normalized earnings and the residual-income-implied multiple around the base.','invalidation':invalid};base=BaselineValuation(ticker='CAT',method='mixed_industrial_captive_finance_residual_income_equity_earnings',method_version=BATCH_18_HISTORY_VERSION,low=scenario['low'],base=scenario['base'],high=scenario['high'],confidence=rel.label,availability_type=AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('reported common equity',end,AssumptionClassification.REPORTED,'Current parent equity anchors residual income.'),BaselineAssumption('company earnings history',str(profile.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Common earnings history supplies the ROE range.')),warnings=(warning,invalid),confidence_reasons=reasons,calculator_link='/api/us-valuations/CAT/calculator');context=[_point(st,name='StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest',expected=19.394e9,period_end='2026-06-30'),_point(st,name='MinorityInterest',expected=-1e6,period_end='2026-06-30'),_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=464.3e6,period_start='2026-01-01',period_end='2026-06-30'),_share_point(st,expected=459_674_889.,end='2026-06-30'),_structural_flow(st,name='PaymentsOfDividendsCommonStock',start='2026-01-01',end='2026-06-30',expected=div),_no_preferred(st,'2026-06-30')]
 return {'ticker':'CAT','method':base.method,'model_version':BATCH_18_HISTORY_VERSION,'availability_type':'conditional_estimate','scenario_rows':rows,'scenario_range':scenario,'reported_inputs':{'ttm_common_earnings':ttm,'beginning_common_equity':begin,'ending_common_equity':end,'h1_common_dividends':div},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':filing,'company_history_profile':profile.as_private_dict(),'equity_model_context':context,'event_sources':[{'source_kind':'controlling_filing_narrative','accession':filing['accession'],'filed':filing['filed'],'period_end':filing['period_end'],'matter':'mixed machinery and Financial Products economics','reported_terms':{'q2_financial_products_revenue_usd':962e6,'q2_financial_products_interest_usd':362e6},'reported_vs_estimated':'reported_narrative'}],'residual_income_trace':{'states':traces},'bridge_treatment':'Equity-level model; Financial Products receivables/debt, credit losses, industrial debt, and NCI remain inside common earnings/equity and are not EV-bridged.','structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':warning,'baseline':base.as_private_dict()}
def build_batch_18_history_result(*,ticker:str,source_root:Path,structural_root:Path,event_root:Path):
 if ticker not in BATCH_18_TICKERS:raise ValueError(ticker)
 packet=Path(source_root)/ticker;subs=json.loads((packet/'submissions.json').read_text());facts=json.loads((packet/'companyfacts.json').read_text());manifest=json.loads((packet/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());filing=_controlling(manifest,subs)
 if st['source_accession']!=filing['accession']:raise ValueError(f'{ticker}: source mismatch')
 if ticker=='CAT':return _cat(filing,st,facts)
 if filing['period_end']!=P[ticker].period:raise ValueError(f'{ticker}: period mismatch')
 return _operating(ticker,filing,st,subs,facts,event_root)
if set(P)|{'CAT'}!=set(BATCH_18_TICKERS):raise RuntimeError('Batch 18 denominator mismatch')
