"""History-backed practical baselines for controlled Universe Reset Batch 25."""
from __future__ import annotations
import copy,json
from dataclasses import dataclass
from pathlib import Path
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _dimension_fact,_no_preferred
from .batch_16_history import _share_point
from .batch_25 import BATCH_25_TICKERS,BATCH_25_VALUATION_DATE
from .history import build_cash_fcff_history_profile
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config
BATCH_25_HISTORY_VERSION='BATCH-25-INDUSTRIALS-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'IR','OTIS'});CONDITIONAL_TICKERS=frozenset({'FTV','DD','CARR','VLTO','GEV','FERG','FDXF'});WITHHELD_TICKERS=frozenset({'HONA'})
def _shares(w,c):hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;weighted:float;current:float;current_end:str;growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalid:str;formula:str
 @property
 def shares(self):return _shares(self.weighted,self.current)
P={
'FTV':Policy('post_separation_instrumentation_faded_fcff','2026-07-03',374.2e6,3.5093e9,8.8e6,310.2e6,302_017_052.,'2026-07-24',(-.03,.03,.07),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-separation instrumentation baseline. Legacy history is finite, while separation comparability, debt allocation, acquisition cash, and current conversion remain material.','Invalidate if post-separation cash, debt, acquisitions, NCI, or shares changes materially.','$374.2M cash; $3.5093B debt; $8.8M NCI.'),
'DD':Policy('post_divestiture_materials_faded_fcff','2026-06-30',1.740e9,3.125e9,112e6,137.2e6,135_042_975.,'2026-07-31',(-.03,.02,.06),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-divestiture materials baseline. Current operations are finite, while portfolio scope, divestiture proceeds, restructuring, pensions, supplier finance, and comparability remain material.','Invalidate if portfolio scope, cash conversion, debt, NCI, restructuring, or shares changes materially.','$1.740B cash; $3.125B debt/capital leases; $112M NCI.'),
'IR':Policy('industrial_machinery_faded_fcff','2026-06-30',1.1735e9,4.7685e9,65.7e6,391.7e6,387_999_429.,'2026-07-24',(0.,.05,.08),(.105,.09,.08),(.005,.015,.025),'Source-bounded industrial-machinery baseline. Five-year cash history and current cash, debt/leases, NCI, warranties, restructuring, supplier finance, and shares reconcile.','Invalidate if industrial demand, cash conversion, debt/leases, NCI, warranties, restructuring, or shares changes.','$1.1735B cash; $4.7685B debt/leases; $65.7M NCI.'),
'OTIS':Policy('elevator_service_faded_fcff','2026-06-30',813e6,8.480e9,294e6,386.4e6,380_669_339.,'2026-07-15',(0.,.04,.07),(.105,.09,.08),(.005,.015,.025),'Source-bounded elevator-service baseline. Five-year cash history and current debt, NCI/redeemable NCI, acquisitions, pensions, restructuring, supplier finance, and shares reconcile.','Invalidate if service cash, acquisitions, debt, NCI, pensions, supplier finance, or shares changes.','$813M cash; $8.270B debt plus $210M short borrowing; $188M NCI + $106M redeemable NCI.'),
'CARR':Policy('portfolio_transition_hvac_faded_fcff','2026-06-30',1.344e9,11.230e9,325e6,839.6e6,824_325_057.,'2026-07-15',(-.03,.02,.06),(.11,.095,.085),(0.,.01,.02),'Conditional Low HVAC portfolio-transition baseline. Five-year history is finite, while divestiture scope, restructuring, warranty cash, debt, and transition conversion remain material.','Invalidate if portfolio scope, divestitures, restructuring, warranties, debt, NCI, or shares changes.','$1.344B cash; $11.230B debt/leases; $325M NCI.'),
'VLTO':Policy('post_acquisition_water_quality_faded_fcff','2026-07-03',2.119e9,3.379e9,1e6,247.5e6,243_793_344.,'2026-07-21',(0.,.05,.09),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-acquisition water-quality baseline. Current cash history is finite, while $620M acquisition cash, acquired goodwill, debt, and acquired conversion remain material.','Invalidate if acquired cash conversion, purchase accounting, debt, NCI, warranties, or shares changes.','$2.119B cash; $3.379B total debt; $1M NCI.'),
'GEV':Policy('post_spin_energy_equipment_faded_fcff','2026-06-30',12.720e9,2.849e9,1.158e9,271e6,266_333_581.,'2026-06-30',(-.05,.03,.08),(.12,.10,.09),(0.,.01,.02),'Conditional Low post-spin energy-equipment baseline. Current history is finite, while warranty obligations, supplier finance, pension income, separation cash, restructuring, and segment cycle remain material.','Invalidate if warranty/supplier-finance cash, pensions, restructuring, restricted cash, debt, NCI, or shares changes.','$13.120B cash/restricted aggregate less $400M filing-disclosed restricted-use cash = $12.720B available; $2.849B debt/leases; $1.158B NCI.'),
'FERG':Policy('pre_fwi_distribution_faded_fcff','2026-06-30',437e6,4.925e9,0.,194.4e6,193_452_717.,'2026-08-03',(-.03,.03,.07),(.11,.095,.085),(0.,.01,.02),'Conditional Low pre-FWI distribution baseline. Three annual periods and current cash are finite, while the subsequent $1.6B FWI acquisition with committed financing, seven H1 acquisitions, working capital, debt, and supplier finance remain material.','Invalidate if FWI closes, terminates, or changes; or if acquisition conversion, working capital, debt, supplier finance, or shares changes.','$437M cash; $4.925B current debt; pending $1.6B FWI consideration remains separate and is not probability-weighted.'),
'FDXF':Policy('post_separation_freight_cycle_faded_fcff','2026-05-31',251e6,4.527e9,0.,149_505_248.,149_518_133.,'2026-08-03',(-.05,.02,.06),(.12,.105,.095),(0.,.01,.02),'Conditional Low standalone freight-cycle baseline. Three years of carve-out history are finite, while current post-separation cash is negative, separation costs, allocated debt/leases, and independent cash conversion remain material.','Invalidate if standalone freight cash, separation costs, debt/leases, pricing, or shares changes.','$251M cash; $4.527B debt/capital leases; operating leases remain inside cash conversion.'),
'HONA':Policy('newly_separated_aerospace_comparative_h1_fcff','2026-06-27',1.057e9,16.006e9,74e6,323.292e6,316_952_725.,'2026-07-25',(-.03,.03,.06),(.12,.105,.095),(0.,.01,.02),'Conditional Low newly separated aerospace baseline. Comparable H1 operations are finite, while there is no standalone annual cash history and opening $16B debt, negative equity, supplier finance, warranties, and separation allocations remain material.','Invalidate if standalone annual cash, debt allocation, supplier finance, warranties, NCI, or shares changes.','$1.057B cash; $16.006B debt carrying amount; $74M NCI; weighted shares are a governed 2% current-share sensitivity.'),
}
POINT={'FTV':(('CashAndCashEquivalentsAtCarryingValue',374.2e6),('LongTermDebt',3.5093e9),('MinorityInterest',8.8e6)),'DD':(('CashAndCashEquivalentsAtCarryingValue',1.740e9),('LongTermDebtAndCapitalLeaseObligations',3.125e9),('MinorityInterest',112e6)),'IR':(('CashAndCashEquivalentsAtCarryingValue',1.1735e9),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',4.7685e9),('MinorityInterest',65.7e6)),'OTIS':(('CashAndCashEquivalentsAtCarryingValue',813e6),('DebtInstrumentCarryingAmount',8.270e9),('ShortTermBorrowings',210e6),('MinorityInterest',188e6),('RedeemableNoncontrollingInterestEquityCarryingAmount',106e6)),'CARR':(('CashAndCashEquivalentsAtCarryingValue',1.344e9),('DebtAndCapitalLeaseObligations',11.230e9),('MinorityInterest',325e6)),'VLTO':(('CashAndCashEquivalentsAtCarryingValue',2.119e9),('LongTermDebt',3.379e9),('MinorityInterest',1e6),('PreferredStockValue',0.)),'GEV':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',13.120e9),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',2.849e9),('MinorityInterest',1.158e9)),'FERG':(('CashAndCashEquivalentsAtCarryingValue',437e6),('DebtInstrumentCarryingAmount',4.925e9)),'FDXF':(('Cash',251e6),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',4.527e9)),'HONA':(('CashAndCashEquivalentsAtCarryingValue',1.057e9),('DebtInstrumentCarryingAmount',16.006e9),('MinorityInterest',74e6))}
START={'FTV':'2026-01-01','DD':'2026-01-01','IR':'2026-01-01','OTIS':'2026-01-01','CARR':'2026-01-01','VLTO':'2026-01-01','GEV':'2026-01-01','FERG':'2026-01-01','FDXF':'2025-06-01'}
def _norm(t,sub,facts):
 if t not in {'DD','GEV'}:return _normalizer(sub,facts)
 c=copy.deepcopy(load_concept_config());c['fields']['interest_expense']['concepts']=['InterestAndDebtExpense'] if t=='DD' else ['InterestPaidNet'];return _normalizer(sub,facts,concept_config=c)
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]]
 if t=='HONA':rows.append({'source_kind':'governed_share_sensitivity','accession':st['source_accession'],'period_end':p.current_end,'current_shares':p.current,'weighted_proxy':p.weighted,'basis':'2% bear-side sensitivity because standalone diluted weighted shares are not reported'})
 else:rows.append(_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=p.weighted,period_start=START[t],period_end=p.period))
 rows.append(_share_point(st,expected=p.current,end=p.current_end));
 if t not in {'OTIS'}:rows.append(_no_preferred(st,p.period))
 return rows
def _events(t,f,st,p):
 rows=[{'source_kind':'controlling_filing_narrative','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':p.warning,'reported_terms':{'restricted_use_cash_usd':400e6} if t=='GEV' else {},'reported_vs_estimated':'reported_narrative'}]
 if t=='FERG':rows.append(_dimension_fact(st,name='BusinessCombinationConsiderationTransferred1',expected=1.6e9,start='2026-07-13',end='2026-07-13',member='FWIHoldingsInc.Member'))
 return rows
def _hona(st):
 def f(n,s,e,v):return _structural_flow(st,name=n,start=s,end=e,expected=v)
 cur={'revenue':f('RevenueFromContractWithCustomerExcludingAssessedTax','2026-01-01','2026-06-27',8.874e9),'ocf':f('NetCashProvidedByUsedInOperatingActivities','2026-01-01','2026-06-27',346e6),'capex':f('PaymentsToAcquirePropertyPlantAndEquipment','2026-01-01','2026-06-27',260e6),'interest':f('InterestExpenseNonoperating','2026-01-01','2026-06-27',229e6)};old={'revenue':f('RevenueFromContractWithCustomerExcludingAssessedTax','2025-01-01','2025-06-28',8.363e9),'ocf':f('NetCashProvidedByUsedInOperatingActivities','2025-01-01','2025-06-28',1.025e9),'capex':f('PaymentsToAcquirePropertyPlantAndEquipment','2025-01-01','2025-06-28',234e6),'interest':f('InterestExpenseNonoperating','2025-01-01','2025-06-28',0.)};tax=.238;cc=cash_fcff_from_reported(operating_cash_flow=346e6,capital_expenditures=260e6,spectrum_investment=0.,interest_expense=229e6,tax_rate=tax);oc=cash_fcff_from_reported(operating_cash_flow=1.025e9,capital_expenditures=234e6,spectrum_investment=0.,interest_expense=0.,tax_rate=.153);rows=[{'period_end':'2025-06-28','revenue':{**old['revenue'],'value':8.363e9,'fiscal_year':2025},'operating_cash_flow':old['ocf'],'capital_expenditures':old['capex'],'interest_expense':old['interest'],'pretax_income':None,'income_tax':None,'cash_fcff':oc},{'period_end':'2026-06-27','revenue':{**cur['revenue'],'value':8.874e9,'fiscal_year':2026},'operating_cash_flow':cur['ocf'],'capital_expenditures':cur['capex'],'interest_expense':cur['interest'],'pretax_income':None,'income_tax':None,'cash_fcff':cc}];flows={k:{'field':k,'value':v,'period_end':'2026-06-27','method':'annualized_current_h1','sources':list(cur.values())} for k,v in {'revenue':17.748e9,'operating_cash_flow':692e6,'capital_expenditures':520e6,'interest_expense':458e6}.items()};return flows,rows,tax
def build_batch_25_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 p=P[ticker];q=Path(source_root)/ticker;sub=json.loads((q/'submissions.json').read_text());facts=json.loads((q/'companyfacts.json').read_text());m=json.loads((q/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,sub)
 if st['source_accession']!=f['accession']:raise ValueError(ticker)
 if ticker=='HONA':flows,annual,tax=_hona(st);taxsrc=()
 else:
  n=_norm(ticker,sub,facts);flows={x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')};annual=_annual_cash_with_losses(n)[2]
  try:tax,taxsrc=_normalized_tax_rate(n)
  except ValueError:tax,taxsrc=.21,()
  if not .05<=tax<=.30:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);sources=[dict(x) for v in flows.values() for x in v.get('sources',[])];rev=float(flows['revenue']['value']);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_25_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if ticker=='HONA':
  reason='Withheld. Only comparative H1 standalone cash is filed, while opening $16.006B debt and separation allocations produce no defensible positive base across the finite current/prior cash states.';invalid='Revalue after a source-backed standalone annual cash history and final opening debt/cash allocation support a positive finite base.';base=BaselineValuation(ticker=ticker,method='unavailable_newly_separated_aerospace_history',method_version=BATCH_25_HISTORY_VERSION,low=None,base=None,high=None,confidence=None,availability_type=AvailabilityType.NOT_AVAILABLE,warnings=(reason,invalid));return {'ticker':ticker,'method':base.method,'model_version':BATCH_25_HISTORY_VERSION,'availability_type':'not_available','scenario_rows':[],'scenario_range':{'low':None,'base':None,'high':None},'reported_inputs':{'annualized_h1_revenue':rev,'annualized_h1_cash_fcff':current},'governed_assumptions':{'history_policy_version':prof.policy_version,'history_years_used':2,'normalization_basis':'comparative_h1_only_with_nonpositive_base','assumption_source_mix':'reported_comparative_h1','invalidation':invalid},'history_reliability':None,'source_ledger':{'controlling_filing':f,'flow_sources':flows,'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'bridge_reconciliation':{'cash':p.cash,'debt':p.debt,'claims':p.claims,'shares':p.shares},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':reason,'baseline':base.as_private_dict()}
 if cm is None or gm is None or (not prof.full_history and ticker not in {'HONA'}):raise ValueError(f'{ticker}: history unavailable')
 margins=tuple(max(.001,float(x)) for x in (cm.low,cm.base,cm.high));growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0.,min(p.growth[2],gm.high)));rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0.,p.claims,p.shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0.,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims,'shares':p.shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(ticker)
 ok=ticker in PASS_TICKERS;reasons=() if ok else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ok else 'Low',source_cap='High',reasons=reasons);pub=prof.public_metadata();
 if not ok:pub.update({'normalization_basis':'company_history_with_named_material_transition','assumption_source_mix':'reported_history_and_finsight_policy'})
 ass={**pub,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Exact faded-cash base.','invalidation':p.invalid};base=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_25_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ok else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked history.'),),warnings=(p.warning,p.invalid),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_25_HISTORY_VERSION,'availability_type':'available' if ok else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':f,'flow_sources':flows,'annual_cash_sources':list(annual),'tax_rate_sources':list(taxsrc),'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'event_sources':_events(ticker,f,st,p),'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims,'other_equity_claim_formula':p.formula,'shares':p.shares},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
if set(P)!=set(BATCH_25_TICKERS) or PASS_TICKERS|CONDITIONAL_TICKERS|WITHHELD_TICKERS!=set(BATCH_25_TICKERS):raise RuntimeError('Batch25 mismatch')
