"""History-backed practical baselines for controlled Universe Reset Batch 23."""
from __future__ import annotations
import copy,json
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _dimension_fact,_no_preferred
from .batch_16_history import _share_point
from .batch_23 import BATCH_23_TICKERS,BATCH_23_VALUATION_DATE
from .history import build_cash_fcff_history_profile
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config

BATCH_23_HISTORY_VERSION='BATCH-23-INDUSTRIALS-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'RSG','LII'});CONDITIONAL_TICKERS=frozenset({'AME','CHRW','FDX','PWR','URI','AXON','UPS','LDOS'});WITHHELD_TICKERS=frozenset()
def _shares(w,c):
 hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;weighted:float;current:float;current_end:str;growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalidation:str;formula:str
 @property
 def shares(self):return _shares(self.weighted,self.current)
P={
'AME':Policy('post_indicor_instrumentation_faded_fcff','2026-06-30',495.446e6,2.036174e9,5e9,229.845e6,229_261_244.,'2026-07-28',(0.,.05,.08),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-Indicor instrumentation baseline. Five-year legacy cash history is finite, while the $5.0B August 3 acquisition, $1.1B acquired sales, bridge funding, and acquired cash conversion remain provisional.','Invalidate if final Indicor funding, acquired cash conversion, purchase accounting, debt, warranty claims, or shares changes materially.','$980.633M current plus $1.055541B noncurrent pre-close debt. The $5.0B reported subsequent acquisition consideration is deducted once as a conditional financing claim while reported acquired sales are added to valuation scale.'),
'CHRW':Policy('freight_brokerage_cycle_claim_adjusted_faded_fcff','2026-06-30',154.590e6,1.685017e9,0.,120.350e6,116_851_258.,'2026-07-29',(-.05,.01,.05),(.11,.095,.085),(0.,.01,.02),'Conditional Low freight-brokerage cycle baseline. Five-year cash history and current debt reconcile, while a $604M subsequent possible loss and only $155M maximum insurance recovery create a material unresolved claim range.','Invalidate if freight spreads, volumes, working capital, claim outcome/insurance, debt, interest cash, or shares changes materially.','$1.685017B reported long-term debt. The unrecognized subsequent loss is ranged at $449M/$224.5M/$0 after maximum insurance; latest annual InterestPaidNet remains a source-linked interest proxy.'),
'FDX':Policy('post_freight_separation_faded_fcff','2026-05-31',13.311e9,24.969e9,0.,239e6,236_581_188.,'2026-07-16',(-.03,.02,.05),(.11,.095,.085),(0.,.01,.02),'Conditional Low post-Freight-separation baseline. Continuing cash history and current claims are finite, while $771M separation costs, $2.5B spin funding, tariffs, leases, and post-spin allocation remain material.','Invalidate if post-spin operating scope, cash allocation, tariffs/refunds, debt/leases, pensions, or shares changes materially.','$24.969B debt/capital leases; $13.311B current cash includes the reported $2.5B spin-related cash increase and is not added again.'),
'PWR':Policy('post_acquisition_infrastructure_backlog_faded_fcff','2026-06-30',506.431e6,6.096174e9,104.001e6,152.289e6,150_343_393.,'2026-07-27',(0.,.06,.10),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-acquisition infrastructure-services baseline. Backlog cash is finite, but $930.311M H1 acquisition cash, pro-forma scale, purchase accounting, and acquired conversion remain material.','Invalidate if backlog conversion, acquired cash, purchase accounting, debt/leases, NCI, claims, or shares changes materially.','$6.096174B debt/capital leases including current maturities plus $104.001M NCI.'),
'RSG':Policy('environmental_services_route_faded_fcff','2026-06-30',107e6,14.205e9,1e6,308.451e6,306_212_978.,'2026-07-30',(0.,.04,.07),(.105,.09,.08),(.005,.015,.025),'Source-bounded environmental-services baseline. Five-year cash history, current gross debt/leases, NCI, shares, and restricted closure/self-insurance cash exclusion reconcile.','Invalidate if route pricing, landfill economics, acquisition pace, closure/environmental cash, debt/leases, NCI, or shares changes materially.','$14.205B gross debt/lease obligations plus $1M NCI; restricted closure and self-insurance cash is excluded.'),
'URI':Policy('equipment_rental_cycle_bounded_capex_fcff','2026-06-30',112e6,14.230e9,0.,62.827e6,62_242_489.,'2026-07-20',(-.05,.01,.05),(.115,.10,.09),(0.,.01,.02),'Conditional Low equipment-rental cycle baseline. Revenue, OCF, debt, and shares are reported; current fleet capex is a transparent nonzero run-rate bridge because the latest standardized annual capex tag is incomplete.','Invalidate if rental rates/utilization, fleet residuals, exact FY capex, acquisition integration, debt/leases, or shares changes materially.','$14.230B reported debt/capital leases. Operating leases remain in cash conversion; missing fleet capex is never replaced with zero.'),
'AXON':Policy('post_acquisition_public_safety_technology_faded_fcff','2026-06-30',692.533e6,1.750e9,0.,82.518e6,81_237_415.,'2026-07-31',(.02,.12,.20),(.12,.10,.09),(.01,.02,.025),'Conditional Low post-acquisition public-safety technology baseline. Current cash/securities, debt, shares, and five-year history are finite, while $551.593M H1 acquisitions, warrants, strategic investments, and claim tail remain material.','Invalidate if acquired cash conversion, warrants/convertibles, strategic securities, claims, debt, or shares changes materially.','$692.533M aggregate cash, cash equivalents, and short-term investments already includes $19.126M marketable securities and is counted once; $1.750B debt. Diluted weighted shares include current incremental warrant dilution.'),
'LII':Policy('hvac_replacement_cycle_faded_fcff','2026-06-30',52.1e6,1.5813e9,0.,34.9e6,34_560_675.,'2026-07-22',(-.03,.03,.06),(.105,.09,.08),(.005,.015,.025),'Source-bounded HVAC replacement-cycle baseline. Five-year cash history, current cash/investments, debt/capital leases, warranty reserve, zero preferred equity, and shares reconcile.','Invalidate if replacement demand, pricing, refrigerant transition, cash conversion, debt/leases, warranty claims, or shares changes materially.','$1.5813B debt/capital leases; $51.5M cash plus $0.6M short-term investments; no nonzero NCI/preferred claim.'),
'UPS':Policy('transformation_parcel_network_faded_fcff','2026-06-30',4.653e9,24.484e9,32e6,851e6,850_781_582.,'2026-07-17',(-.03,0.,.03),(.11,.095,.085),(0.,.01,.02),'Conditional Low parcel-network transformation baseline. Five-year cash history and current bridge are finite, while $933M H1 transformation costs, tariff-refund claims, pension obligations, network closures, and volume reset remain material.','Invalidate if transformation savings/costs, tariff refunds, pension funding, network volume, debt/leases, NCI, or shares changes materially.','$24.484B debt/capital leases plus $32M NCI. Pension, supplier finance, and operating leases remain in cash conversion and are not deducted twice.'),
'LDOS':Policy('post_acquisition_government_services_faded_fcff','2026-07-03',748e6,6.031e9,52e6,127e6,125_492_209.,'2026-07-28',(-.02,.04,.07),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-acquisition government-services baseline. Current backlog cash is finite, but $2.338B H1 acquisition cash, $1.652B acquired goodwill, higher debt, and integration costs make legacy history provisional.','Invalidate if acquired contract cash, integration, fixed-price execution, debt/leases, NCI, claims, or shares changes materially.','$6.031B debt/capital leases including current maturities plus $52M NCI.'),
}
POINT={
'AME':(('CashAndCashEquivalentsAtCarryingValue',495.446e6),('DebtCurrent',980.633e6),('LongTermDebtNoncurrent',1.055541e9)),
'CHRW':(('CashAndCashEquivalentsAtCarryingValue',154.590e6),('LongTermDebt',1.685017e9),('PreferredStockValue',0.)),
'FDX':(('CashAndCashEquivalentsAtCarryingValue',13.311e9),('DebtAndCapitalLeaseObligations',24.969e9),('PreferredStockValue',0.)),
'PWR':(('CashAndCashEquivalentsAtCarryingValue',506.431e6),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',6.096174e9),('MinorityInterest',104.001e6)),
'RSG':(('CashAndCashEquivalentsAtCarryingValue',107e6),('DebtLongTermAndShortTermCombinedAmountGrossAndLeaseObligation',14.205e9),('MinorityInterest',1e6),('PreferredStockValue',0.)),
'URI':(('CashAndCashEquivalentsAtCarryingValue',112e6),('DebtAndCapitalLeaseObligations',14.230e9)),
'AXON':(('CashCashEquivalentsAndShortTermInvestments',692.533e6),('DebtInstrumentCarryingAmount',1.750e9),('PreferredStockValue',0.)),
'LII':(('CashAndCashEquivalentsAtCarryingValue',51.5e6),('ShortTermInvestments',.6e6),('DebtAndCapitalLeaseObligations',1.5813e9),('PreferredStockValue',0.)),
'UPS':(('CashAndCashEquivalentsAtCarryingValue',4.653e9),('DebtAndCapitalLeaseObligations',24.484e9),('MinorityInterest',32e6)),
'LDOS':(('CashAndCashEquivalentsAtCarryingValue',748e6),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',6.031e9),('MinorityInterest',52e6)),
}
START={'AME':'2026-01-01','CHRW':'2026-01-01','FDX':'2025-06-01','PWR':'2026-01-01','RSG':'2026-01-01','URI':'2026-01-01','AXON':'2026-01-01','LII':'2026-01-01','UPS':'2026-01-01','LDOS':'2026-01-03'}
def _norm(t,sub,facts):
 if t not in {'CHRW','URI'}:return _normalizer(sub,facts)
 c=copy.deepcopy(load_concept_config())
 if t=='CHRW':c['fields']['interest_expense']['concepts'].append('InterestPaidNet')
 else:c['fields']['revenue']['concepts']=['Revenues']+c['fields']['revenue']['concepts']
 return _normalizer(sub,facts,concept_config=c)
def _ups_shares(st):
 vals=(101_432_177.,749_349_405.);rows=[]
 for value,member in zip(vals,('CommonClassAMember','CommonClassBMember')):
  rows.append(_dimension_fact(st,name='EntityCommonStockSharesOutstanding',expected=value,start=None,end='2026-07-17',member=member))
 return {'source_kind':'structural_xbrl_class_sum','accession':st['source_accession'],'period_end':'2026-07-17','unit':'xbrli:shares','components':rows,'value':sum(vals),'reported_vs_estimated':'reported_derived'}
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]];rows.append(_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=p.weighted,period_start=START[t],period_end=p.period));rows.append(_ups_shares(st) if t=='UPS' else _share_point(st,expected=p.current,end=p.current_end));rows.append(_no_preferred(st,p.period));return rows
def _uri_flows(n,st):
 annual_rev=n.annual_at_end('revenue','2025-12-31');annual_ocf=n.annual_at_end('operating_cash_flow','2025-12-31');annual_interest=n.annual_at_end('interest_expense','2025-12-31');annual_capex=n.annual_at_end('capital_expenditures','2024-12-31')
 if None in (annual_rev,annual_ocf,annual_interest,annual_capex):raise ValueError('URI annual anchors missing')
 cur_rev=_structural_flow(st,name='Revenues',start='2026-01-01',end='2026-06-30',expected=8.395e9);old_rev=_structural_flow(st,name='Revenues',start='2025-01-01',end='2025-06-30',expected=7.662e9);cur_ocf=_structural_flow(st,name='NetCashProvidedByUsedInOperatingActivities',start='2026-01-01',end='2026-06-30',expected=3.305e9);old_ocf=_structural_flow(st,name='NetCashProvidedByUsedInOperatingActivities',start='2025-01-01',end='2025-06-30',expected=2.753e9);cur_rent=_structural_flow(st,name='PaymentsToAcquirePropertySubjectToOrAvailableForOperatingLease',start='2026-01-01',end='2026-06-30',expected=2.720e9);old_rent=_structural_flow(st,name='PaymentsToAcquirePropertySubjectToOrAvailableForOperatingLease',start='2025-01-01',end='2025-06-30',expected=2.121e9);cur_other=_structural_flow(st,name='PaymentsToAcquirePropertyPlantAndEquipmentAndIntangibleAssets',start='2026-01-01',end='2026-06-30',expected=165e6);old_other=_structural_flow(st,name='PaymentsToAcquirePropertyPlantAndEquipmentAndIntangibleAssets',start='2025-01-01',end='2025-06-30',expected=182e6);cur_int=_structural_flow(st,name='InterestIncomeExpenseNonoperatingNet',start='2026-01-01',end='2026-06-30',expected=-354e6);old_int=_structural_flow(st,name='InterestIncomeExpenseNonoperatingNet',start='2025-01-01',end='2025-06-30',expected=-355e6)
 def row(field,value,sources,method):return {'field':field,'value':value,'period_end':'2026-06-30','method':method,'sources':sources}
 return {'revenue':row('revenue',annual_rev.value+8.395e9-7.662e9,[annual_rev.as_dict(),cur_rev,old_rev],'latest_fy_plus_current_h1_minus_prior_h1'),'operating_cash_flow':row('operating_cash_flow',annual_ocf.value+3.305e9-2.753e9,[annual_ocf.as_dict(),cur_ocf,old_ocf],'latest_fy_plus_current_h1_minus_prior_h1'),'capital_expenditures':row('capital_expenditures',annual_capex.value+(2.720e9+165e6)-(2.121e9+182e6),[annual_capex.as_dict(),cur_rent,cur_other,old_rent,old_other],'bounded_latest_standard_annual_plus_current_h1_minus_prior_h1'),'interest_expense':row('interest_expense',annual_interest.value-354e6+355e6,[annual_interest.as_dict(),cur_int,old_int],'latest_fy_plus_current_h1_minus_prior_h1')}
EVENT={
'AME':('August 3 Indicor acquisition',{'purchase_consideration_usd':5e9,'estimated_annual_sales_usd':1.1e9,'bridge_capacity_usd':5e9}),'CHRW':('subsequent loss contingency',{'possible_loss_usd':604e6,'insurance_recovery_maximum_usd':155e6,'deductible_usd':5e6}),'FDX':('FedEx Freight separation',{'separation_costs_usd':771e6,'spin_cash_increase_usd':2.5e9}),'PWR':('current-year infrastructure acquisitions',{'h1_acquisition_cash_usd':930.311e6,'h1_pro_forma_revenue_usd':18.134997e9}),'RSG':('ordinary route and landfill acquisitions',{'h1_acquisition_cash_usd':865e6}),'URI':('equipment-rental fleet cycle',{'h1_rental_fleet_capex_usd':2.720e9,'h1_other_capex_usd':165e6}),'AXON':('current-year technology acquisitions and warrants',{'h1_acquisition_cash_usd':551.593e6,'warrant_underlying_shares':3_016_680}),'LII':('HVAC replacement cycle and warranties',{'warranty_accrual_usd':174.6e6}),'UPS':('parcel-network transformation and tariffs',{'h1_transformation_cost_usd':933e6,'tariff_claims_submitted_usd':500e6,'tariff_claims_received_usd':200e6,'pension_obligation_usd':6.341e9}),'LDOS':('current-year government-services acquisition',{'h1_acquisition_cash_usd':2.338e9,'acquired_goodwill_usd':1.652e9})}
def _events(t,f,st):
 matter,terms=EVENT[t];rows=[{'source_kind':'controlling_filing_narrative','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':matter,'reported_terms':terms,'reported_vs_estimated':'reported_narrative'}]
 specs={'AME':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',424.484e6),'CHRW':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',78.948e6),'PWR':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',930.311e6),'RSG':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',865e6),'URI':('PaymentsToAcquirePropertySubjectToOrAvailableForOperatingLease','2026-01-01',2.720e9),'AXON':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-01',551.593e6),'UPS':('TransformationStrategyCost','2026-01-01',933e6),'LDOS':('PaymentsToAcquireBusinessesNetOfCashAcquired','2026-01-03',2.338e9)}
 if t in specs:n,s,v=specs[t];rows.append(_structural_flow(st,name=n,start=s,end=P[t].period,expected=v) if t!='UPS' else _dimension_fact(st,name=n,expected=v,start=s,end=P[t].period,member='TransformationStrategyMember'))
 if t=='FDX':rows.extend((_structural_flow(st,name='SeparationAndOtherCosts',start='2025-06-01',end='2026-05-31',expected=771e6),_point(st,name='IncreaseInCashAndCashEquivalentsDueToSpinOff',expected=2.5e9,period_end='2026-05-31')))
 if t=='AME':rows.extend((_dimension_fact(st,name='PaymentsToAcquireBusinessesNetOfCashAcquired',expected=5e9,start='2026-08-03',end='2026-08-03',member='IndicorLLCMember'),_dimension_fact(st,name='BusinessAcquisitionEstimatedAnnualSales',expected=1.1e9,start='2026-08-03',end='2026-08-03',member='IndicorLLCMember'),_dimension_fact(st,name='LineOfCreditFacilityMaximumBorrowingCapacity',expected=5e9,start=None,end='2026-06-09',member='BridgeLoanMember')))
 if t=='CHRW':rows.extend((_dimension_fact(st,name='LossContingencyEstimateOfPossibleLoss',expected=604e6,start=None,end='2026-07-23',member='SubsequentEventMember'),_dimension_fact(st,name='LossContingencyInsuranceRecoveryMaximumAmount',expected=155e6,start='2026-07-23',end='2026-07-23',member='SubsequentEventMember'),_dimension_fact(st,name='LossContingencyInsuranceDeductibleAmount',expected=5e6,start='2026-07-23',end='2026-07-23',member='SubsequentEventMember')))
 if t=='AXON':rows.append(_dimension_fact(st,name='ClassOfWarrantOrRightNumberOfSecuritiesCalledByWarrantsOrRights',expected=3_016_680.,start=None,end='2026-06-30',member='Warrant2027Member'))
 return rows
def build_batch_23_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 p=P[ticker];q=Path(source_root)/ticker;sub=json.loads((q/'submissions.json').read_text());facts=json.loads((q/'companyfacts.json').read_text());m=json.loads((q/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,sub)
 if st['source_accession']!=f['accession']:raise ValueError(ticker)
 n=_norm(ticker,sub,facts);flows=_uri_flows(n,st) if ticker=='URI' else {x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,taxsrc=_normalized_tax_rate(n)
 except ValueError:tax,taxsrc=.21,()
 if ticker=='URI':tax=.248
 if not .05<=tax<=.30:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(x) for v in flows.values() for x in v.get('sources',[])];rev=float(flows['revenue']['value']);valuation_rev=rev+(1.1e9 if ticker=='AME' else 0.);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_23_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if not prof.full_history or cm is None or gm is None:raise ValueError(f'{ticker}: history unavailable')
 margins=tuple(max(.001,float(x)) for x in (cm.low,cm.base,cm.high));growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0.,min(p.growth[2],gm.high)));claim_range=(449e6,224.5e6,0.) if ticker=='CHRW' else (p.claims,)*3;rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(valuation_rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0.,claim_range[i],p.shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0.,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claim_range[i],'shares':p.shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(ticker)
 ok=ticker in PASS_TICKERS;reasons=() if ok else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ok else 'Low',source_cap='High',reasons=reasons);public=prof.public_metadata()
 if not ok:public.update({'normalization_basis':'company_history_with_named_material_transition','assumption_source_mix':'reported_history_and_finsight_policy'})
 ass={**public,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'valuation_revenue':valuation_rev,'valuation_revenue_basis':'reported TTM plus reported Indicor annual sales' if ticker=='AME' else 'reported TTM','other_equity_claims':claim_range,'equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Exact faded-cash base.','current_reinvestment_basis':'bounded nonzero fleet-capex bridge' if ticker=='URI' else 'reported TTM','invalidation':p.invalidation};base=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_23_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ok else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked cash history.'),),warnings=(p.warning,p.invalidation),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_23_HISTORY_VERSION,'availability_type':'available' if ok else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'valuation_revenue':valuation_rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':f,'flow_sources':flows,'annual_cash_sources':list(annual),'tax_rate_sources':list(taxsrc),'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'event_sources':_events(ticker,f,st),'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claim_range,'other_equity_claim_formula':p.formula,'shares':p.shares,'operating_liability_treatment':'Operating leases, supplier finance, pensions, ordinary reserves, and working capital remain in cash conversion unless explicitly bridged.'},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
if set(P)!=set(BATCH_23_TICKERS) or PASS_TICKERS|CONDITIONAL_TICKERS|WITHHELD_TICKERS!=set(BATCH_23_TICKERS):raise RuntimeError('Batch23 mismatch')
