"""History-backed launch-first baselines for controlled Batch 10."""
from __future__ import annotations
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_conditional_estimates import five_year_fcff_dcf
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_10 import BATCH_10_TICKERS,BATCH_10_VALUATION_DATE
from .history import HISTORY_POLICY_VERSION,build_cash_fcff_history_profile
from .reliability import assess_reliability

BATCH_10_HISTORY_VERSION='BATCH-10-HISTORY-LAUNCH-FIRST-1.0'
PASS_TICKERS=frozenset({'HSY','HRL','KR','PEP','PG','WMT'})
def _shares(base):return (base*1.025,base,base*.975)
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;shares:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalidation:str
P={
'HSY':Policy('dual_class_confectionery_cash_fcff','2026-06-28',791_213_000.,5_610_680_000.,0.,_shares(203_250_000.),(.105,.09,.08),(0,.015,.02),'History-backed confectionery cash-FCFF. Cocoa volatility and both voting classes remain visible, while the diluted denominator reflects Class B conversion.','Invalidate if cocoa working capital, acquisitions, debt, class conversion, or diluted shares changes.'),
'HRL':Policy('packaged_protein_cash_fcff','2026-04-26',859_857_000.,2_856_339_000.,14_556_000.,_shares(550_810_000.),(.105,.09,.08),(0,.015,.02),'History-backed packaged-protein cash-FCFF with marketable securities, total debt, finance leases, and NCI reconciled once.','Invalidate if protein margins, investments, debt/leases, NCI, or diluted shares changes.'),
'KMB':Policy('pre_transaction_consumer_products_cash_fcff','2026-06-30',1_363_000_000.,7_882_000_000.,146_000_000.,_shares(333_300_000.),(.115,.10,.09),(0,.01,.02),'Conditional Low pre-transaction estimate. IFP is annualized inside the current company snapshot; the pending Kenvue acquisition and subsequent IFP closing are not forecast as completed.','Invalidate on Kenvue or IFP closing-term changes, final debt/cash/share allocation, continuing cash separation, or dilution.'),
'KR':Policy('food_retail_cash_fcff','2026-05-23',2_873_000_000.,16_995_000_000.,6_000_000.,_shares(615_000_000.),(.105,.09,.08),(0,.015,.02),'History-backed food-retail cash-FCFF. Current and noncurrent debt include finance-lease obligations once; the terminated Albertsons transaction is not treated as a continuing business combination.','Invalidate if retail cash conversion, opioid/merger obligations, debt, leases, NCI, or shares changes.'),
'MKC':Policy('post_mexico_consolidation_cash_fcff','2026-05-31',331_200_000.,5_028_500_000.,577_700_000.,_shares(269_300_000.),(.115,.10,.09),(0,.01,.02),'Conditional Low estimate. McCormick de Mexico became consolidated in 2026 after the additional ownership acquisition, while the latest $95M annual finance-lease claim is conservatively carried to the current bridge.','Invalidate if Mexico consolidation, NCI, purchase accounting, debt/leases, cash conversion, or shares changes.'),
'PEP':Policy('global_snacks_beverages_cash_fcff','2026-06-13',10_716_000_000.,53_214_000_000.,172_000_000.,_shares(1_370_000_000.),(.105,.09,.08),(0,.015,.02),'History-backed global snacks-and-beverages cash-FCFF with short investments, current debt, long-term debt, and NCI reconciled.','Invalidate if acquisition integration, cash/investments, debt, NCI, supplier finance, or shares changes.'),
'PG':Policy('global_consumer_products_cash_fcff','2026-06-30',9_942_000_000.,34_138_000_000.,230_000_000.,_shares(2_422_500_000.),(.105,.09,.08),(0,.015,.02),'History-backed consumer-products cash-FCFF with current/noncurrent debt and NCI included once; the diluted denominator already includes assumed preferred conversion.','Invalidate if preferred conversion treatment, debt, supplier finance, cash, NCI, or diluted shares changes.'),
'SJM':Policy('post_impairment_packaged_food_cash_fcff','2026-04-30',58_600_000.,6_974_100_000.,0.,_shares(106_700_000.),(.115,.10,.09),(0,.01,.02),'Conditional Low estimate. Hostess/Sweet Baked Snacks impairment, divestitures, restructuring, leverage, and the governed loss-year tax policy remain material.','Invalidate if impairment/divestiture cash, tax normalization, debt/leases, supplier finance, or shares changes.'),
'TSN':Policy('protein_cycle_normalized_cash_fcff','2026-06-27',740_000_000.,8_006_000_000.,106_000_000.,_shares(354_000_000.),(.115,.10,.09),(0,.01,.02),'Conditional Low protein-cycle estimate. Beef, pork, chicken, network optimization, impairments, and dual-class conversion remain material.','Invalidate if protein-cycle cash, restructuring/impairment, debt, NCI, or Class A/Class B shares changes.'),
'WMT':Policy('global_retail_cash_fcff','2026-04-30',10_729_000_000.,58_129_000_000.,6_645_000_000.,_shares(7_999_000_000.),(.105,.09,.08),(0,.015,.02),'History-backed global-retail cash-FCFF with short borrowings, debt, finance leases, NCI, and redeemable NCI included once.','Invalidate if retail cash conversion, debt/leases, NCI, supplier finance, or diluted shares changes.'),
}

def _dim_duration(st,name,expected,start,end,member):
 rows=[r for r in st['facts'] if r.get('local_name')==name and r.get('period_start')==start and r.get('period_end')==end and isinstance(r.get('value'),(int,float)) and float(r['value'])==expected and any(member in str(v) for _,v in (r.get('dimensions') or []))]
 if not rows:raise ValueError(f'{name}/{member}: expected {expected} absent')
 r=rows[0];return {'source_kind':'structural_xbrl','accession':st['source_accession'],'period_start':start,'period_end':end,'concept':r.get('qname'),'dimensions':r.get('dimensions'),'unit':r.get('unit'),'value':expected,'reported_vs_estimated':'reported'}
def _dim_point(st,name,expected,end,member):
 rows=[r for r in st['facts'] if r.get('local_name')==name and r.get('period_start') is None and r.get('period_end')==end and isinstance(r.get('value'),(int,float)) and float(r['value'])==expected and any(member in str(v) for _,v in (r.get('dimensions') or []))]
 if not rows:raise ValueError(f'{name}/{member}: expected {expected} absent')
 r=rows[0];return {'source_kind':'structural_xbrl','accession':st['source_accession'],'period_end':end,'concept':r.get('qname'),'dimensions':r.get('dimensions'),'unit':r.get('unit'),'value':expected,'reported_vs_estimated':'reported'}
def _no_preferred(st,end):
 names=('PreferredStockValue','PreferredStockValueOutstanding','TemporaryEquityCarryingAmount','TemporaryEquityCarryingAmountIncludingPortionAttributableToNoncontrollingInterests')
 rows=[r for r in st['facts'] if r.get('local_name') in names and r.get('period_start') is None and r.get('period_end')==end and isinstance(r.get('value'),(int,float)) and float(r['value'])!=0]
 if rows:raise ValueError('unreconciled preferred or temporary equity')
 return {'source_kind':'controlling_filing_structure','accession':st['source_accession'],'period_end':end,'field':'preferred_and_temporary_equity','reported_vs_estimated':'source_proven_absent_or_zero','checked_concepts':list(names)}
def _bridge(t,st,p):
 specs={
 'HSY':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',791_213_000.),('ShortTermBorrowings',421_545_000.),('LongTermDebt',5_189_135_000.),('FinanceLeaseLiability',75_541_000.),('PreferredStockValue',0.)),
 'HRL':(('CashAndCashEquivalentsAtCarryingValue',826_750_000.),('MarketableSecuritiesCurrent',33_107_000.),('LongTermDebtCurrent',505_335_000.),('LongTermDebtAndCapitalLeaseObligations',2_351_004_000.),('FinanceLeaseLiability',20_444_000.),('MinorityInterest',14_556_000.),('PreferredStockValue',0.)),
 'KMB':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations',1_363_000_000.),('DebtCurrent',43_000_000.),('LongTermDebtAndCapitalLeaseObligations',6_474_000_000.),('DisposalGroupIncludingDiscontinuedOperationDebtCurrent',8_000_000.),('DisposalGroupIncludingDiscontinuedOperationLongTermDebt',1_357_000_000.),('MinorityInterest',124_000_000.),('RedeemableCommonAndPreferredSecuritiesOfSubsidiaries',22_000_000.),('PreferredStockValue',0.)),
 'KR':(('CashAndCashEquivalentsAtCarryingValue',2_873_000_000.),('LongTermDebtAndFinanceLeaseCurrent',1_264_000_000.),('LongTermDebtAndFinanceLease',15_731_000_000.),('MinorityInterest',6_000_000.)),
 'MKC':(('CashAndCashEquivalentsAtCarryingValue',331_200_000.),('ShortTermBorrowings',1_326_600_000.),('LongTermDebt',3_606_900_000.),('MinorityInterest',577_700_000.)),
 'PEP':(('CashAndCashEquivalentsAtCarryingValue',10_251_000_000.),('ShortTermInvestments',465_000_000.),('ShortTermBorrowings',10_602_000_000.),('LongTermDebtAndCapitalLeaseObligations',42_612_000_000.),('MinorityInterest',172_000_000.)),
 'PG':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',9_942_000_000.),('DebtCurrent',11_296_000_000.),('LongTermDebtNoncurrent',22_842_000_000.),('MinorityInterest',230_000_000.)),
 'SJM':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',58_600_000.),('ShortTermBorrowings',420_900_000.),('LongTermDebtCurrent',150_000_000.),('LongTermDebtNoncurrent',6_392_800_000.),('FinanceLeaseLiability',10_400_000.),('PreferredStockValueOutstanding',0.)),
 'TSN':(('CashAndCashEquivalentsAtCarryingValue',740_000_000.),('DebtAndCapitalLeaseObligations',8_006_000_000.),('MinorityInterest',106_000_000.)),
 'WMT':(('CashAndCashEquivalentsAtCarryingValue',10_729_000_000.),('ShortTermBorrowings',10_673_000_000.),('DebtLongtermAndShorttermCombinedAmount',40_783_000_000.),('FinanceLeaseLiabilityCurrent',851_000_000.),('FinanceLeaseLiabilityNoncurrent',5_822_000_000.),('MinorityInterest',6_352_000_000.),('RedeemableNoncontrollingInterestEquityCarryingAmount',293_000_000.)),
 }
 rows=[]
 for name,value in specs[t]:
  if t=='KMB' and name in {'DisposalGroupIncludingDiscontinuedOperationDebtCurrent','DisposalGroupIncludingDiscontinuedOperationLongTermDebt'}:rows.append(_dim_point(st,name,value,p.period,'InternationalFamilyCareAndProfessionalBusinessMember'))
  else:rows.append(_point(st,name=name,expected=value,period_end=p.period))
 starts={'HRL':'2025-10-27','KMB':'2026-01-01','KR':'2026-02-01','MKC':'2025-12-01','PEP':'2025-12-28','PG':'2025-07-01','TSN':'2025-09-28','WMT':'2026-02-01'}
 if t=='HSY':rows.append(_dim_duration(st,'WeightedAverageNumberOfDilutedSharesOutstanding',p.shares[1],'2026-01-01',p.period,'CommonStockMember'))
 elif t=='SJM':rows.append(_dim_duration(st,'WeightedAverageNumberOfDilutedSharesOutstanding',p.shares[1],'2025-05-01',p.period,'TwoClassMethodMember'))
 else:rows.append(_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=p.shares[1],period_start=starts[t],period_end=p.period))
 if t=='PG':rows.append(_dim_point(st,'PreferredStockValue',756_000_000.,p.period,'PreferredClassAMember'))
 else:rows.append(_no_preferred(st,p.period))
 if t=='KMB':
  rows.extend((_dim_duration(st,'DisposalGroupIncludingDiscontinuedOperationRevenue',1_642_000_000.,'2026-01-01',p.period,'InternationalFamilyCareAndProfessionalBusinessMember'),_dim_point(st,'DisposalGroupIncludingDiscontinuedOperationConsideration',1_700_000_000.,p.period,'InternationalFamilyCareAndProfessionalBusinessMember'),_dim_duration(st,'BusinessCombinationPriceOfAcquisitionExpected',6_700_000_000.,'2025-11-02','2025-11-02','KenvueAcquisitionMember'),_dim_point(st,'BusinessCombinationCommonStockIssuedExpected',280_000_000.,'2025-11-02','KenvueAcquisitionMember'),{'source_kind':'governed_policy','field':'IFP_revenue_annualization','period_end':p.period,'reported_h1':1_642_000_000.,'annualized_value':3_284_000_000.,'reported_vs_estimated':'reported_h1_annualized','basis':'Current H1 IFP revenue is doubled only for the pre-closing whole-company snapshot; Kenvue is not forecast as closed.'}))
 if t=='MKC':rows.append({'source_kind':'structural_xbrl_event','accession':st['source_accession'],'period_end':p.period,'field':'Mexico_consolidation_NCI','value':577_700_000.,'reported_vs_estimated':'reported','basis':'The additional ownership acquisition consolidated McCormick de Mexico and recognized $504.3M fair-value NCI; prior equity-method history is not fully comparable.'})
 return rows

def _mkc_carried_finance_lease(facts):
 rows=facts['facts']['us-gaap']['FinanceLeaseLiability']['units']['USD'];matches=[r for r in rows if r.get('end')=='2025-11-30' and r.get('val')==95_000_000 and r.get('accn')=='0000063754-26-000037' and r.get('filed')=='2026-01-22' and r.get('form')=='10-K']
 if not matches:raise ValueError('MKC carried finance lease source absent')
 return {'source_kind':'companyfacts_carried_annual_point','accession':'0000063754-26-000037','filed':'2026-01-22','form':'10-K','period_end':'2025-11-30','concept':'us-gaap:FinanceLeaseLiability','unit':'USD','value':95_000_000.,'reported_vs_estimated':'reported_annual_carried_to_current_bridge','basis':'The current 10-Q omits a finance-lease point; the latest cutoff-safe annual carrying amount is conservatively retained without growth reduction.'}

def build_batch_10_history_result(*,ticker,source_root:Path,structural_root:Path):
 p=P[ticker];packet=Path(source_root)/ticker;sub=json.loads((packet/'submissions.json').read_text());facts=json.loads((packet/'companyfacts.json').read_text());manifest=json.loads((packet/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());filing=_controlling(manifest,sub)
 if st['source_accession']!=filing['accession'] or filing['period_end']!=p.period:raise ValueError(f'{ticker}: controlling source mismatch')
 if ticker=='KMB':
  reason='Withheld. The IFP transaction closed after quarter-end but before the valuation date, while the larger Kenvue cash-and-stock acquisition remained pending. The filing does not supply one post-IFP, post-Kenvue cash-flow and capital-structure object.';baseline=BaselineValuation(ticker='KMB',method='unavailable_transaction_state',method_version=BATCH_10_HISTORY_VERSION,low=None,base=None,high=None,confidence=None,availability_type=AvailabilityType.NOT_AVAILABLE,warnings=(reason,));return {'ticker':'KMB','method':'unavailable_transaction_state','model_version':BATCH_10_HISTORY_VERSION,'availability_type':'not_available','scenario_rows':[],'scenario_range':{'low':None,'base':None,'high':None},'reported_inputs':{},'governed_assumptions':{'history_policy_version':HISTORY_POLICY_VERSION,'history_years_used':0,'normalization_basis':'post_IFP_post_Kenvue_economic_object_unavailable','assumption_source_mix':'reported_event_terms_without_combined_cash_flow','invalidation':'Revalue after a filed post-IFP continuing cash bridge and final Kenvue closing or termination capital structure.'},'history_reliability':None,'source_ledger':{'controlling_filing':filing,'event_bridge_sources':_bridge(ticker,st,p),'known_event_state':{'IFP_closing_date':'2026-07-01','IFP_cash_consideration':1_700_000_000.,'Kenvue_status':'pending','Kenvue_expected_cash_consideration':6_700_000_000.,'Kenvue_expected_incremental_shares':280_000_000.},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':reason,'baseline':baseline.as_private_dict()}
 n=_normalizer(sub,facts);flows={f:n.ttm_flow(f) for f in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')};tax=.21 if ticker=='SJM' else _normalized_tax_rate(n)[0];current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);_,_,annual_sources=_annual_cash_with_losses(n);sources=[]
 for flow in flows.values():sources.extend(dict(row) for row in flow.get('sources',[]) if isinstance(row,dict))
 revenue=float(flows['revenue']['value'])
 if ticker=='KMB':
  revenue+=3_284_000_000.;sources.append({'source_kind':'structural_xbrl_and_governed_policy','accession':st['source_accession'],'period_start':'2026-01-01','period_end':p.period,'field':'IFP_revenue','reported_h1':1_642_000_000.,'annualized_value':3_284_000_000.,'reported_vs_estimated':'reported_h1_annualized'})
 profile=build_cash_fcff_history_profile(annual_cash_states=annual_sources,ttm_revenue=revenue,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_10_VALUATION_DATE);cash=profile.metric('cash_conversion_margin');hist_growth=profile.metric('revenue_growth')
 if not profile.full_history or cash is None or hist_growth is None:raise ValueError(f'{ticker}: history insufficient')
 margins=(max(.001,cash.low),max(.001,cash.base),max(.001,cash.high));growth=(max(-.05,min(.03,hist_growth.low)),max(-.03,min(.04,hist_growth.base)),max(0.,min(.05,hist_growth.high)));rows=[]
 for i,name in enumerate(('bear','base','bull')):
  raw=five_year_fcff_dcf(revenue=revenue,fcff_margin=margins[i],growth=growth[i],wacc=p.wacc[i],terminal_growth=p.terminal[i],cash_and_investments=p.cash,debt=p.debt,noncontrolling_interests=p.claims,shares=p.shares[i]);value=max(0.,float(raw['value_per_share']));rows.append({'name':name,'conditional_value_per_share':value,'raw_value_per_share':float(raw['value_per_share']),'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'shares':p.shares[i],'limited_liability_floor_applied':value==0 and float(raw['value_per_share'])<0})
 scenario={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']};is_pass=ticker in PASS_TICKERS
 if not(0<=scenario['low']<=scenario['base']<=scenario['high']) or scenario['base']<=0:raise ValueError(f'{ticker}: invalid range')
 reasons=() if is_pass else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');reliability=assess_reliability(accounting_low=scenario['base'],accounting_base=scenario['base'],accounting_high=scenario['base'],scenario_low=scenario['low'],scenario_base=scenario['base'],scenario_high=scenario['high'],model_cap='High' if is_pass else 'Low',source_cap='High',reasons=reasons);pub=profile.public_metadata()
 if not is_pass:pub.update({'normalization_basis':'company_history_with_material_event_override','assumption_source_mix':'reported_history_and_finsight_policy'})
 assumptions={**pub,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'equity_floor_basis':'limited-liability floor after negative residual' if scenario['low']==0 else 'not applied','calculator_calibration':'Calculator is calibrated to the published base; private history and bridge remain fixed.','invalidation':p.invalidation}
 baseline=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_10_HISTORY_VERSION,low=scenario['low'],base=scenario['base'],high=scenario['high'],confidence=reliability.label,availability_type=AvailabilityType.AVAILABLE if is_pass else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(profile.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked annual history supplies cash-conversion and growth states.'),BaselineAssumption('reported anchors',str({k:v['value'] for k,v in flows.items()}),AssumptionClassification.REPORTED,'Cutoff-safe filing facts anchor current cash generation.'),BaselineAssumption('scenario policy',str(assumptions),AssumptionClassification.FINSIGHT_ASSUMPTION,'Discount rates, terminal growth, shares, and named dependencies remain transparent assumptions.')),warnings=(p.warning,p.invalidation),confidence_reasons=tuple(reliability.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 bridge_sources=_bridge(ticker,st,p)
 if ticker=='MKC':bridge_sources.append(_mkc_carried_finance_lease(facts))
 share_treatment={'HSY':'203.25M diluted common shares are the as-converted economic denominator; the separate 54.614M Class B fact is not added again.','MKC':'269.3M diluted shares cover voting and non-voting common economics.','PG':'2,422.5M diluted shares include 68.3M assumed preferred-conversion shares.','TSN':'354M diluted shares cover Class A plus the one-for-one convertible Class B economics.'}.get(ticker,'Current diluted weighted-average shares are used once with a ±2.5% denominator range.')
 affiliate_treatment={'HSY':'$174.834M affiliate fair-value diagnostic is not treated as excess cash; distributed affiliate cash remains in reported OCF.','HRL':'$568.549M equity-affiliate investment is not treated as excess cash; only $33.107M current marketable securities are added.','PEP':'$2.180B equity-method affiliates remain part of operating cash conversion and are not added again as excess cash.'}.get(ticker,'No separate noncash affiliate investment is added to excess cash.')
 debt_scope={'HSY':'$5.189135B total long-term debt already includes $75.541M finance leases; only $421.545M short-term debt is added.','MKC':'$95M latest annual finance lease is carried in addition to current short-term and long-term debt.','KR':'$1.264B current plus $15.731B noncurrent debt already include finance leases.'}.get(ticker,'Current debt and any separate finance lease claims are reconciled once.')
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_10_HISTORY_VERSION,'availability_type':baseline.availability_type.value,'scenario_rows':rows,'scenario_range':scenario,'reported_inputs':{'ttm_revenue':flows['revenue']['value'],'valuation_revenue':revenue,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_capex':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':assumptions,'history_reliability':reliability.as_dict(),'source_ledger':{'controlling_filing':filing,'flow_sources':flows,'company_history_profile':profile.as_private_dict(),'bridge_sources':bridge_sources,'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'debt_scope':debt_scope,'preferred_nci_and_redeemable_claims':p.claims,'preferred_treatment':'PG diluted shares include 68.3M assumed-conversion shares, so its $756M preferred carrying value is not subtracted again.' if ticker=='PG' else 'Any reported preferred or temporary-equity claim is included once or source-proven zero.','share_treatment':share_treatment,'affiliate_investment_treatment':affiliate_treatment,'supplier_finance_and_operating_leases':'Remain operating in cash conversion and are not subtracted again.'},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':baseline.as_private_dict()}
if set(P)!=set(BATCH_10_TICKERS):raise RuntimeError('Batch 10 policy denominator mismatch')
