"""History-backed practical baselines for controlled Universe Reset Batch 27."""
from __future__ import annotations
import copy,json
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_05_launch_first import _source_proven_no_debt
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _no_preferred
from .batch_16_history import _share_point
from .batch_27 import BATCH_27_TICKERS,BATCH_27_VALUATION_DATE
from .history import build_cash_fcff_history_profile
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config
BATCH_27_HISTORY_VERSION='BATCH-27-TECHNOLOGY-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'TER','TXN','LRCX','MU','IT','ADSK'});CONDITIONAL_TICKERS=frozenset({'KLAC','ADBE','COHR','FLEX'});WITHHELD_TICKERS=frozenset()
def _shares(w,c):hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;shares:tuple[float,float,float];growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalid:str;formula:str
P={
'TER':Policy('semiconductor_test_robotics_cycle_faded_fcff','2026-06-28',517.103e6,0.,36.151e6,_shares(157.664e6,156_340_750.),(-.04,.03,.07),(.11,.095,.085),(0.,.01,.02),'Source-bounded semiconductor-test and robotics baseline. Five-year cash history, current cash/AFS securities, debt absence, NCI, warranties, ordinary-sized acquisitions, and shares reconcile.','Invalidate if semiconductor-test/robotics demand, acquisition conversion, warranties, securities, debt absence, NCI, or shares changes.','$349.538M cash + $5.291M current and $162.274M noncurrent AFS securities; no interest-bearing debt; $36.151M NCI. Equity-method investments remain inside operating economics and are not added as cash.'),
'TXN':Policy('fab_investment_semiconductor_faded_fcff','2026-06-30',7.016e9,14.052e9,0.,_shares(917e6,913_247_686.),(-.03,.02,.05),(.105,.09,.08),(.005,.015,.025),'Source-bounded semiconductor/fab-investment baseline. Five-year cash history, current cash/investments, debt, preferred absence, fab capex, and shares reconcile; the investment cycle is ranged rather than treated as an unbounded event.','Invalidate if fab capex, semiconductor demand, government incentives, cash conversion, investments, debt, or shares changes.','$3.660B cash + $3.341B short-term and $15M long-term investments; $1.149B current and $12.903B noncurrent debt. Maturity schedule slices are not added to investments.'),
'KLAC':Policy('purchase_commitment_process_control_faded_fcff','2026-06-30',4.902408e9,5.887415e9,0.,_shares(1_319_633_000.,1_306_546_783.),(-.05,.03,.07),(.105,.09,.08),(.005,.015,.025),'Conditional Low semiconductor process-control baseline. Five-year cash history and the cash/debt/share bridge reconcile, while the $5.970B purchase commitment—up from $2.420B—requires explicit three/five/eight-year cash timing reserves.','Invalidate if purchase-commitment timing or scope, process-control demand, cash conversion, securities, debt, or split-adjusted shares changes.','$1.649842B cash + $3.252566B complete AFS/equity securities fair value; $5.887415B debt. The $5.970B commitment is modeled as equal annual payments over 3/5/8 years and deducted at its scenario-specific present value.'),
'LRCX':Policy('wafer_fabrication_equipment_faded_fcff','2026-06-28',5.579171e9,3.730490e9,0.,_shares(1_261_102_000.,1_251_321_000.),(-.05,.03,.07),(.105,.09,.08),(.005,.015,.025),'Source-bounded wafer-fabrication equipment baseline. Five-year cash history, productive-assets capex, current unrestricted cash, debt/capital leases, preferred absence, warranties, and post-split shares reconcile.','Invalidate if wafer-fab demand, capex, warranties, cash, debt/leases, or split-adjusted shares changes.','$5.579171B unrestricted cash; $3.730490B debt/capital leases. $18.772M restricted cash is excluded and operating leases are not deducted twice.'),
'MU':Policy('memory_cycle_normalized_faded_fcff','2026-05-28',30.128e9,5.722e9,6.914e9,_shares(1.142e9,1_129_393_151.),(-.10,.02,.08),(.12,.105,.095),(0.,.01,.02),'Source-bounded normalized memory-cycle baseline. Five-year history includes the loss year and current AI-memory upcycle; cash/AFS securities, debt/capital leases, the full current unpaid-capex liability, and shares reconcile without treating peak current cash as permanent.','Invalidate if memory pricing, AI demand, fab capex/payables, cash conversion, securities, debt/leases, or shares changes.','$30.128B cash/AFS aggregate; $5.722B debt/capital leases; $6.914B reported current PP&E payable deducted once. The $2.670B finance-lease fact is a debt subset and is not deducted again.'),
'IT':Policy('recurring_information_services_faded_fcff','2026-06-30',1.488706e9,2.979281e9,0.,_shares(68.288e6,63_148_976.),(-.02,.03,.06),(.105,.09,.08),(.005,.015,.025),'Source-bounded recurring information-services baseline. Five-year cash history, structurally current capital-improvement lineage, cash, debt, preferred absence, leases, and shares reconcile; negative book equity is not substituted for operating value.','Invalidate if subscription/contract value, cash conversion, capital improvements, debt, leases, or shares changes.','$1.488706B cash; $2.979281B debt. Operating leases stay inside operating cash conversion.'),
'ADSK':Policy('subscription_design_software_faded_fcff','2026-04-30',3.309e9,2.5e9,0.,_shares(212e6,211e6),(0.,.06,.10),(.11,.095,.085),(.01,.02,.025),'Source-bounded subscription design-software baseline. Four-year cash history, cash/marketable securities, debt, diluted shares, SBC, and ordinary-sized acquisition/restructuring cash reconcile.','Invalidate if subscription growth, SBC/dilution, cash conversion, marketable securities, debt, acquisitions, or shares changes.','$2.671B cash + $253M current and $385M noncurrent marketable securities; $2.5B total long-term debt. The broader $2.559B investments aggregate is not added again.'),
'ADBE':Policy('post_acquisition_creative_software_faded_fcff','2026-05-29',5.626e9,6.645e9,0.,_shares(406.6e6,397.5e6),(.02,.07,.11),(.11,.095,.085),(.01,.02,.025),'Conditional Low post-acquisition software baseline. Five-year cash history is finite, while $1.560B of first-half acquisition cash, acquired conversion, goodwill, integration, SBC, debt, and dilution remain material.','Invalidate if acquired cash conversion, purchase accounting, AI/subscription growth, SBC/dilution, debt, or shares changes.','$5.626B cash plus short-term investments aggregate counted once; $1.843B current + $4.802B long-term debt. Antidilutive awards remain a sensitivity rather than invented shares.'),
'COHR':Policy('post_acquisition_optical_cycle_faded_fcff','2026-06-30',1.987018e9,3.257482e9,334.705e6,_shares(195.387e6,195_832_246.),(-.08,.02,.08),(.12,.105,.095),(0.,.01,.02),'Conditional Low post-acquisition optical-components baseline. Five-year history is finite, while current post-capex cash is negative and acquisition stock, converted preferred dilution, integration, restructuring, NCI, and optical-cycle normalization remain material. The bear state explicitly carries the current negative-cash gap to a limited-liability floor.','Invalidate if post-acquisition cash conversion, preferred-conversion treatment, capex, restructuring, debt, NCI, supplier finance, or shares changes.','$1.162018B cash + $825M short-term investments; $3.257482B debt including finance leases; $334.705M NCI. Bear claims add the exact gap between normalized positive cash and current negative cash; current temporary/preferred equity is source-proven zero.'),
'FLEX':Policy('post_acquisition_ems_working_capital_faded_fcff','2026-06-26',2.840e9,5.240e9,0.,_shares(374e6,369_402_978.),(-.04,.03,.07),(.11,.095,.085),(0.,.01,.02),'Conditional Low post-acquisition EMS baseline. Five-year cash history is finite, while $1.134B acquisition cash, $473M acquired goodwill, debt issuance/maturities, acquired conversion, and EMS working capital remain material.','Invalidate if acquired conversion, purchase accounting, working capital, supplier finance, debt/refinancing, or shares changes.','$2.840B cash; $5.240B debt carrying amount. $2.349B due within 12 months is a maturity subset, not additional debt; supplier finance remains operating.'),
}
POINT={
'TER':(('CashAndCashEquivalentsAtCarryingValue',349.538e6),('AvailableForSaleDebtAndEquitySecuritiesCurrent',5.291e6),('AvailableForSaleDebtAndEquitySecuritiesNonCurrent',162.274e6),('MinorityInterest',36.151e6)),
'TXN':(('CashAndCashEquivalentsAtCarryingValue',3.660e9),('ShortTermInvestments',3.341e9),('LongTermInvestments',15e6),('LongTermDebtCurrent',1.149e9),('LongTermDebtNoncurrent',12.903e9),('PreferredStockValue',0.)),
'KLAC':(('CashAndCashEquivalentsAtCarryingValue',1.649842e9),('DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue',3.252566e9),('DebtLongtermAndShorttermCombinedAmount',5.887415e9),('PreferredStockValue',0.)),
'LRCX':(('CashAndCashEquivalentsAtCarryingValue',5.579171e9),('LongTermDebtAndCapitalLeaseObligations',3.730490e9),('PreferredStockValue',0.)),
'MU':(('CashCashEquivalentsandAvailableforSaleDebtSecurities',30.128e9),('DebtAndCapitalLeaseObligations',5.722e9),('PropertyPlantAndEquipmentPayableCurrent',6.914e9)),
'IT':(('CashAndCashEquivalentsAtCarryingValue',1.488706e9),('DebtLongtermAndShorttermCombinedAmount',2.979281e9),('PreferredStockValue',0.)),
'ADSK':(('CashAndCashEquivalentsAtCarryingValue',2.671e9),('MarketableSecuritiesCurrent',253e6),('MarketableSecuritiesNoncurrent',385e6),('LongTermDebt',2.5e9)),
'ADBE':(('CashCashEquivalentsAndShortTermInvestments',5.626e9),('DebtCurrent',1.843e9),('LongTermDebt',4.802e9),('PreferredStockValue',0.)),
'COHR':(('CashAndCashEquivalentsAtCarryingValue',1.162018e9),('ShortTermInvestments',825e6),('DebtInstrumentCarryingAmount',3.257482e9),('MinorityInterest',334.705e6),('TemporaryEquityCarryingAmountAttributableToParent',0.)),
'FLEX':(('CashAndCashEquivalentsAtCarryingValue',2.840e9),('DebtInstrumentCarryingAmount',5.240e9),('BusinessCombinationContingentConsiderationLiability',0.)),}
START={'TER':'2026-01-01','TXN':'2026-01-01','KLAC':'2025-07-01','LRCX':'2025-06-30','MU':'2025-08-29','IT':'2026-01-01','ADSK':'2026-02-01','ADBE':'2025-11-29','COHR':'2025-07-01','FLEX':'2026-04-01'}
WEIGHTED={'TER':157.664e6,'TXN':917e6,'KLAC':1_319_633_000.,'LRCX':1_261_102_000.,'MU':1.142e9,'IT':68.288e6,'ADSK':212e6,'ADBE':406.6e6,'COHR':195.387e6,'FLEX':374e6}
CURRENT={'TER':156_340_750.,'TXN':913_247_686.,'KLAC':1_306_546_783.,'LRCX':1_251_321_000.,'MU':1_129_393_151.,'IT':63_148_976.,'ADSK':211e6,'ADBE':397.5e6,'COHR':195_832_246.,'FLEX':369_402_978.}
END={'TER':'2026-07-27','TXN':'2026-07-15','KLAC':'2026-08-03','LRCX':'2026-08-04','MU':'2026-06-17','IT':'2026-07-31','ADSK':'2026-05-21','ADBE':'2026-06-11','COHR':'2026-08-10','FLEX':'2026-07-24'}
def _norm(t,sub,facts):
 if t not in {'TXN','IT','COHR'}:return _normalizer(sub,facts)
 c=copy.deepcopy(load_concept_config());field,concept={'TXN':('interest_expense','InterestAndDebtExpense'),'IT':('capital_expenditures','PaymentsForCapitalImprovements'),'COHR':('interest_expense','InterestExpenseOperating')}[t];c['fields'][field]['concepts']=[concept];return _normalizer(sub,facts,concept_config=c)
def _fact(st,name,value,start,end):
 rows=[r for r in st['facts'] if r.get('local_name')==name and r.get('period_start')==start and r.get('period_end')==end and not r.get('dimensions') and isinstance(r.get('value'),(int,float)) and float(r['value'])==value]
 if not rows:raise ValueError(f'{name}={value} absent')
 r=rows[0];return {'source_kind':'structural_xbrl','accession':st['source_accession'],'filed':st.get('filed_date'),'period_start':start,'period_end':end,'concept':r.get('qname'),'unit':r.get('unit'),'value':value,'reported_vs_estimated':'reported'}
def _cf_point(facts,concept,accession,end,value):
 rows=[r for r in facts['facts']['us-gaap'][concept]['units']['USD'] if r.get('accn')==accession and r.get('end')==end and r.get('start') is None and isinstance(r.get('val'),(int,float)) and float(r['val'])==value]
 if not rows:raise ValueError(f'{concept} prior point absent')
 r=rows[0];return {'source_kind':'companyfacts','accession':accession,'filed':r.get('filed'),'form':r.get('form'),'period_end':end,'concept':f'us-gaap:{concept}','unit':'USD','value':value,'reported_vs_estimated':'reported'}
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]];rows.extend((_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=WEIGHTED[t],period_start=START[t],period_end=p.period),_share_point(st,expected=CURRENT[t],end=END[t]),_no_preferred(st,p.period)))
 if t=='TER':rows.append(_source_proven_no_debt(st,period_end=p.period))
 return rows
def _events(t,f,st,p,facts):
 rows=[{'source_kind':'controlling_filing_narrative','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':p.warning,'reported_vs_estimated':'reported_narrative'}]
 specs={'TER':(('PaymentsToAcquireBusinessesNetOfCashAcquired',165.611e6,'2026-01-01','2026-06-28'),('GoodwillAcquiredDuringPeriod',153.939e6,'2026-01-01','2026-06-28')),'KLAC':(('PurchaseCommitmentRemainingMinimumAmountCommitted',5.970e9,None,'2026-06-30'),),'ADSK':(('PaymentsToAcquireBusinessesNetOfCashAcquired',55e6,'2026-02-01','2026-04-30'),),'ADBE':(('PaymentsToAcquireBusinessesNetOfCashAcquired',1.560e9,'2025-11-29','2026-05-29'),),'COHR':(('StockIssuedDuringPeriodValueAcquisitions',2.506885e9,'2025-07-01','2026-06-30'),('IncrementalCommonSharesAttributableToConversionOfPreferredStock',12.419e6,'2025-07-01','2026-06-30')),'FLEX':(('PaymentsToAcquireBusinessesNetOfCashAcquired',1.134e9,'2026-04-01','2026-06-26'),('GoodwillAcquiredDuringPeriod',473e6,'2026-04-01','2026-06-26'),('SupplierFinanceProgramObligation',134e6,None,'2026-06-26'))}
 rows.extend(_fact(st,*x) for x in specs.get(t,()))
 if t=='KLAC':rows.extend((_cf_point(facts,'PurchaseCommitmentRemainingMinimumAmountCommitted','0000319201-25-000024','2025-06-30',2.420e9),_fact(st,'StockholdersEquityNoteStockSplitConversionRatio1',10000.,'2026-06-11','2026-06-11'),{'source_kind':'governed_cash_timing_range','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'reported_terms':{'current_commitment_usd':5.970e9,'prior_commitment_usd':2.420e9,'commitment_growth_usd':3.550e9,'cash_timing_years':(3,5,8),'annual_cash_reserve_usd':(1.990e9,1.194e9,746.25e6),'stock_split_ratio':'10-for-1'},'reported_vs_estimated':'reported_amounts_and_governed_timing'}))
 return rows
def build_batch_27_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 if ticker not in BATCH_27_TICKERS:raise ValueError(ticker)
 p=P[ticker];q=Path(source_root)/ticker;sub=json.loads((q/'submissions.json').read_text());facts=json.loads((q/'companyfacts.json').read_text());m=json.loads((q/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,sub)
 if st['source_accession']!=f['accession'] or f['period_end']!=p.period:raise ValueError(ticker)
 n=_norm(ticker,sub,facts);flows={x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,taxsrc=_normalized_tax_rate(n)
 except ValueError:tax,taxsrc=.21,()
 fallback=not .05<=tax<=.30
 if fallback:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(x) for v in flows.values() for x in v.get('sources',[])];rev=float(flows['revenue']['value']);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_27_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if cm is None or gm is None or not prof.full_history:raise ValueError(f'{ticker}: history unavailable')
 historical_margins=tuple(max(.001,float(x)) for x in (cm.low,cm.base,cm.high));margins=historical_margins;commitment_years=(3,5,8) if ticker=='KLAC' else (0,0,0);commitment_annual=tuple(5.970e9/year if year else 0. for year in commitment_years);commitment_pv=tuple(sum(commitment_annual[i]/((1+p.wacc[i])**year) for year in range(1,commitment_years[i]+1)) if commitment_years[i] else 0. for i in range(3));claims=tuple(p.claims+commitment_pv[i] for i in range(3))
 if ticker=='COHR':claims=(p.claims+max(0.,rev*margins[0]-current),p.claims,p.claims)
 growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0.,min(p.growth[2],gm.high)));rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0.,claims[i],p.shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0.,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'commitment_payment_years':commitment_years[i],'commitment_annual_cash_reserve':commitment_annual[i],'commitment_present_value_reserve':commitment_pv[i],'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claims[i],'shares':p.shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(ticker)
 ok=ticker in PASS_TICKERS;reasons=() if ok else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ok else 'Low',source_cap='High',reasons=reasons);pub=prof.public_metadata()
 if not ok:pub.update({'normalization_basis':'company_history_with_named_material_acquisition_dependency','assumption_source_mix':'reported_history_and_finsight_policy'})
 ass={**pub,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'commitment_payment_years':commitment_years,'commitment_annual_cash_reserve':commitment_annual,'commitment_present_value_reserve':commitment_pv,'other_equity_claims':claims,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':p.shares,'tax_rate_basis':'governed 21% fallback' if fallback else 'normalized filing history','equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Calculator is calibrated to the exact faded-cash base.','invalidation':p.invalid};base=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_27_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ok else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked annual and current cash conversion anchors the range.'),),warnings=(p.warning,p.invalid),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_27_HISTORY_VERSION,'availability_type':'available' if ok else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':f,'flow_sources':flows,'annual_cash_sources':list(annual),'tax_rate_sources':list(taxsrc),'tax_rate_treatment':{'fallback_applied':fallback,'rate':tax},'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'event_sources':_events(ticker,f,st,p,facts),'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':claims,'other_equity_claim_formula':p.formula,'commitment_schedule':{'years':commitment_years,'annual_cash_reserve':commitment_annual,'present_value_reserve':commitment_pv,'discount_rates':p.wacc},'shares':p.shares,'operating_liability_treatment':'Operating leases, supplier finance, purchase commitments, SBC, and ordinary working capital remain inside operating cash conversion except for explicitly modeled KLAC commitment and MU unpaid-capex reserves.'},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
if set(P)!=set(BATCH_27_TICKERS) or PASS_TICKERS|CONDITIONAL_TICKERS|WITHHELD_TICKERS!=set(BATCH_27_TICKERS):raise RuntimeError('Batch27 mismatch')
