"""One controlled recovery attempt for Batch 10's withheld KMB issuer."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_conditional_estimates import five_year_fcff_dcf
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_10 import BATCH_10_VALUATION_DATE
from .batch_10_history import BATCH_10_HISTORY_VERSION,_dim_duration,_dim_point
from .history import HISTORY_POLICY_VERSION
from .reliability import assess_reliability

BATCH_10_RECOVERY_VERSION='BATCH-10-KMB-RECOVERY-1.0'
def _sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def build_kmb_recovery_result(*,source_root:Path,structural_root:Path):
 packet=Path(source_root)/'KMB';sub=json.loads((packet/'submissions.json').read_text());facts=json.loads((packet/'companyfacts.json').read_text());manifest=json.loads((packet/'source-manifest.json').read_text());structural_dir=Path(structural_root)/'KMB';st=json.loads((structural_dir/'structural-filing.json').read_text());package=json.loads((structural_dir/'package-manifest.json').read_text());filing=_controlling(manifest,sub)
 if filing['accession']!='0001628280-26-052348' or filing['period_end']!='2026-06-30' or st['source_accession']!=filing['accession']:raise ValueError('KMB recovery source mismatch')
 n=_normalizer(sub,facts);flows={field:n.ttm_flow(field) for field in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')};reported_tax=_normalized_tax_rate(n)[0];reported_cash=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=reported_tax)
 current_revenue=_structural_flow(st,name='Revenues',start='2026-01-01',end='2026-06-30',expected=8_352_000_000.);prior_revenue=_structural_flow(st,name='Revenues',start='2025-01-01',end='2025-06-30',expected=8_217_000_000.);continuing_ebit=_structural_flow(st,name='OperatingIncomeLoss',start='2026-01-01',end='2026-06-30',expected=1_386_000_000.);continuing_da=_structural_flow(st,name='DepreciationDepletionAndAmortization',start='2026-01-01',end='2026-06-30',expected=360_000_000.);total_capex=_structural_flow(st,name='PaymentsToAcquireProductiveAssets',start='2026-01-01',end='2026-06-30',expected=776_000_000.);ifp_capex=_structural_flow(st,name='CapitalExpenditureDiscontinuedOperations',start='2026-01-01',end='2026-06-30',expected=81_000_000.);continuing_pretax=_structural_flow(st,name='IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments',start='2026-01-01',end='2026-06-30',expected=1_257_000_000.);equity_income=_structural_flow(st,name='IncomeLossFromEquityMethodInvestments',start='2026-01-01',end='2026-06-30',expected=108_000_000.);income_tax=_structural_flow(st,name='IncomeTaxExpenseBenefit',start='2026-01-01',end='2026-06-30',expected=381_000_000.)
 continuing_tax=381_000_000./(1_257_000_000.+108_000_000.);continuing_capex=776_000_000.-81_000_000.;continuing_cash=(2*(1_386_000_000.*.70+360_000_000.-776_000_000.),2*(1_386_000_000.*(1-continuing_tax)+360_000_000.-continuing_capex),2*(1_386_000_000.*.79+360_000_000.-continuing_capex));revenue=float(flows['revenue']['value']);margins=tuple(value/revenue for value in continuing_cash);growth=(-.02,8_352_000_000./8_217_000_000.-1,.03);wacc=(.115,.10,.09);terminal=(0.,.01,.02);shares=(333_300_000.*1.025,333_300_000.,333_300_000.*.975)
 sale_cash=(1_170_000_000.,1_300_000_000.,1_300_000_000.);retained_stake=(1_080_000_000.,1_200_000_000.,1_200_000_000.);cash_and_investments=tuple(956_000_000.+sale_cash[i]+retained_stake[i] for i in range(3));debt=6_517_000_000.;claims=146_000_000.;rows=[]
 for i,name in enumerate(('bear','base','bull')):
  raw=five_year_fcff_dcf(revenue=revenue,fcff_margin=margins[i],growth=growth[i],wacc=wacc[i],terminal_growth=terminal[i],cash_and_investments=cash_and_investments[i],debt=debt,noncontrolling_interests=claims,shares=shares[i]);value=max(0.,float(raw['value_per_share']));rows.append({'name':name,'conditional_value_per_share':value,'raw_value_per_share':float(raw['value_per_share']),'continuing_revenue':revenue,'continuing_cash_fcff_proxy':continuing_cash[i],'continuing_capex':continuing_capex if i else 776_000_000.,'cash_sale_proceeds':sale_cash[i],'retained_ifp_stake_value':retained_stake[i],'cash_and_investments':cash_and_investments[i],'growth':growth[i],'cash_conversion_margin':margins[i],'wacc':wacc[i],'terminal_growth':terminal[i],'shares':shares[i],'limited_liability_floor_applied':value==0 and float(raw['value_per_share'])<0})
 scenario={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=scenario['low']<=scenario['base']<=scenario['high'] or scenario['base']<=0:raise ValueError('KMB recovery range invalid')
 reliability=assess_reliability(accounting_low=scenario['base'],accounting_base=scenario['base'],accounting_high=scenario['base'],scenario_low=scenario['low'],scenario_base=scenario['base'],scenario_high=scenario['high'],model_cap='Low',source_cap='High',reasons=('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY'));warning='Conditional Low current-state estimate. It values Kimberly-Clark after the completed IFP sale and before any Kenvue closing; the pending Kenvue cash, shares, synergies, and combined cash flow are not probability-weighted or included. Standalone continuing working-capital cash is not separately reported and is covered by the Low cap.';invalidation='Invalidate on any Kenvue closing, termination, amendment, financing change, post-closing IFP adjustment, or continuing cash outside the recorded range.'
 assumptions={'history_policy_version':HISTORY_POLICY_VERSION,'history_years_used':0,'normalization_basis':'annualized_reported_continuing_EBIT_DA_and_capex_proxy','assumption_source_mix':'reported_current_comparatives_transaction_values_and_finsight_policy','cash_conversion_margin':margins,'growth':growth,'wacc':wacc,'terminal_growth':terminal,'shares':shares,'cash_sale_proceeds':sale_cash,'retained_ifp_stake_value':retained_stake,'IFP_value_reserve_basis':'Bear applies a 10% reserve to the reported approximate $1.3B sale proceeds and $1.2B retained-stake fair value for closing adjustments, tax, and valuation uncertainty; base/bull do not exceed reported values.','transition_capex_reserve':(81_000_000.,0.,0.),'working_capital_cash_treatment':'Standalone continuing working-capital cash is not reported; the EBIT/D&A/capex proxy excludes a separate working-capital benefit and reliability is capped Low.','equity_floor_basis':'not applied','calculator_calibration':'Calculator is calibrated to the current-state base; private transaction and bridge evidence remain fixed.','invalidation':invalidation}
 baseline=BaselineValuation(ticker='KMB',method='post_ifp_pre_kenvue_cash_fcff',method_version=BATCH_10_RECOVERY_VERSION,low=scenario['low'],base=scenario['base'],high=scenario['high'],confidence=reliability.label,availability_type=AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('continuing current scale',str(revenue),AssumptionClassification.REPORTED,'Current continuing revenue and consolidated cash facts anchor the model.'),BaselineAssumption('IFP closing value','cash $1.3B; retained stake $1.2B',AssumptionClassification.REPORTED,'The controlling filing reports the completed sale and initial retained-stake fair value.'),BaselineAssumption('event-state policy',str(assumptions),AssumptionClassification.FINSIGHT_ASSUMPTION,'The pending Kenvue transaction remains outside intrinsic value.')),warnings=(warning,invalidation),confidence_reasons=tuple(reliability.reasons),calculator_link='/api/us-valuations/KMB/calculator')
 source_url=f"https://www.sec.gov/Archives/edgar/data/55785/{filing['accession'].replace('-','')}/{filing['primary_document']}";primary_row=next(row for row in package['files'] if row['local_path']==package['entrypoint_local_path'])
 event_sources=[current_revenue,prior_revenue,continuing_ebit,continuing_da,total_capex,ifp_capex,continuing_pretax,equity_income,income_tax,_point(st,name='CashAndCashEquivalentsAtCarryingValue',expected=956_000_000.,period_end='2026-06-30'),_point(st,name='DebtCurrent',expected=43_000_000.,period_end='2026-06-30'),_point(st,name='LongTermDebtAndCapitalLeaseObligations',expected=6_474_000_000.,period_end='2026-06-30'),_point(st,name='MinorityInterest',expected=124_000_000.,period_end='2026-06-30'),_point(st,name='RedeemableCommonAndPreferredSecuritiesOfSubsidiaries',expected=22_000_000.,period_end='2026-06-30'),_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=333_300_000.,period_start='2026-01-01',period_end='2026-06-30'),_point(st,name='EquityMethodInvestmentsFairValueDisclosure',expected=1_200_000_000.,period_end='2026-07-01'),_dim_duration(st,'BusinessCombinationPriceOfAcquisitionExpected',6_700_000_000.,'2025-11-02','2025-11-02','KenvueAcquisitionMember'),_dim_point(st,'BusinessCombinationCommonStockIssuedExpected',280_000_000.,'2025-11-02','KenvueAcquisitionMember'),{'source_kind':'controlling_filing_subsequent_event_narrative','accession':filing['accession'],'filed':filing['filed'],'event_date':'2026-07-01','field':'IFP_cash_purchase_price','value':1_300_000_000.,'unit':'USD','reported_vs_estimated':'reported_approximate','source_url':source_url,'primary_document_sha256':primary_row['sha256'],'basis':'The filing reports the completed IFP sale for approximately $1.3B cash, subject to post-closing adjustments.'}]
 return {'ticker':'KMB','method':'post_ifp_pre_kenvue_cash_fcff','model_version':BATCH_10_RECOVERY_VERSION,'availability_type':'conditional_estimate','scenario_rows':rows,'scenario_range':scenario,'reported_inputs':{'continuing_ttm_revenue':revenue,'continuing_h1_operating_income':1_386_000_000.,'continuing_h1_depreciation_amortization':360_000_000.,'continuing_h1_capex_proxy':continuing_capex,'continuing_tax_rate':continuing_tax,'consolidated_ttm_operating_cash_flow_diagnostic':flows['operating_cash_flow']['value'],'consolidated_ttm_capex_diagnostic':flows['capital_expenditures']['value'],'consolidated_cash_fcff_diagnostic':reported_cash,'current_continuing_h1_revenue':8_352_000_000.,'prior_continuing_h1_revenue':8_217_000_000.},'governed_assumptions':assumptions,'history_reliability':reliability.as_dict(),'source_ledger':{'controlling_filing':filing,'source_packet_manifest_sha256':_sha(packet/'source-manifest.json'),'package_manifest_sha256':_sha(structural_dir/'package-manifest.json'),'structural_filing_sha256':_sha(structural_dir/'structural-filing.json'),'consolidated_flow_diagnostic':flows,'event_and_bridge_sources':event_sources,'bridge_reconciliation':{'remaining_cash':956_000_000.,'IFP_cash_sale_proceeds':sale_cash,'retained_49_percent_IFP_stake':retained_stake,'remaining_debt_and_capital_leases':debt,'nci_and_redeemable_claims':claims,'continuing_cash_formula':'2 × (continuing EBIT × (1-tax) + continuing D&A − continuing capex); consolidated OCF is diagnostic only because it includes discontinued working capital.','transition_capex_reserve':'Bear retains all $776M H1 capex, including the separately reported $81M IFP amount; base/bull use $695M continuing capex.','working_capital_cash':'Standalone continuing working-capital cash is not separately reported and no positive working-capital add-back is used.','transferred_IFP_debt_and_cash':'Excluded from remaining KMB; the transferred IFP term debt is non-recourse after closing.','IFP_gain':'Not added separately; cash proceeds and retained-stake value already represent the transaction.','Kenvue':'Pending $6.7B expected price and 280M expected shares are event context only, not probability-weighted intrinsic inputs.','supplier_finance':'Remains operating in cash conversion and is not subtracted again.'}},'warning':warning,'baseline':baseline.as_private_dict()}
