"""Launch-first Conditional Low baselines for controlled Batch 05."""
from __future__ import annotations
from dataclasses import dataclass
import json
from pathlib import Path
from statistics import median
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation,FallbackRejected,FallbackStage,run_fallback_ladder
from .batch_02_conditional_estimates import five_year_fcff_dcf
from .batch_02_practical_inputs import _annual_cash_fcff,_normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_05 import BATCH_05_TICKERS

BATCH_05_LAUNCH_FIRST_VERSION='BATCH-05-LAUNCH-FIRST-1.0'
@dataclass(frozen=True)
class Policy:
 method:str;growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];shares:tuple[float,float,float];period:str;cash:float;debt:float;nci:float;warning:str;invalidation:str;reserve:tuple[float,float,float];land_reinvestment:tuple[float,float,float]=(0,0,0)
P={
'WSM':Policy('home_furnishing_normalized_cash_fcff',(0,.03,.06),(.10,.09,.08),(0,.015,.02),(125_888_700.,122_891_350.,119_894_000.),'2026-05-03',651_601_000.,0,0,'Conditional Low estimate. Inventory, leases, working capital, and unreported financing claims are broadly ranged.','Invalidate when debt, inventory, leases, shares, or cash conversion leave the governed range.',(.10,.05,0)),
'CASY':Policy('food_fuel_retail_normalized_cash_fcff',(0,.04,.07),(.095,.085,.075),(.01,.02,.025),(39_145_736.,38_213_694.,37_281_653.),'2026-04-30',522_991_000.,2_431_594_000.,0,'Conditional Low estimate. Fuel/merchandise mix, acquisitions, LIFO, land, and working capital can move value materially.','Invalidate when acquisition, fuel-margin, debt/lease, or working-capital evidence leaves the range.',(.02,.01,0)),
'CCL':Policy('cruise_cycle_normalized_cash_fcff',(-.05,.03,.08),(.13,.11,.095),(0,.01,.02),(1_459_500_000.,1_424_750_000.,1_390_000_000.),'2026-05-31',2_260_000_000.,25_570_000_000.,16_000_000.,'Conditional Low estimate. Cruise recovery, heavy ship capex, debt maturities, leases, and NCI make the range unusually wide.','Invalidate when debt, leases, NCI, ship capex, or normalized cruise cash leave the range.',(.02,.01,0)),
'PHM':Policy('homebuilder_normalized_equity_earnings_baseline',(-.06,0,.06),(.12,.10,.09),(0,.01,.02),(201_589_500.,196_789_750.,191_990_000.),'2026-06-30',1_335_709_000.,0,0,'Conditional Low normalized-equity-earnings estimate. It includes consolidated homebuilding and mortgage earnings rather than claiming mortgage cash separation.','Invalidate when consolidated earnings, mortgage contribution, debt, inventory, or shares leave the range.',(.10,.05,0),(.15,.10,.05)),
'SBUX':Policy('restaurant_lease_turnaround_cash_fcff',(-.03,.03,.07),(.11,.095,.085),(0,.015,.02),(1_200_150_000.,1_171_575_000.,1_143_000_000.),'2026-06-28',3_923_500_000.,13_384_100_000.,7_200_000.,'Conditional Low estimate. Store turnaround, leases, inventory, and negative book equity make the cash range provisional.','Invalidate when store cash, debt, leases, shares, or turnaround margins leave the range.',(.02,.01,0)),
'AZO':Policy('auto_parts_working_capital_cash_fcff',(0,.04,.07),(.10,.09,.08),(.01,.02,.025),(17_822_700.,17_398_350.,16_974_000.),'2026-05-09',394_639_000.,9_058_000_000.,0,'Conditional Low estimate. Inventory/AP financing, leases, repurchases, and negative book equity are normalized through broad cash states.','Invalidate when working-capital reversal, debt, leases, or split-adjusted shares leave the range.',(.02,.01,0)),
'DHI':Policy('homebuilder_normalized_equity_earnings_baseline',(-.06,0,.06),(.12,.10,.09),(0,.01,.02),(302_820_000.,295_610_000.,288_400_000.),'2026-06-30',2_078_700_000.,0,587_000_000.,'Conditional Low normalized-equity-earnings estimate. It includes consolidated homebuilding and mortgage earnings rather than claiming mortgage cash separation.','Invalidate when consolidated earnings, mortgage contribution, debt, NCI, or shares leave the range.',(.10,.05,0),(.15,.10,.05)),
'RCL':Policy('cruise_cycle_normalized_cash_fcff',(-.04,.04,.09),(.12,.10,.09),(0,.01,.02),(283_500_000.,276_750_000.,270_000_000.),'2026-06-30',875_000_000.,23_407_000_000.,225_000_000.,'Conditional Low estimate. Ship capex nearly consumes current OCF; debt, leases, NCI, and cruise-cycle assumptions drive the range.','Invalidate when capex-adjusted cash, debt, leases, NCI, or shares leave the range.',(.02,.01,0)),
'ORLY':Policy('auto_parts_working_capital_cash_fcff',(0,.04,.07),(.10,.09,.08),(.01,.02,.025),(877_444_050.,856_552_525.,835_661_000.),'2026-06-30',262_181_000.,7_014_543_000.,0,'Conditional Low estimate. Inventory/AP financing, leases, buybacks, and negative book equity are normalized through cash scenarios.','Invalidate when working-capital reversal, debt, leases, or split-adjusted shares leave the range.',(.02,.01,0)),
'NVR':Policy('homebuilder_normalized_equity_earnings_baseline',(-.06,0,.06),(.12,.10,.09),(0,.01,.02),(3_015_066.,2_943_755.,2_872_444.),'2026-06-30',1_197_259_000.,39_553_000.,0,'Conditional Low normalized-equity-earnings estimate. It includes consolidated homebuilding, lot-option, and mortgage earnings rather than claiming cash separation.','Invalidate when consolidated earnings, mortgage contribution, lot deposits, debt, or shares leave the range.',(.10,.05,0),(.12,.08,.04)),
}
def _bridge_sources(t,st,pol,assets):
 p=lambda n,v:_point(st,name=n,expected=v,period_end=pol.period)
 specs={'WSM':[('CashAndCashEquivalentsAtCarryingValue',651_601_000.)],'CASY':[('CashAndCashEquivalentsAtCarryingValue',522_991_000.),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',2_431_594_000.)],'CCL':[('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',2_260_000_000.),('LongTermDebt',25_570_000_000.),('MinorityInterest',16_000_000.)],'PHM':[('CashAndCashEquivalentsAtCarryingValue',1_335_709_000.),('NotesPayable',1_820_277_000.)],'SBUX':[('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',3_449_800_000.),('ShortTermInvestments',160_500_000.),('AvailableForSaleSecuritiesDebtSecuritiesNoncurrent',313_200_000.),('DebtInstrumentCarryingAmount',13_384_100_000.),('MinorityInterest',7_200_000.)],'AZO':[('CashAndCashEquivalentsAtCarryingValue',253_729_000.),('AvailableForSaleSecuritiesDebtSecurities',140_910_000.),('DebtLongtermAndShorttermCombinedAmount',9_058_000_000.)],'DHI':[('CashAndCashEquivalentsAtCarryingValue',2_078_700_000.),('NotesPayable',7_112_600_000.),('MinorityInterest',587_000_000.)],'RCL':[('CashAndCashEquivalentsAtCarryingValue',875_000_000.),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',23_407_000_000.),('MinorityInterest',225_000_000.)],'ORLY':[('CashAndCashEquivalentsAtCarryingValue',262_181_000.),('LongTermDebtNoncurrent',7_014_543_000.)],'NVR':[('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',1_197_259_000.),('FinanceLeaseLiability',39_553_000.)]}
 rows=[p('Assets',assets),*[p(n,v) for n,v in specs[t]]]
 starts={'WSM':'2026-02-02','CASY':'2025-05-01','CCL':'2025-12-01','PHM':'2026-01-01','SBUX':'2025-09-29','AZO':'2025-08-31','DHI':'2025-10-01','RCL':'2026-01-01','ORLY':'2026-01-01','NVR':'2026-01-01'}
 rows.append(_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=pol.shares[2],period_start=starts[t],period_end=pol.period));return rows

def _companyfacts_duration(facts, *, concept, accession, start, end, expected):
 rows=[row for row in facts['facts']['us-gaap'][concept]['units']['USD'] if row.get('accn')==accession and row.get('start')==start and row.get('end')==end and isinstance(row.get('val'),(int,float)) and float(row['val'])==expected]
 if not rows:raise ValueError(f'{concept}: expected {expected} absent for {accession} {start}/{end}')
 row=rows[0]
 return {'source_kind':'sec_companyfacts','accession':accession,'filed':row.get('filed'),'form':row.get('form'),'period_start':start,'period_end':end,'concept':f'us-gaap:{concept}','unit':'USD','value':expected,'reported_vs_estimated':'reported'}

def _structural_duration(st, *, name, expected, start, end):
 rows=[row for row in st['facts'] if row.get('local_name')==name and row.get('period_start')==start and row.get('period_end')==end and not row.get('dimensions') and isinstance(row.get('value'),(int,float)) and float(row['value'])==expected]
 if not rows:raise ValueError(f'{name}: expected {expected} absent for {start}/{end}')
 row=rows[0]
 return {'source_kind':'structural_xbrl','accession':st['source_accession'],'period_start':start,'period_end':end,'concept':row.get('qname'),'unit':row.get('unit') or 'USD','value':expected,'reported_vs_estimated':'reported'}

HOME_EARNINGS={
 'PHM':{'ttm':1_906_446_000.,'fy':(2_218_730_000.,'0000822416-26-000007','2025-01-01','2025-12-31'),'current_ytd':(818_998_000.,'0000822416-26-000036','2026-01-01','2026-06-30'),'prior_ytd':(1_131_282_000.,'0000822416-26-000036','2025-01-01','2025-06-30')},
 'DHI':{'ttm':3_052_900_000.,'fy':(3_585_200_000.,'0000882184-25-000081','2024-10-01','2025-09-30'),'current_ytd':(2_147_600_000.,'0000882184-26-000096','2025-10-01','2026-06-30'),'prior_ytd':(2_679_900_000.,'0000882184-26-000096','2024-10-01','2025-06-30')},
 'NVR':{'ttm':1_141_320_000.,'fy':(1_339_816_000.,'0000906163-26-000018','2025-01-01','2025-12-31'),'current_ytd':(434_817_000.,'0000906163-26-000093','2026-01-01','2026-06-30'),'prior_ytd':(633_313_000.,'0000906163-26-000093','2025-01-01','2025-06-30')},
}

def _homebuilder_context(ticker,st):
 if ticker=='PHM':return [_point(st,name='InventoryRealEstateMortgageLoansHeldInInventory',expected=562_400_000.,period_end='2026-06-30'),_point(st,name='InventoryOperativeBuilders',expected=13_715_417_000.,period_end='2026-06-30'),_point(st,name='RemainingPurchasePriceOfAllLandOptionAgreements',expected=9_687_078_000.,period_end='2026-06-30'),_structural_duration(st,name='GainLossOnSaleOfMortgageLoans',expected=87_900_000.,start='2026-01-01',end='2026-06-30'),_point(st,name='NotesPayable',expected=1_820_277_000.,period_end='2026-06-30')]
 if ticker=='DHI':return [_point(st,name='PrincipalAmountOutstandingOnLoansHeldForSaleOrSecuritization',expected=3_100_000_000.,period_end='2026-06-30'),_point(st,name='InventoryRealEstate',expected=26_686_900_000.,period_end='2026-06-30'),_point(st,name='InventoryRealEstateLandAndLandDevelopmentCosts',expected=14_318_900_000.,period_end='2026-06-30'),_structural_duration(st,name='PaymentsForOriginationOfMortgageLoansHeldForSale',expected=17_200_000_000.,start='2025-10-01',end='2026-06-30'),_structural_duration(st,name='ProceedsFromSaleOfMortgageLoansHeldForSale',expected=16_700_000_000.,start='2025-10-01',end='2026-06-30'),_point(st,name='NotesPayable',expected=7_112_600_000.,period_end='2026-06-30')]
 return [_point(st,name='ContractLandDeposits',expected=1_062_308_000.,period_end='2026-06-30'),_point(st,name='LossReserveOnContractLandDeposits',expected=134_928_000.,period_end='2026-06-30'),_point(st,name='InventoryRealEstateLandAndLandDevelopmentCosts',expected=21_067_000.,period_end='2026-06-30'),_point(st,name='DepositsAssets',expected=927_380_000.,period_end='2026-06-30'),_structural_duration(st,name='PaymentsForOriginationOfMortgageLoansHeldForSale',expected=2_412_511_000.,start='2026-01-01',end='2026-06-30'),_structural_duration(st,name='ProceedsFromSaleOfMortgageLoansHeldForSale',expected=2_665_140_000.,start='2026-01-01',end='2026-06-30'),_structural_duration(st,name='GainLossOnSaleOfMortgageLoans',expected=76_607_000.,start='2026-01-01',end='2026-06-30')]

def _homebuilder_equity_result(ticker,pol,filing,st,facts,assets,flows):
 data=HOME_EARNINGS[ticker];earn=(data['ttm']*.6,data['ttm'],data['ttm']*1.2);multiples=(5.,8.,11.);rows=[]
 for i,name in enumerate(('bear','base','bull')):
  value=earn[i]*multiples[i]/pol.shares[i];rows.append({'name':name,'conditional_value_per_share':value,'normalized_consolidated_earnings':earn[i],'earnings_multiple':multiples[i],'shares':pol.shares[i],'wacc':pol.wacc[i],'cash_conversion_margin':earn[i]/float(flows['revenue']['value']),'limited_liability_floor_applied':False})
 margins=tuple(row['cash_conversion_margin'] for row in rows);srange={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']};sources=_bridge_sources(ticker,st,pol,assets);components={key:_companyfacts_duration(facts,concept='NetIncomeLoss',accession=value[1],start=value[2],end=value[3],expected=value[0]) for key,value in (('fy',data['fy']),('current_ytd',data['current_ytd']),('prior_ytd',data['prior_ytd']))};context=_homebuilder_context(ticker,st);exposures={'PHM':23_964_895_000.,'DHI':29_786_900_000.,'NVR':1_218_303_000.};exposure=exposures[ticker];reserves=tuple(exposure*rate for rate in pol.reserve);accounting_impact=max(abs(reserves[0]-reserves[1]),abs(reserves[2]-reserves[1]))/max(srange['base']*pol.shares[1],1.);ass={'cash_conversion_margin':margins,'normalized_consolidated_earnings':earn,'earnings_multiples':multiples,'shares':pol.shares,'route_is_mortgage_separated_fcff':False,'ev_debt_bridge_applied':False,'equity_floor_basis':'not applied','calculator_calibration':'Calculator directly varies normalized earnings and the earnings multiple around the published base.','invalidation':pol.invalidation}
 def primary():raise FallbackRejected('Primary mortgage-separated FCFF route is not complete; conditional consolidated equity-earnings baseline selected.')
 def conditional():return BaselineValuation(ticker=ticker,method=pol.method,method_version=BATCH_05_LAUNCH_FIRST_VERSION,low=srange['low'],base=srange['base'],high=srange['high'],confidence='Low',availability_type=AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('reported consolidated earnings',str(data),AssumptionClassification.REPORTED,'FY plus current YTD less prior YTD net income.'),BaselineAssumption('earnings scenarios',str(ass),AssumptionClassification.FINSIGHT_ASSUMPTION,'Broad equity-level baseline that keeps mortgage contribution inside consolidated earnings.')),warnings=(pol.warning,pol.invalidation),confidence_reasons=('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY'),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 baseline=run_fallback_ladder(ticker=ticker,strategies=((FallbackStage.PRIMARY_INTRINSIC,'mortgage_separated_fcff',primary),(FallbackStage.CONDITIONAL,pol.method,conditional)))
 return {'ticker':ticker,'method':pol.method,'model_version':BATCH_05_LAUNCH_FIRST_VERSION,'availability_type':'conditional_estimate','scenario_rows':rows,'scenario_range':srange,'reported_inputs':{'ttm_revenue':flows['revenue']['value'],'ttm_consolidated_net_income':data['ttm']},'governed_assumptions':ass,'accounting_impact_ratio':accounting_impact,'source_ledger':{'controlling_filing':filing,'net_income_reconstruction':{'components':components,'ttm':data['ttm'],'formula':'FY + current YTD - prior YTD'},'mortgage_and_land_context':context,'accounting_uncertainty':{'source_linked_exposure':exposure,'reserve_rates':pol.reserve,'reserve_values':reserves,'impact_ratio':accounting_impact,'basis':'Issuer-specific reported mortgage/land exposure multiplied by governed reserve rates; the ratio is the reserve movement relative to base common-equity value.'},'bridge_sources':sources,'bridge_treatment':'Equity-level baseline: homebuilding debt and mortgage banking remain inside consolidated equity earnings; no EV debt bridge is applied.','structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':pol.warning,'baseline':baseline.as_private_dict()}

def build_batch_05_launch_first_result(*,ticker,source_root,structural_root):
 pol=P[ticker];packet=Path(source_root)/ticker;sub=json.loads((packet/'submissions.json').read_text());facts=json.loads((packet/'companyfacts.json').read_text());manifest=json.loads((packet/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());filing=_controlling(manifest,sub)
 if filing['period_end']!=pol.period or st['source_accession']!=filing['accession']:raise ValueError(ticker)
 n=_normalizer(sub,facts);flows={f:n.ttm_flow(f) for f in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')};assets=float(n.instant('total_assets').value);tax=0.21
 if ticker in HOME_EARNINGS:
  return _homebuilder_equity_result(ticker,pol,filing,st,facts,assets,flows)
 try:tax=_normalized_tax_rate(n)[0]
 except ValueError:pass
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);cur_margin=current/float(flows['revenue']['value'])
 try:ac,ar,asrc=_annual_cash_fcff(n,spectrum_required=False,spectrum_floor=0,spectrum_source={},scope_adjustment=0);hist=[c/r for c,r in zip(ac,ar) if r>0]
 except ValueError:ac=ar=asrc=();hist=[]
 pool=hist[-3:]+[cur_margin];margins=(max(.005,min(pool)*.75),median(pool),max(pool)*1.15) if len(pool)>1 else (max(.005,cur_margin*.65),cur_margin,cur_margin*1.25)
 margins=tuple(max(.005,m-pol.land_reinvestment[i]) for i,m in enumerate(margins));rows=[]
 lease_reserve=(82_161_000.,41_080_500.,0.) if ticker=='AZO' else (0.,0.,0.)
 for i,name in enumerate(('bear','base','bull')):
  claims=pol.nci+assets*pol.reserve[i]+lease_reserve[i];raw=five_year_fcff_dcf(revenue=float(flows['revenue']['value']),fcff_margin=margins[i],growth=pol.growth[i],wacc=pol.wacc[i],terminal_growth=pol.terminal[i],cash_and_investments=pol.cash,debt=pol.debt,noncontrolling_interests=claims,shares=pol.shares[i]);v=max(0,float(raw['value_per_share']));rows.append({'name':name,'conditional_value_per_share':v,'raw_value_per_share':raw['value_per_share'],'cash_conversion_margin':margins[i],'growth':pol.growth[i],'wacc':pol.wacc[i],'terminal_growth':pol.terminal[i],'limited_liability_floor_applied':v==0 and raw['value_per_share']<0})
 sources=_bridge_sources(ticker,st,pol,assets);nci_reported=ticker in {'CCL','SBUX','DHI','RCL'}
 if not nci_reported:sources.append({'source_kind':'governed_policy','field':'unresolved_nci_and_other_claims','period_end':pol.period,'reported_vs_estimated':'estimated_range','value_range':{'bear':assets*pol.reserve[0],'base':assets*pol.reserve[1],'bull':assets*pol.reserve[2]},'basis':'No current NCI point is asserted; reserve covers unresolved claims.'})
 if ticker=='AZO':sources.extend([_structural_duration(st,name='FinanceLeasePrincipalPayments',expected=82_161_000.,start='2025-08-31',end='2026-05-09'),{'source_kind':'governed_policy','field':'unresolved_finance_lease_reserve','period_end':pol.period,'reported_vs_estimated':'estimated_range','value_range':{'bear':lease_reserve[0],'base':lease_reserve[1],'bull':lease_reserve[2]},'basis':'Liability balance was not separately reported; one year-to-date principal-payment amount caps the explicit reserve and is deducted once.'}])
 srange={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']};ass={'cash_conversion_margin':margins,'growth':pol.growth,'wacc':pol.wacc,'terminal_growth':pol.terminal,'shares':pol.shares,'unresolved_claims_reserve_rates':pol.reserve,'land_inventory_reinvestment_rates':pol.land_reinvestment,'equity_floor_basis':'limited-liability floor after negative residual' if srange['low']==0 else 'not applied','calculator_calibration':'Calculator is calibrated to the baseline and does not rerun the private issuer model.','invalidation':pol.invalidation}
 def primary():raise FallbackRejected('Primary source-bounded route requires issuer-specific refinements; conditional baseline selected.')
 def conditional():return BaselineValuation(ticker=ticker,method=pol.method,method_version=BATCH_05_LAUNCH_FIRST_VERSION,low=srange['low'],base=srange['base'],high=srange['high'],confidence='Low',availability_type=AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('reported anchors',str({k:v['value'] for k,v in flows.items()}),AssumptionClassification.REPORTED,'Cutoff-safe filing facts.'),BaselineAssumption('scenario policy',str(ass),AssumptionClassification.FINSIGHT_ASSUMPTION,'Launch-first baseline assumptions.')),warnings=(pol.warning,pol.invalidation),confidence_reasons=('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY'),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 baseline=run_fallback_ladder(ticker=ticker,strategies=((FallbackStage.PRIMARY_INTRINSIC,'primary_source_bounded',primary),(FallbackStage.CONDITIONAL,pol.method,conditional)))
 return {'ticker':ticker,'method':pol.method,'model_version':BATCH_05_LAUNCH_FIRST_VERSION,'availability_type':'conditional_estimate','scenario_rows':rows,'scenario_range':srange,'reported_inputs':{'ttm_revenue':flows['revenue']['value'],'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_capex':flows['capital_expenditures']['value']},'governed_assumptions':ass,'source_ledger':{'controlling_filing':filing,'flow_sources':flows,'annual_sources':asrc,'bridge_sources':sources,'bridge_reconciliation':{'cash':pol.cash,'debt':pol.debt,'reported_nci':pol.nci if nci_reported else None,'nci_status':'reported' if nci_reported else 'unresolved_covered_by_reserve'},'operating_lease_treatment':'Operating lease cash remains in OCF and is not bridge debt.','structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':pol.warning,'baseline':baseline.as_private_dict()}
