"""History-backed practical baselines for controlled Universe Reset Batch 21."""
from __future__ import annotations
from dataclasses import dataclass
import json
from pathlib import Path
from app.valuation.bank import residual_income_valuation
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _no_preferred
from .batch_16_history import _history_source,_share_point
from .batch_21 import BATCH_21_TICKERS,BATCH_21_VALUATION_DATE
from .equity_fact_selection import annual_facts
from .history import HISTORY_POLICY_VERSION,CompanyHistoryProfile,HistoryObservation,build_cash_fcff_history_profile,summarize_history_metric
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability

BATCH_21_HISTORY_VERSION='BATCH-21-INDUSTRIALS-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'EME','GWW','CSX','EXPD','FAST'});CONDITIONAL_TICKERS=frozenset({'RTX','LHX','TXT','NSC','JBHT'});WITHHELD_TICKERS=frozenset();EQUITY_EARNINGS_TICKERS=frozenset({'TXT'})
def _shares(w,c):
 hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;weighted:float;current:float;current_end:str;growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalidation:str;formula:str
P={
'RTX':Policy('aerospace_engine_claim_adjusted_faded_fcff','2026-06-30',9.016e9,32.087e9,2.757e9,1.3647e9,1_347_758_144.,'2026-06-30',(-.02,.04,.07),(.11,.095,.085),(.005,.015,.025),'Conditional Low aerospace baseline. Current bridge and history reconcile, while powder-metal engine inspection, compensation, and litigation exposure remains material.','Invalidate if engine inspection scope, customer compensation, claims, cash conversion, debt, NCI, or shares changes materially.','$1.739B NCI + $800M environmental + $218M trade accrual; warranties remain operating.'),
'EME':Policy('construction_services_backlog_faded_fcff','2026-06-30',924.411e6,6.1e6,1.037e6,44_619_442.,44_109_901.,'2026-07-24',(.02,.07,.10),(.11,.095,.085),(.005,.015,.025),'Source-bounded construction-services baseline. Five-year cash history and current bridge reconcile.','Invalidate if backlog conversion, acquisitions, working capital, debt/leases, claims, or shares changes materially.','$6.1M finance leases plus $1.037M NCI.'),
'LHX':Policy('post_aerojet_defense_faded_fcff','2026-07-03',1.521e9,10.999e9,1.628e9,187.7e6,186_214_616.,'2026-07-24',(-.02,.04,.07),(.11,.095,.085),(.005,.015,.025),'Conditional Low post-Aerojet defense baseline. Three comparable annual periods support value, while integration and redeemable preferred exposure remain material.','Invalidate if integration, program cash, preferred redemption, environmental exposure, debt, or shares changes materially.','$968M redeemable preferred NCI + $660M environmental accrual.'),
'GWW':Policy('industrial_distribution_faded_fcff','2026-06-30',589e6,2.408e9,382e6,47.3e6,47_100_942.,'2026-07-28',(.01,.05,.08),(.105,.09,.08),(.005,.015,.025),'Source-bounded industrial-distribution baseline. Recent cash history and current bridge reconcile.','Invalidate if volume, pricing, inventory cash, debt, NCI, claims, or shares changes materially.','$382M reported NCI.'),
'CSX':Policy('rail_network_faded_fcff','2026-06-30',1.390e9,18.864e9,6e6,1.860e9,1_852_474_917.,'2026-06-30',(-.02,.02,.04),(.105,.09,.08),(.005,.015,.025),'Source-bounded rail-network baseline. Five-year cash history and current bridge reconcile.','Invalidate if volumes, pricing, network efficiency, capex, debt/leases, claims, or shares changes materially.','$6M NCI; cash and investments counted once.'),
'NSC':Policy('transaction_separate_rail_faded_fcff','2026-06-30',1.069e9,15.967e9,245e6,225e6,224_608_373.,'2026-06-30',(-.02,.02,.04),(.105,.09,.08),(.005,.015,.025),'Conditional Low standalone Norfolk Southern baseline. Recorded claims and history reconcile; Union Pacific consideration remains separate.','Invalidate if the Union Pacific transaction closes, terminates, or changes; or rail economics, claims, debt, or shares changes materially.','$60M environmental + $185M Eastern Ohio incident accrual.'),
'JBHT':Policy('trucking_cycle_faded_fcff','2026-06-30',4.162e6,1.145337e9,0.,95.073e6,93_914_939.,'2026-06-30',(-.05,.01,.05),(.115,.10,.09),(0.,.01,.02),'Conditional Low trucking-cycle baseline. Loss-preserving history is finite, while pricing and equipment reinvestment remain material.','Invalidate if freight demand, pricing, equipment capex, cash conversion, debt, claims, or shares changes materially.','No NCI/preferred claim.'),
'EXPD':Policy('freight_forwarding_owner_cash_faded_fcff','2026-06-30',1.031448e9,0.,2.371e6,132.724e6,129_990_622.,'2026-07-31',(-.05,.02,.06),(.105,.09,.08),(.005,.015,.025),'Source-bounded debt-free freight-forwarding baseline. Current cash, debt absence, NCI, shares, and recent cash history reconcile.','Invalidate if rates/volumes, working capital, cash conversion, debt absence, NCI, claims, or shares changes materially.','$2.371M NCI; no debt/preferred claim.'),
'FAST':Policy('industrial_supply_faded_fcff','2026-06-30',204.7e6,120e6,0.,1_150_590_276.,1_147_497_573.,'2026-07-10',(.01,.05,.08),(.105,.09,.08),(.005,.015,.025),'Source-bounded industrial-supply baseline. Five-year cash history and current bridge reconcile.','Invalidate if onsite growth, industrial demand, inventory cash, debt, claims, or shares changes materially.','$120M total debt; no NCI/preferred claim.')}
POINT={'RTX':(('CashAndCashEquivalentsAtCarryingValue',8.305e9),('MarketableSecuritiesCurrent',711e6),('LongTermDebtAndCapitalLeaseObligations',31.858e9),('ShortTermBorrowings',229e6),('MinorityInterest',1.739e9)),'EME':(('CashAndCashEquivalentsAtCarryingValue',924.411e6),('FinanceLeaseLiability',6.1e6),('MinorityInterest',1.037e6),('PreferredStockValue',0.)),'LHX':(('CashAndCashEquivalentsAtCarryingValue',1.521e9),('LongTermDebtAndCapitalLeaseObligationsIncludingCurrentMaturities',10.999e9),('RedeemableNoncontrollingInterestEquityPreferredCarryingAmount',968e6)),'GWW':(('CashAndCashEquivalentsAtCarryingValue',589e6),('LongTermDebt',2.408e9),('MinorityInterest',382e6),('PreferredStockValue',0.)),'CSX':(('CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',1.007e9),('ShortTermInvestments',383e6),('DebtAndCapitalLeaseObligations',18.864e9),('MinorityInterest',6e6)),'NSC':(('CashAndCashEquivalentsAtCarryingValue',1.069e9),('LongTermDebtAndCapitalLeaseObligations',15.967e9)),'JBHT':(('CashAndCashEquivalentsAtCarryingValue',4.162e6),('LongTermDebtNoncurrent',1.145337e9),('LongTermDebtCurrent',0.)),'EXPD':(('CashAndCashEquivalentsAtCarryingValue',1.031448e9),('MinorityInterest',2.371e6)),'FAST':(('CashAndCashEquivalentsAtCarryingValue',204.7e6),('LongTermDebt',120e6),('PreferredStockValue',0.))}
START={'RTX':'2026-01-01','EME':'2026-01-01','LHX':'2026-01-03','GWW':'2026-01-01','CSX':'2026-01-01','NSC':'2026-01-01','JBHT':'2026-01-01','EXPD':'2026-01-01','FAST':'2026-01-01'}
EVENT={'RTX':('Pratt powder-metal inspection and claims',{'unquantified_tail':True}),'EME':('ordinary backlog and acquisitions',{}),'LHX':('Aerojet integration and preferred NCI',{'preferred_redemption_value_usd':1.422e9}),'GWW':('ordinary industrial distribution',{}),'CSX':('ordinary rail operations',{}),'NSC':('pending Union Pacific transaction',{'cash_per_share_usd':88.82,'unp_shares_per_share':1.0,'cutoff_status':'signed_not_closed'}),'JBHT':('trucking and intermodal cycle',{}),'EXPD':('freight forwarding cycle',{}),'FAST':('ordinary industrial supply',{})}
def _bridge(t,st,p):
 rows=[_point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]];rows.extend((_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=p.weighted,period_start=START[t],period_end=p.period),_share_point(st,expected=p.current,end=p.current_end)))
 if t not in {'RTX','LHX'}:rows.append(_no_preferred(st,p.period))
 return rows
def _operating(t,filing,st,subs,facts):
 p=P[t];n=_normalizer(subs,facts);flows={x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,_=_normalized_tax_rate(n)
 except ValueError:tax=.21
 if tax<.05:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=flows['operating_cash_flow']['value'],capital_expenditures=flows['capital_expenditures']['value'],spectrum_investment=0,interest_expense=abs(flows['interest_expense']['value']),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(y) for x in flows.values() for y in x.get('sources',[])];rev=float(flows['revenue']['value']);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_21_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if not prof.full_history or cm is None or gm is None:raise ValueError(t)
 margins=(max(.001,cm.low),max(.001,cm.base),max(.001,cm.high));growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0,min(p.growth[2],gm.high)));shares=_shares(p.weighted,p.current);rows=[];traces={}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0,p.claims,shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims,'shares':shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(t)
 ispass=t in PASS_TICKERS;reasons=() if ispass else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ispass else 'Low',source_cap='High',reasons=reasons);ass={**prof.public_metadata(),'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':shares,'equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Exact faded-cash base.','invalidation':p.invalidation};base=BaselineValuation(ticker=t,method=p.method,method_version=BATCH_21_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ispass else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked history.'),),warnings=(p.warning,p.invalidation),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{t}/calculator');matter,terms=EVENT[t]
 return {'ticker':t,'method':p.method,'model_version':BATCH_21_HISTORY_VERSION,'availability_type':'available' if ispass else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':filing,'flow_sources':flows,'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(t,st,p),'event_sources':[{'source_kind':'controlling_filing_narrative','accession':filing['accession'],'filed':filing['filed'],'period_end':filing['period_end'],'matter':matter,'reported_terms':terms,'reported_vs_estimated':'reported_narrative'}],'bridge_reconciliation':{'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':p.claims,'other_equity_claim_formula':p.formula,'shares':shares},'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
def _txt(filing,st,facts):
 gaap=facts['facts']['us-gaap'];a=annual_facts(gaap,concepts=('NetIncomeLoss',),unit='USD',valuation_date=BATCH_21_VALUATION_DATE);obs=[HistoryObservation('annual',a[y].period_end,a[y].fiscal_year,a[y].value,'USD','reported earnings',(_history_source(a[y]),)) for y in (2021,2022,2023,2024,2025)];ttm=a[2025].value+468e6-452e6;obs.append(HistoryObservation('operating_ttm','2026-07-04',None,ttm,'USD','FY+H1-prior H1',(obs[-1].sources[0],_structural_flow(st,name='NetIncomeLoss',start='2026-01-04',end='2026-07-04',expected=468e6),_structural_flow(st,name='NetIncomeLoss',start='2024-12-29',end='2025-06-28',expected=452e6))));m=summarize_history_metric('normalized_common_earnings',obs);prof=CompanyHistoryProfile(HISTORY_POLICY_VERSION,'mixed_industrial_finance_residual_income',BATCH_21_VALUATION_DATE,tuple(x.period_end for x in obs if x.period_role=='annual'),(m,),True,'reported_and_company_history');earn=(m.low,m.base,m.high);begin,end=7.875e9,8.054e9;avg=(begin+end)/2;shares=_shares(175.591e6,171_986_917.);payout=14e6/ttm;coe=(.12,.10,.085);troe=(.10,.14,.20);tg=(.01,.02,.025);rows=[];traces={};mult=[]
 for i,name in enumerate(('bear','base','bull')):
  tr=residual_income_valuation(book_value_per_share=end/shares[i],current_roe=earn[i]/avg,cost_of_equity=coe[i],current_payout_ratio=payout,terminal_roe=troe[i],terminal_growth=tg[i],years=5);raw=float(tr['intrinsic_value']);mul=raw*shares[i]/earn[i];rows.append({'name':name,'conditional_value_per_share':raw,'raw_value_per_share':raw,'normalized_common_earnings':earn[i],'book_value_per_share':end/shares[i],'current_roe':earn[i]/avg,'current_payout_ratio':payout,'cost_of_equity':coe[i],'terminal_roe':troe[i],'terminal_growth':tg[i],'earnings_multiple':mul,'shares':shares[i],'limited_liability_floor_applied':False});traces[name]=tr;mult.append(mul)
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']};reasons=('CONSOLIDATED_MODEL_FALLBACK','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='Low',source_cap='High',reasons=reasons);warning='Conditional Low mixed aerospace/captive-finance residual-income baseline. Common equity and earnings avoid double-counting Textron Finance funding; aviation cycle and finance receivables remain material.';invalid='Invalidate if aviation demand, finance receivables/credit, common equity, funding, or shares changes materially.';ass={**prof.public_metadata(),'normalized_common_earnings':earn,'earnings_multiples':tuple(mult),'shares':shares,'book_equity':end,'average_common_equity':avg,'current_payout_ratio':payout,'cost_of_equity':coe,'terminal_roe':troe,'terminal_growth':tg,'route_is_equity_level':True,'ev_debt_bridge_applied':False,'equity_floor_basis':'not applied','calculator_calibration':'Exact residual-income base.','invalidation':invalid};base=BaselineValuation(ticker='TXT',method='mixed_aerospace_captive_finance_residual_income_equity_earnings',method_version=BATCH_21_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('common equity',end,AssumptionClassification.REPORTED,'Equity anchor.'),),warnings=(warning,invalid),confidence_reasons=reasons,calculator_link='/api/us-valuations/TXT/calculator')
 return {'ticker':'TXT','method':base.method,'model_version':BATCH_21_HISTORY_VERSION,'availability_type':'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_common_earnings':ttm,'beginning_common_equity':begin,'ending_common_equity':end},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':filing,'company_history_profile':prof.as_private_dict(),'equity_model_context':[_point(st,name='StockholdersEquity',expected=end,period_end='2026-07-04'),_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=175.591e6,period_start='2026-01-04',period_end='2026-07-04'),_share_point(st,expected=171_986_917.,end='2026-07-17'),_no_preferred(st,'2026-07-04')],'event_sources':[{'source_kind':'controlling_filing_narrative','accession':filing['accession'],'filed':filing['filed'],'period_end':filing['period_end'],'matter':'Textron manufacturing and Finance economics','reported_terms':{'finance_receivables_usd':468e6},'reported_vs_estimated':'reported_narrative'}],'residual_income_trace':{'states':traces},'bridge_treatment':'Equity-level; finance funding remains inside earnings/equity.','structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':warning,'baseline':base.as_private_dict()}
def build_batch_21_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 p=Path(source_root)/ticker;subs=json.loads((p/'submissions.json').read_text());facts=json.loads((p/'companyfacts.json').read_text());m=json.loads((p/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,subs)
 if st['source_accession']!=f['accession']:raise ValueError(ticker)
 return _txt(f,st,facts) if ticker=='TXT' else _operating(ticker,f,st,subs,facts)
if set(P)|{'TXT'}!=set(BATCH_21_TICKERS):raise RuntimeError('Batch21 mismatch')
