"""History-backed practical baselines for controlled Universe Reset Batch 28."""
from __future__ import annotations
import copy,json
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from .baseline import AssumptionClassification,AvailabilityType,BaselineAssumption,BaselineValuation
from .batch_02_practical_inputs import _normalizer,_normalized_tax_rate,cash_fcff_from_reported
from .batch_04_launch_first import _controlling,_duration,_point
from .batch_07_history import _structural_flow
from .batch_08_history import _annual_cash_with_losses
from .batch_11_history import _no_preferred
from .batch_16_history import _share_point
from .batch_28 import BATCH_28_TICKERS,BATCH_28_VALUATION_DATE
from .history import build_cash_fcff_history_profile
from .practical_models import EnterpriseCashFlowState,enterprise_cash_flow_dcf
from .reliability import assess_reliability
from .xbrl import load_concept_config
BATCH_28_HISTORY_VERSION='BATCH-28-TECHNOLOGY-HISTORY-1.0';FORECAST_YEARS=8
PASS_TICKERS=frozenset({'FICO','ZBRA'});CONDITIONAL_TICKERS=frozenset({'QCOM','CDNS','MCHP','GEN','PTC','CSCO','TYL','JBL'});WITHHELD_TICKERS=frozenset()
def _shares(w,c):hi=max(w,c);lo=min(w,c);return hi,(hi+lo)/2,lo
@dataclass(frozen=True)
class Policy:
 method:str;period:str;cash:float;debt:float;claims:float;shares:tuple[float,float,float];growth:tuple[float,float,float];wacc:tuple[float,float,float];terminal:tuple[float,float,float];warning:str;invalid:str;formula:str
P={
'QCOM':Policy('post_alphawave_post_modular_semiconductor_faded_fcff','2026-06-28',8.304e9,15.270e9,0.,_shares(1.073e9,1.068e9),(-.05,.03,.08),(.11,.095,.085),(0.,.01,.02),'Conditional Low post-Alphawave/post-Modular semiconductor and licensing baseline. Modular closed July 28 for approximately $3.1B primarily in 18M shares, but no preliminary acquired allocation was practicable; Alphawave/Modular conversion, licensing mix, and capital allocation remain material.','Invalidate if Modular purchase accounting/acquired cash or the 18M-share state changes, or if Alphawave conversion, licensing cash, debt, or securities changes.','$4.533B cash + $3.771B marketable securities; $15.270B total debt. Scenario shares include the reported 18M Modular issuance; prior restricted acquisition cash was consumed and is not added again.'),
'CDNS':Policy('post_acquisition_eda_software_faded_fcff','2026-06-30',1.520670e9,2.4822e9,0.,_shares(274.948e6,275_393_000.),(.02,.08,.12),(.11,.095,.085),(.01,.02,.025),'Conditional Low post-acquisition EDA-software baseline. Structurally repaired H1 cash history is finite, while $2.100B acquisition cash, $902M acquisition stock, acquired conversion, goodwill, integration, SBC, and debt remain material.','Invalidate if acquired conversion, purchase accounting, EDA/AI growth, SBC/dilution, debt, securities, or shares changes.','$1.440443B cash + $80.227M AFS securities; $2.4822B debt carrying amount. Acquisition cash/stock is not deducted again because acquired operations remain consolidated.'),
'FICO':Policy('credit_scoring_analytics_faded_fcff','2026-06-30',304.537e6,5.582389e9,0.,_shares(23.470e6,21_597_635.),(0.,.07,.12),(.11,.095,.085),(.01,.02,.025),'Source-bounded credit-scoring and analytics baseline. Five-year cash history, current cash/securities, debt, SBC/buybacks, and shares reconcile; mortgage/auto cycles are ranged.','Invalidate if scoring/pricing, mortgage/auto demand, cash conversion, debt, SBC/buybacks, securities, or shares changes.','$248.444M cash + $56.093M noncurrent marketable securities; $300M current + $5.282389B noncurrent debt.'),
'MCHP':Policy('mandatory_convertible_preferred_analog_semiconductor_recovery_faded_fcff','2026-06-30',272.3e6,5.3989e9,0.,_shares(550.5e6,543_008_691.),(-.08,.02,.07),(.12,.105,.095),(0.,.01,.02),'Conditional Low analog-semiconductor recovery baseline. Five-year history includes the severe downturn. The Series A preferred is modeled as seven remaining quarterly dividends followed by the reported March 2028 mandatory conversion range; the capped-call offset is excluded because its realized benefit is uncertain.','Invalidate if semiconductor demand, preferred dividends/conversion or capped-call treatment, inventory cash conversion, debt/commercial paper, capex, or shares changes.','$272.3M cash; $5.3989B debt. The $1.485B liquidation preference is not also deducted because the modeled March 2028 conversion supersedes it; dividend PV and conversion dilution are deducted once.'),
'GEN':Policy('mixed_cybersecurity_instacash_faded_fcff','2026-07-03',533e6,8.230e9,0.,_shares(603e6,598_587_032.),(-.02,.03,.06),(.11,.095,.085),(0.,.01,.02),'Conditional Low mixed cybersecurity/Trust-Based Solutions baseline. Current cash is finite, while Instacash originations/sales and held-for-sale advances enter operating cash alongside subscription economics; post-MoneyLion conversion, leverage, and restructuring remain material.','Invalidate if Instacash originations/sales, financial-asset funding, subscription retention, restructuring, goodwill, debt/refinancing, or shares changes.','$533M unrestricted cash; $31M restricted cash excluded; $8.230B debt. $1.193B originations and $1.107B sales stay inside consolidated cash conversion and are not treated as issuer cash.'),
'PTC':Policy('post_kepware_thingworx_divestiture_faded_fcff','2026-06-30',351.454e6,1.423315e9,0.,_shares(117.844e6,108_506_261.),(0.,.06,.10),(.11,.095,.085),(.01,.02,.025),'Conditional Low post-Kepware/ThingWorx-divestiture industrial SaaS baseline. Current value is finite, while historical consolidated cash includes the sold operations and the $523.3M proceeds, $7.5M expected payment, $462.6M gain, and up to $125M contingent consideration make continuing scope provisional.','Invalidate if divestiture consideration/contingency, continuing cash/revenue, subscription transition, SBC/dilution, debt, investments, or shares changes.','$351.454M cash; $1.423315B debt. Sale proceeds already reflected in cash are not added again.'),
'CSCO':Policy('post_splunk_networking_software_faded_fcff','2026-04-25',16.640e9,31.303e9,0.,_shares(3.987e9,3_941_434_665.),(-.02,.03,.07),(.105,.09,.08),(.005,.015,.025),'Conditional Low post-Splunk networking/software baseline. Five-year cash history is finite, while software integration, recurring-revenue conversion, $31.303B debt, restructuring, SBC, and portfolio mix remain material.','Invalidate if Splunk integration/software conversion, product demand, securities, debt/commercial paper, restructuring, SBC, or shares changes.','$7.083B cash + $9.557B short-term investments; $11.932B current debt plus $19.371B noncurrent debt. The $23.002B debt-instrument fact is a component, not the complete total.'),
'TYL':Policy('post_bftr_government_software_faded_fcff','2026-06-30',1.015267e9,1.408691e9,0.,_shares(41.853e6,40_952_274.),(.02,.07,.11),(.11,.095,.085),(.01,.02,.025),'Conditional Low post-acquisition government-software baseline. Four-year cash history is finite, while the $257.771M BFTR transaction, acquired conversion, convertible debt/dilution, SBC, integration, and $537.4M through-2031 purchase obligation remain material. The commitment uses governed 3/4/5-year timing, all within the reported endpoint.','Invalidate if BFTR conversion/purchase accounting, purchase-obligation timing, recurring revenue, convertible debt/dilution, SBC, investments, or shares changes.','$895.353M cash + $119.914M complete AFS securities; $1.408691B convertible debt. The $537.4M obligation is modeled through timed PV reserves within the reported 2031 endpoint.'),
'ZBRA':Policy('asset_intelligence_hardware_cycle_faded_fcff','2026-07-04',157e6,2.776e9,0.,_shares(48_776_549.,47_310_660.),(-.05,.02,.06),(.11,.095,.085),(0.,.01,.02),'Source-bounded asset-intelligence hardware/software baseline. Five-year cash history includes the device downturn; cash, complete debt, preferred absence, restructuring, cash-interest lineage, and shares reconcile. The $96M nonmarketable Skild AI stake is recorded but excluded from issuer cash.','Invalidate if device demand, inventory/working capital, software mix, restructuring, nonmarketable investments, debt/refinancing, or shares changes.','$157M cash; the $96M nonmarketable Skild AI stake is recorded but excluded from cash. $2.776B complete debt; $68M unremitted collections are operating customer funds, not issuer cash.'),
'JBL':Policy('post_acquisition_ems_working_capital_faded_fcff','2026-05-31',1.360e9,3.378e9,55e6,_shares(107.2e6,104_787_089.),(-.04,.03,.07),(.11,.095,.085),(0.,.01,.02),'Conditional Low post-acquisition EMS baseline. Five-year cash history is finite, while $852M acquisition cash, $384M acquired goodwill, acquired conversion, restructuring, NCI, finance-lease obligations, and working-capital volatility remain material.','Invalidate if acquisition conversion/purchase accounting, EMS working capital, restructuring, supplier finance, finance leases, debt, NCI, or shares changes.','$1.360B cash; $3.378B debt; $4M NCI + $51M finance-lease payment obligation. Net-interest lineage is consistent but represents accrual net interest rather than cash interest paid.'),
}
POINT={
'QCOM':(('CashAndCashEquivalentsAtCarryingValue',4.533e9),('MarketableSecuritiesCurrent',3.771e9),('DebtCurrent',2.489e9),('LongTermDebt',12.781e9),('PreferredStockValue',0.)),
'CDNS':(('CashAndCashEquivalentsAtCarryingValue',1.440443e9),('AvailableForSaleSecuritiesDebtSecurities',80.227e6),('UnsecuredLongTermDebt',2.4822e9)),
'FICO':(('CashAndCashEquivalentsAtCarryingValue',248.444e6),('MarketableSecuritiesNoncurrent',56.093e6),('LongTermDebtCurrent',300e6),('LongTermDebtNoncurrent',5.282389e9)),
'MCHP':(('CashAndCashEquivalentsAtCarryingValue',272.3e6),('DebtInstrumentCarryingAmount',5.3989e9),('PreferredStockValue',0.),('PreferredStockSharesOutstanding',1.485e6),('PreferredStockLiquidationPreferenceValue',1.485e9)),
'GEN':(('Cash',384e6),('CashEquivalentsAtCarryingValue',149e6),('RestrictedCash',31e6),('DebtInstrumentCarryingAmount',8.230e9)),
'PTC':(('CashAndCashEquivalentsAtCarryingValue',351.454e6),('DebtLongtermAndShorttermCombinedAmount',1.423315e9),('PreferredStockValue',0.)),
'CSCO':(('CashAndCashEquivalentsAtCarryingValue',7.083e9),('ShortTermInvestments',9.557e9),('DebtCurrent',11.932e9),('LongTermDebtNoncurrent',19.371e9),('PreferredStockValue',0.)),
'TYL':(('CashAndCashEquivalentsAtCarryingValue',895.353e6),('DebtSecuritiesAvailableForSaleExcludingAccruedInterest',119.914e6),('DebtLongtermAndShorttermCombinedAmount',1.408691e9),('PreferredStockValue',0.)),
'ZBRA':(('CashAndCashEquivalentsAtCarryingValue',157e6),('LongTermInvestments',96e6),('DebtInstrumentCarryingAmount',2.776e9),('PreferredStockValue',0.)),
'JBL':(('CashAndCashEquivalentsAtCarryingValue',1.360e9),('LongTermDebtCurrent',499e6),('LongTermDebtNoncurrent',2.879e9),('MinorityInterest',4e6),('FinanceLeaseLiabilityPaymentsDue',51e6),('PreferredStockValue',0.)),}
START={'QCOM':'2025-09-29','CDNS':'2026-01-01','FICO':'2025-10-01','MCHP':'2026-04-01','GEN':'2026-04-04','PTC':'2025-10-01','CSCO':'2025-07-27','TYL':'2026-01-01','ZBRA':'2026-01-01','JBL':'2025-09-01'}
WEIGHTED={'QCOM':1.073e9,'CDNS':274.948e6,'FICO':23.470e6,'MCHP':550.5e6,'GEN':603e6,'PTC':117.844e6,'CSCO':3.987e9,'TYL':41.853e6,'ZBRA':48_776_549.,'JBL':107.2e6}
CURRENT={'QCOM':1.068e9,'CDNS':275_393_000.,'FICO':21_597_635.,'MCHP':543_008_691.,'GEN':598_587_032.,'PTC':108_506_261.,'CSCO':3_941_434_665.,'TYL':40_952_274.,'ZBRA':47_310_660.,'JBL':104_787_089.}
END={'QCOM':'2026-07-27','CDNS':'2026-06-30','FICO':'2026-07-17','MCHP':'2026-07-28','GEN':'2026-08-04','PTC':'2026-07-29','CSCO':'2026-05-14','TYL':'2026-07-27','ZBRA':'2026-07-28','JBL':'2026-06-24'}
def _norm(t,sub,facts):
 if t not in {'GEN','ZBRA'}:return _normalizer(sub,facts)
 c=copy.deepcopy(load_concept_config());c['fields']['interest_expense']['concepts']=[{'GEN':'InterestAndDebtExpense','ZBRA':'InterestPaidNet'}[t]];return _normalizer(sub,facts,concept_config=c)
def _cdns_flows(n,st):
 specs={'revenue':('RevenueFromContractWithCustomerExcludingAssessedTax',3_058_671_000.,2_517_807_000.),'operating_cash_flow':('NetCashProvidedByUsedInOperatingActivities',990_711_000.,864_624_000.),'capital_expenditures':('PaymentsToAcquirePropertyPlantAndEquipment',101_448_000.,67_146_000.),'interest_expense':('InterestExpense',66_749_000.,58_066_000.)};out={}
 for field,(concept,cur,prior) in specs.items():
  base=n.ttm_flow(field);annual=dict(base['sources'][0]);c=_structural_flow(st,name=concept,start='2026-01-01',end='2026-06-30',expected=cur);p=_structural_flow(st,name=concept,start='2025-01-01',end='2025-06-30',expected=prior);out[field]={'field':field,'value':annual['value']+cur-prior,'period_end':'2026-06-30','method':'latest_fy_plus_structural_current_ytd_minus_prior_ytd','sources':[annual,c,p],'current_ytd':c,'prior_ytd':p}
 return out
def _fact(st,name,value,start,end,allow_dimensions=False):
 rows=[r for r in st['facts'] if r.get('local_name')==name and r.get('period_start')==start and r.get('period_end')==end and (allow_dimensions or not r.get('dimensions')) and isinstance(r.get('value'),(int,float)) and float(r['value'])==value]
 if not rows:raise ValueError(f'{name}={value} absent')
 r=rows[0];return {'source_kind':'structural_xbrl','accession':st['source_accession'],'filed':st.get('filed_date'),'period_start':start,'period_end':end,'concept':r.get('qname'),'unit':r.get('unit'),'value':value,'dimensions':r.get('dimensions',[]),'reported_vs_estimated':'reported'}
def _point_reported_unit(st,name,value,period_end):
 rows=[r for r in st['facts'] if r.get('local_name')==name and r.get('period_start') is None and r.get('period_end')==period_end and not r.get('dimensions') and isinstance(r.get('value'),(int,float)) and float(r['value'])==value]
 if not rows:raise ValueError(f'{name}={value} absent')
 r=rows[0];return {'source_kind':'structural_xbrl','accession':st['source_accession'],'filed':st.get('filed_date'),'period_end':period_end,'concept':r.get('qname'),'unit':r.get('unit'),'value':value,'reported_vs_estimated':'reported'}
def _bridge(t,st,p):
 rows=[_point_reported_unit(st,n,v,p.period) if n=='PreferredStockSharesOutstanding' else _point(st,name=n,expected=v,period_end=p.period) for n,v in POINT[t]]+[_duration(st,name='WeightedAverageNumberOfDilutedSharesOutstanding',expected=WEIGHTED[t],period_start=START[t],period_end=p.period)]
 if t=='QCOM':rows.append({'source_kind':'subsequent_event_share_bridge','accession':st['source_accession'],'filed':st.get('filed_date'),'period_end':'2026-07-28','pre_close_entity_shares':1.050e9,'modular_shares_issued':18e6,'post_close_shares':1.068e9,'reported_vs_estimated':'reported_event_overlay'})
 else:rows.append(_share_point(st,expected=CURRENT[t],end=END[t]))
 if t=='MCHP':rows.append({'source_kind':'mandatory_convertible_preferred_treatment','accession':st['source_accession'],'filed':st.get('filed_date'),'period_end':p.period,'preferred_shares':1.485e6,'liquidation_preference':1.485e9,'preferred_stock_value':0.,'annual_dividend_rate':.075,'automatic_conversion_date':'2028-03-15','conversion_rate_range':(16.006,19.608),'reported_vs_estimated':'reported_terms_with_governed_dividend_pv_and_conversion_dilution'})
 else:rows.append(_no_preferred(st,p.period))
 return rows
def _events(t,f,st,p):
 rows=[{'source_kind':'controlling_filing_narrative','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':p.warning,'reported_vs_estimated':'reported_narrative'}]
 specs={'QCOM':(('BusinessCombinationConsiderationTransferred1',2.3e9,'2025-12-18','2025-12-18',True),('BusinessCombinationConsiderationTransferred1',3.1e9,'2026-07-28','2026-07-28',True),('PaymentsToAcquireBusinessesGross',1.1e9,'2025-09-29','2026-06-28',True)),'CDNS':(('PaymentsToAcquireBusinessesNetOfCashAcquired',2_100_292_000.,'2026-01-01','2026-06-30',False),('GoodwillAcquiredDuringPeriod',2_198_007_000.,'2026-01-01','2026-06-30',False),('StockIssuedDuringPeriodValueAcquisitions',902_208_000.,'2026-01-01','2026-06-30',False)),'MCHP':(('PreferredStockDividendsIncomeStatementImpact',27.8e6,'2026-04-01','2026-06-30',False),),'GEN':(('OriginationsOfCertainTradeReceivablesHeldForSale',-1.193e9,'2026-04-04','2026-07-03',False),('ProceedsFromSaleOfLoansReceivable',1.107e9,'2026-04-04','2026-07-03',False),('IncreaseDecreaseInReceivablesPurchaseAgreementAdvancesHeldForSale',-86e6,'2026-04-04','2026-07-03',False)),'PTC':(('ProceedsFromDivestitureOfBusinesses',523.306e6,'2025-10-01','2026-06-30',False),('GainLossOnSaleOfBusiness',462.6e6,'2025-10-01','2026-06-30',True),('ContingentConsideration',125e6,'2025-11-05','2025-11-05',True)),'CSCO':(('PaymentsToAcquireBusinessesNetOfCashAcquired',46e6,'2025-07-27','2026-04-25',False),),'TYL':(('BusinessCombinationConsiderationTransferred1',257_771_000.,'2026-04-14','2026-04-14',True),('PaymentsToAcquireBusinessesNetOfCashAcquired',214_291_000.,'2026-01-01','2026-06-30',False),('PurchaseObligation',537.4e6,None,'2026-06-30',False)),'JBL':(('PaymentsToAcquireBusinessesNetOfCashAcquired',852e6,'2025-09-01','2026-05-31',False),('GoodwillAcquiredDuringPeriod',384e6,'2025-09-01','2026-05-31',False))}
 rows.extend(_fact(st,n,v,s,e,a) for n,v,s,e,a in specs.get(t,()))
 if t=='QCOM':rows.append({'source_kind':'controlling_filing_subsequent_event','accession':f['accession'],'filed':f['filed'],'period_end':'2026-07-28','matter':'Modular acquisition completed','reported_terms':{'consideration_usd':3.1e9,'shares_issued':18e6,'executive_service_shares_included':4e6,'preliminary_allocation_practicable':False},'reported_vs_estimated':'reported'})
 if t=='MCHP':rows.append({'source_kind':'controlling_filing_preferred_terms','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'reported_terms':{'preferred_shares':1.485e6,'liquidation_preference_per_share_usd':1000.,'annual_dividend_rate':.075,'quarterly_dividend_per_share_usd':18.75,'automatic_conversion_date':'2028-03-15','minimum_conversion_rate':16.006,'maximum_conversion_rate':19.608,'capped_call_cap_price_usd':71.40},'reported_vs_estimated':'reported'})
 if t=='PTC':rows.append({'source_kind':'controlling_filing_divestiture','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'reported_terms':{'cash_received_usd':523.306e6,'cash_expected_usd':7.5e6,'gain_usd':462.6e6,'net_assets_sold_usd':68.2e6,'maximum_contingent_consideration_usd':125e6},'reported_vs_estimated':'reported'})
 if t=='CSCO':rows.append({'source_kind':'controlling_filing_integration_trace','accession':f['accession'],'filed':f['filed'],'period_end':f['period_end'],'matter':'post-Splunk networking/software integration','reported_terms':{'nonmarketable_investments_excluded_from_cash_usd':2.946e9,'complete_debt_usd':31.303e9},'reported_vs_estimated':'reported_current_state'})
 return rows
def build_batch_28_history_result(*,ticker:str,source_root:Path,structural_root:Path):
 if ticker not in BATCH_28_TICKERS:raise ValueError(ticker)
 p=P[ticker];q=Path(source_root)/ticker;sub=json.loads((q/'submissions.json').read_text());facts=json.loads((q/'companyfacts.json').read_text());m=json.loads((q/'source-manifest.json').read_text());st=json.loads((Path(structural_root)/ticker/'structural-filing.json').read_text());f=_controlling(m,sub)
 if st['source_accession']!=f['accession'] or f['period_end']!=p.period:raise ValueError(ticker)
 n=_norm(ticker,sub,facts);flows=_cdns_flows(n,st) if ticker=='CDNS' else {x:n.ttm_flow(x) for x in ('revenue','operating_cash_flow','capital_expenditures','interest_expense')}
 try:tax,taxsrc=_normalized_tax_rate(n)
 except ValueError:tax,taxsrc=.21,()
 fallback=not .05<=tax<=.30
 if fallback:tax=.21
 current=cash_fcff_from_reported(operating_cash_flow=float(flows['operating_cash_flow']['value']),capital_expenditures=float(flows['capital_expenditures']['value']),spectrum_investment=0.,interest_expense=abs(float(flows['interest_expense']['value'])),tax_rate=tax);annual=_annual_cash_with_losses(n)[2];sources=[dict(x) for v in flows.values() for x in v.get('sources',[])];rev=float(flows['revenue']['value']);prof=build_cash_fcff_history_profile(annual_cash_states=annual,ttm_revenue=rev,ttm_cash_fcff=current,ttm_period_end=p.period,ttm_sources=sources,valuation_date=BATCH_28_VALUATION_DATE);cm,gm=prof.metric('cash_conversion_margin'),prof.metric('revenue_growth')
 if cm is None or gm is None or not prof.full_history:raise ValueError(f'{ticker}: history unavailable')
 margins=tuple(max(.001,float(x)) for x in (cm.low,cm.base,cm.high));growth=(max(-.1,min(p.growth[0],gm.low)),max(-.08,min(p.growth[1],gm.base)),max(0.,min(p.growth[2],gm.high)));rows=[];traces={}
 commitment_schedule=None;preferred_schedule=None;scenario_claims=(p.claims,p.claims,p.claims);scenario_shares=p.shares
 if ticker=='MCHP':
  preferred_shares=1.485e6
  conversion_rates=(19.608,(19.608+16.006)/2,16.006)
  conversion_shares=tuple(preferred_shares*rate for rate in conversion_rates)
  scenario_shares=tuple(p.shares[i]+conversion_shares[i] for i in range(3))
  quarterly_dividend=preferred_shares*18.75
  remaining_quarters=7
  dividend_pv=tuple(sum(quarterly_dividend/((1+p.wacc[i])**(quarter/4)) for quarter in range(1,remaining_quarters+1)) for i in range(3))
  scenario_claims=dividend_pv
  preferred_schedule={'reported_preferred_shares':preferred_shares,'reported_liquidation_preference':1.485e9,'reported_annual_dividend_rate':.075,'reported_quarterly_dividend_per_share':18.75,'remaining_quarters':remaining_quarters,'automatic_conversion_date':'2028-03-15','conversion_rate':conversion_rates,'conversion_shares':conversion_shares,'dividend_present_value':dividend_pv,'capped_call_treatment':'excluded because realized dilution offset is uncertain','liquidation_preference_treatment':'not separately deducted because mandatory conversion is modeled'}
 if ticker=='TYL':
  commitment_years=(3,4,5)
  commitment_total=537.4e6
  commitment_annual=tuple(commitment_total/y for y in commitment_years)
  commitment_pv=tuple(sum(commitment_annual[i]/((1+p.wacc[i])**year) for year in range(1,commitment_years[i]+1)) for i in range(3))
  scenario_claims=tuple(p.claims+commitment_pv[i] for i in range(3))
  commitment_schedule={'reported_total':commitment_total,'payment_years':commitment_years,'annual_payment':commitment_annual,'present_value_reserve':commitment_pv,'treatment':'scenario-timed present-value reserve deducted once from enterprise value'}
 for i,name in enumerate(('bear','base','bull')):
  s=EnterpriseCashFlowState(rev*margins[i],growth[i],p.terminal[i],p.wacc[i],p.cash,p.debt,0.,scenario_claims[i],scenario_shares[i]);tr=enterprise_cash_flow_dcf(s,forecast_years=FORECAST_YEARS,allow_nonpositive_equity_trace=True);raw=float(tr['intrinsic_value_per_share']);rows.append({'name':name,'conditional_value_per_share':max(0.,raw),'raw_value_per_share':raw,'starting_cash_fcff':s.cash_fcff,'cash_conversion_margin':margins[i],'growth':growth[i],'wacc':p.wacc[i],'terminal_growth':p.terminal[i],'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':scenario_claims[i],'shares':scenario_shares[i],'limited_liability_floor_applied':raw<0});traces[name]=tr
 sc={'low':rows[0]['conditional_value_per_share'],'base':rows[1]['conditional_value_per_share'],'high':rows[2]['conditional_value_per_share']}
 if not 0<=sc['low']<=sc['base']<=sc['high'] or sc['base']<=0:raise ValueError(ticker)
 ok=ticker in PASS_TICKERS;reasons=() if ok else ('CONDITIONAL_EVENT_MODEL','SPECIALIST_MODEL_UNCERTAINTY');rel=assess_reliability(accounting_low=sc['base'],accounting_base=sc['base'],accounting_high=sc['base'],scenario_low=sc['low'],scenario_base=sc['base'],scenario_high=sc['high'],model_cap='High' if ok else 'Low',source_cap='High',reasons=reasons);pub=prof.public_metadata()
 if not ok:pub.update({'normalization_basis':'company_history_with_named_material_acquisition_dependency','assumption_source_mix':'reported_history_and_finsight_policy'})
 ass={**pub,'forecast_years':FORECAST_YEARS,'cash_conversion_margin':margins,'growth':growth,'wacc':p.wacc,'terminal_growth':p.terminal,'shares':scenario_shares,'tax_rate_basis':'governed 21% fallback' if fallback else 'normalized filing history','equity_floor_basis':'limited-liability bear floor with raw residual retained' if sc['low']==0 else 'not applied','calculator_calibration':'Calculator is calibrated to the exact faded-cash base.','invalidation':p.invalid}
 if preferred_schedule is not None:ass['mandatory_convertible_preferred_schedule']=preferred_schedule
 if commitment_schedule is not None:ass['purchase_obligation_schedule']=commitment_schedule
 base=BaselineValuation(ticker=ticker,method=p.method,method_version=BATCH_28_HISTORY_VERSION,low=sc['low'],base=sc['base'],high=sc['high'],confidence=rel.label,availability_type=AvailabilityType.AVAILABLE if ok else AvailabilityType.CONDITIONAL,key_assumptions=(BaselineAssumption('company history',str(prof.history_years_used),AssumptionClassification.HISTORICALLY_DERIVED,'Source-linked annual and current cash conversion anchors the range.'),),warnings=(p.warning,p.invalid),confidence_reasons=tuple(rel.reasons),calculator_link=f'/api/us-valuations/{ticker}/calculator')
 bridge_reconciliation={'cash_and_investments':p.cash,'debt_and_finance_leases':p.debt,'other_equity_claims':scenario_claims,'other_equity_claim_formula':p.formula,'shares':scenario_shares,'operating_liability_treatment':'Operating leases, supplier finance, customer funds, SBC, and ordinary working capital remain inside operating cash conversion and are not deducted twice.'}
 if preferred_schedule is not None:bridge_reconciliation['mandatory_convertible_preferred_schedule']=preferred_schedule
 if commitment_schedule is not None:bridge_reconciliation['purchase_obligation_schedule']=commitment_schedule
 return {'ticker':ticker,'method':p.method,'model_version':BATCH_28_HISTORY_VERSION,'availability_type':'available' if ok else 'conditional_estimate','scenario_rows':rows,'scenario_range':sc,'reported_inputs':{'ttm_revenue':rev,'ttm_operating_cash_flow':flows['operating_cash_flow']['value'],'ttm_reinvestment':flows['capital_expenditures']['value'],'ttm_interest':flows['interest_expense']['value'],'tax_rate':tax,'ttm_cash_fcff':current},'governed_assumptions':ass,'history_reliability':rel.as_dict(),'source_ledger':{'controlling_filing':f,'flow_sources':flows,'annual_cash_sources':list(annual),'tax_rate_sources':list(taxsrc),'tax_rate_treatment':{'fallback_applied':fallback,'rate':tax},'company_history_profile':prof.as_private_dict(),'bridge_sources':_bridge(ticker,st,p),'event_sources':_events(ticker,f,st,p),'bridge_reconciliation':bridge_reconciliation,'model_trace':{'forecast_years':FORECAST_YEARS,'states':traces},'structural_top_level_period_diagnostic':{'value':st.get('period_end'),'used_for_selection':False}},'warning':p.warning,'baseline':base.as_private_dict()}
if set(P)!=set(BATCH_28_TICKERS) or PASS_TICKERS|CONDITIONAL_TICKERS|WITHHELD_TICKERS!=set(BATCH_28_TICKERS):raise RuntimeError('Batch28 mismatch')
